-- [HE-PORT]

function balance.load_config()
	local bcfg = "default"
	if level and level.get_game_difficulty then
		bcfg = ( tonumber( level.get_game_difficulty() ) == 0 and "light" ) or "default"
	end
	local rel = sprintf( "balance_%s.ltx", bcfg )
	local fs = getFS()
	local fname = fs:update_path( "$game_config$", rel )
	if not fs:exist( fname ) then
		return
	end
	local ini = ini_file( rel )
	ini:iterate_sections( function( scn )
		local tab = {}
		for n = 0, ini:line_count( scn ) - 1 do
			local r, k, v = ini:r_line( scn, n, "", "" )
			if k and k ~= "" then
				local num = tonumber( v )
				if num ~= nil then
					tab[ k ] = num
				else
					tab[ k ] = v
				end
			end
		end
		balance[ scn ] = tab
	end )
end

function init_module()
	balance.load_config()
end

function late_init() end

balance.load_config()
