local teleport_particle = particles_object( "anomaly2\\teleport" )
local teleport_snd 		= sound_object( "anomaly\\teleport_work_2" )

function set_st_conds(obj)
	if obj then
		local conds = {}
		conds["none"] = xr_logic.parse_condlist(obj, "smart_terrains", "none", "true")
		obj.smart_terrain_conditions = conds
		sak.obj_off_on(obj)
	end
end

function x10_after_switch_rats()
	if has_alife_info("x10_switch_on_rats") then return end
	local table_monsters={
				"rat_mad_weak",
				"rat_mad_wery_strong",
				"rat_mad_normal",
				"rat_mad_strong",
				"rat_mad_wery_strong"
				}
	local table_spawn={
				{-19.976345062256,-9.5,-56.663566589355,3769,3636},
				{-22.296869277954,-9.5,-0.93966680765152,3446,3633},
				{-20.998249053955,-8.95,17.489625930786,3727,3629},
				{-0.27049475908279,-8.95,-7.6065130233765,6901,3660},
				{-12.827882766724,-21.9,52.936962127686,4544,3643},
				{8.6156625747681,-21.9,53.920192718506,9242,3682}
				}
	local timer=17131
	for ii=1,8 do
		for i=1,#table_spawn do
		local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = x10_rats_"..i.."\nhome_min_radius = 20\nhome_max_radius = 40\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = "..timer.." | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = "..tostring(timer+1234).." | mob_home"
			timer=timer+1100
			local zomb=table_monsters[lua_random(#table_monsters)]
			local point=table_spawn[i]
			local obj=alife():create(zomb,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
			local pk = get_netpk(obj)
			local data = pk:get()
			data.custom_data = logic
			pk:set(data)	
			set_st_conds(obj)
		end
	end
	db.actor:give_info_portion("x10_switch_on_rats")
end

function dead_after_fedotov_monsters(force)
	local table_spawn={
				{86.828010559082,1.0300453901291,38.787406921387,319520,3894},
				{31.7847,1.2499,-111.8160,320865,3889},
				{-74.665702819824,1.5174041986465,106.16954803467,315203,3894},
				{-67.025596618652,1.2036197185516,-197.37725830078,240678,3844}
				}
	local timer=17131
	local bs="bloodsucker_strong"
	local point, obj = nil, nil
	for ii=1,2 do
		if force and type(force) == 'boolean' then
			if ii == 1 then
				point = {49.2934,1.2496,-69.0855,333861,3905}
			else
				point = table_spawn[2]
			end
			local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = dead_bloodsuckers_new\nhome_min_radius = 10\nhome_max_radius = 70\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 3000 | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = "..tostring(timer+1234).." | mob_home"
			obj=alife():create(bs,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
			local pk = get_netpk(obj)
			local data = pk:get()
			data.custom_data = logic
			pk:set(data)	
			teleport_particle:play_at_pos( sak.v3f(point[1],point[2],point[3]) )
			teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(point[1],point[2],point[3]), 1.0 )
			set_st_conds(obj)
		else
			for i=1,#table_spawn do
				local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = dead_bloodsuckers"..i.."\nhome_min_radius = 35\nhome_max_radius = 110\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = "..timer.." | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = "..tostring(timer+1234).." | mob_home"
				timer=timer+1100
				point=table_spawn[i]
				obj=alife():create(bs,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
				local pk = get_netpk(obj)
				local data = pk:get()
				data.custom_data = logic
				pk:set(data)	
				teleport_particle:play_at_pos( sak.v3f(point[1],point[2],point[3]) )
				teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(point[1],point[2],point[3]), 1.0 )
				set_st_conds(obj)
			end
		end
	end
end

function rad_near_scaner_monsters()
	local table_monsters={
				"snork_strong",
				"snork_strong",
				"snork_strong",
				"snork_strong",
				"bloodsucker_normal",
				}
	local table_spawn={
				{497.50897216797,-53.891983032227,-135.75592041016,165452,2049},
				{494.73611450195,-54.386772155762,-152.03329467773,164248,2049},
				{466.44006347656,-53.581493377686,-175.33825683594,155854,2055},
				{511.5114440918,-45.064025878906,-211.03578186035,171591,2057},
				{524.28405761719,-48.448532104492,-186.93353271484,177398,2056}
				}
	local timer=17131
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = rad_near_scaner_home_1\nhome_min_radius = 35\nhome_max_radius = 110\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = "..timer.." | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 16321 | mob_home"
	for i=1,#table_spawn do
		timer=timer+1100
		local zomb=table_monsters[i]
		local point=table_spawn[i]
		local obj=alife():create(zomb,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)	
		teleport_particle:play_at_pos( sak.v3f(point[1],point[2],point[3]) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(point[1],point[2],point[3]), 1.0 )
		set_st_conds(obj)
	end
end

function dsc_1_monsters_add()
	local table_monsters={
				{"pseudodog_normal",2},
				{"tushkano_normal",10},
				{"dog_normal",6},
				{"boar_normal",3}
				}
	local table_spawn={
				{position={x=-386.58489990234,y=0.53244173526764,z=-534.90270996094},gv=3950,lv=60529},
				{position={x=-411.24545288086,y=0.27787283062935,z=-441.29388427734},gv=3946,lv=49558},
				{position={x=-463.40411376953,y=0.79835343360901,z=-449.8525390625},gv=3939,lv=31578},
				{position={x=-512.77069091797,y=1.9909368753433,z=-509.19580078125},gv=3937,lv=20537}
				}
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local rand_point=lua_random(#table_spawn)
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\dsc\\dsc_1_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

function add_x18_gigant()
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\dar\\dar_gigant.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	local obj=alife():create("gigant_normal",sak.v3f(18.757219314575,-10.819721221924,-22.1803855896),5628,1157)
	local pk = get_netpk(obj)
	local data = pk:get()
	data.custom_data = logic
	data.base_out_restrictors = "dar_poltergeist_territory"
	pk:set(data)
	set_st_conds(obj)
	dsh.timeout(1000, function() sak_spawn.add_x18_gigant_snd(obj.id) end)
end

function add_x18_gigant_snd(id)
	local c_obj = id and client_obj(id)
	if c_obj then
		local snd = xr_sound.get_safe_sound_object([[monsters\giant\giant_underground_0]])
		snd:play_no_feedback(c_obj, sound_object.s3d, 0, c_obj:position(), 1.0)
	end
end

function add_esc_monsters()
	local logic="[smart_terrains]\nesc_road_tushkans=true"
	for i=1,5 do
		local obj=alife():create("tushkano_normal",sak.v3f(-80.501472473145,-7.1152625083923,-115.44844818115),187545,109)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		sak.obj_off_on(obj)
	end
end

function add_esc_ambush_monsters()
	local m=get_value("r_treas_items",1)
	local table_monsters={
				{"cat_normal",4},
				{"tushkano_normal",7},
				{"dog_normal",5}
				}
	local logic="[smart_terrains]\nesc_ambush=true"
	for i=1,table_monsters[m][2] do
		local obj=alife():create(table_monsters[m][1],sak.v3f(14.8223810195923,15.9107275009155,663.943603515625),292769,206)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
	end
end

function mil_barjer_monsters_add()
	local table_monsters={
				{"chimera_strong",3},
				{"bloodsucker_normal",3},
				{"burer_strong",3}
				}
	local table_spawn={
				{position={x=131.51,y=-8.50,z=433.60},gv=1812,lv=411674}, 
				{position={x=123.61,y=-6.30,z=444.35},gv=1812,lv=409754},
				{position={x=138.86,y=-8.20,z=438.87},gv=1812,lv=413071}
				}
	local r = get_value("r_treas_items",3)
	local rand_monstr = table_monsters[r]
	local p = table_spawn[r]
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\mil\\mil_barjer_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local obj=alife():create(rand_monstr[1],sak.v3f(p.position.x,p.position.y,p.position.z),p.lv,p.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(p.position.x,p.position.y,p.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(p.position.x,p.position.y,p.position.z), 1.0 )
		set_st_conds(obj)
	end
end

function add_gar_hellcar_monsters()
	local table_monsters={
				{"pseudodog_normal",2},
				{"tushkano_normal",7},
				{"dog_normal",5},
				{"boar_normal",3}
				}
	local table_spawn={
				{position={x=-147.9315032959,y=0.50033414363861,z=-258.63153076172},gv=275,lv=69770}, 
				{position={x=-155.05776977539,y=-0.90811288356781,z=-174.21310424805},gv=278,lv=63297}, 
				{position={x=-10.28719997406,y=-1.0010341405869,z=-177.19413757324},gv=287,lv=166462}, 
				{position={x=-1.7937774658203,y=0.48571994900703,z=-236.17179870605},gv=265,lv=173304}
				}
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local rand_point=lua_random(#table_spawn)
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\gar\\gar_hellcar_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

function mutant_blok_post()
	local rand2=lua_random()
	if rand2>0.3 then return end
	add_gar_monsters()
end
function add_gar_monsters()
	local table_monsters={
				{"pseudodog_normal",3},
				{"tushkano_normal",7},
				{"dog_normal",5},
				{"boar_normal",4},
				{"boar_strong",3},
				{"cat_normal",3}
				}
	local table_spawn={
				{position={x=78.63,y=0.5,z=195.3},gv=363,lv=248003}, 
				{position={x=99.96,y=0.8,z=260.27},gv=366,lv=266369}, 
				{position={x=12.91,y=0.5,z=162.57},gv=355,lv=186028}, 
				{position={x=69.41,y=0.9,z=159.32},gv=364,lv=240038}
				}
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local rand_point=lua_random(#table_spawn)
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\gar\\gar_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

function add_val_monsters()
	local rand2=lua_random()
	if rand2>0.3 then return end
	val_monsters_add()
end
function val_monsters_add()
	local table_monsters={
				{"pseudodog_normal",2},
				{"tushkano_normal",6},
				{"dog_normal",4},
				{"boar_normal",3},
				{"chimera_normal",1}
				}
	local table_spawn={
				{position={x=-67.44,y=-2.69,z=-232.15},gv=852,lv=95488},
				{position={x=-135.55,y=0.44,z=-270.84},gv=848,lv=22426},
				{position={x=-152.80,y=6.27,z=-149.12},gv=884,lv=10912}
				}
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\val\\val_add_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local rand_point=lua_random(#table_spawn)
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

function add_val2_monsters()
	local rand2=lua_random()
	if rand2>0.4 then return end
	val2_monsters_add()
end
function val2_monsters_add()
	local table_monsters={
				{"pseudodog_normal",2},
				{"tushkano_normal",8},
				{"dog_normal",5},
				{"boar_normal",3},
				{"chimera_normal",1}
				}
	local table_spawn={
				{position={x=-21.88,y=-0.10,z=-430.76},gv=952,lv=148737},
				{position={x=-52.25,y=0.10,z=-431.32},gv=826,lv=112199},
				{position={x=-82.84,y=0.17,z=-449.32},gv=826,lv=77669},
				{position={x=-61.33,y=0.97,z=-538.55},gv=815,lv=101549}
				}
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\val\\val2_add_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local rand_point=lua_random(#table_spawn)
	for i=1,rand_monstr[2] do
	local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

function gar_monster_angar()
	if lua_random()<0.5 then
		return
	end
	local table_monsters={
				{"flesh_strong",2},
				{"flesh_normal",3},
				{"flesh_weak",4},
				{"pseudodog_normal",3},
				{"tushkano_normal",10},
				{"dog_weak",6},
				{"dog_normal",5},
				{"boar_normal",4},
				{"cat_normal",3}
				}
	local table_spawn={
				{position={x=79.96,y=0.65,z=-42.15},gv=394,lv=249047}
				}
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local rand_point=lua_random(#table_spawn)
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\gar\\gar_monsters_angar.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

function gar_monster_tonel()
	local table_monsters={
				{"dog_normal",4},
				{"tushkano_normal",6}
				}
	local table_spawn = {position={x=-187.7568,y=0.3720,z=16.2489},gv=314,lv=37887}
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\gar\\gar_monsters_tonel.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local a=table_spawn
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

function add_klyk_med1_monsters()
	if get_value("agr_izm1_monsters") == true then return end
	local table_monsters={
				{"pseudodog_normal",3},
				{"tushkano_normal",7},
				{"cat_strong",4}
				}
	local table_spawn={
				{position={x=45.98,y=16.96,z=198.55},gv=694,lv=283809},  
				{position={x=-42.14,y=8.87,z=149.05},gv=518,lv=199055}
				}
	local r = get_value("r_treas_items",3)
	local rand_monstr=table_monsters[r]
	local rand_point=lua_random(#table_spawn)
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\agr\\agr_klyk_med1_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end
function add_klyk_med2_monsters()
	if get_value("agr_izm2_monsters") == true then return end
	local table_monsters={
				{"tushkano_normal",7},
				{"pseudodog_normal",3},
				{"boar_normal",5}
				}
	local a = {-86.88,3.83,2.10,530,150967}
	local r = get_value("r_treas_items",3)
	local rand_monstr=table_monsters[r]
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\agr\\agr_klyk_med2_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local obj=alife():create(rand_monstr[1],sak.v3f(a[1],a[2],a[3]),a[5],a[4])
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a[1],a[2],a[3]) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a[1],a[2],a[3]), 1.0 )
		set_st_conds(obj)
	end
end
function add_klyk_med3_monsters()
	if get_value("agr_izm3_monsters") == true then return end
	local table_monsters={
				{"dog_normal",6},
				{"cat_strong",4},
				{"pseudodog_normal",3}
				}
	local table_spawn={
				{position={x=65.88,y=0.6,z=-64.11},gv=425,lv=303227}, 
				{position={x=-27.93,y=0.1,z=-24.41},gv=457,lv=212533}, 
				{position={x=-43.52,y=1.11,z=-71.49},gv=545,lv=200175}
				}
	local r = get_value("r_treas_items",3)
	local rand_monstr=table_monsters[r]
	local rand_point=lua_random(#table_spawn)
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\agr\\agr_klyk_med3_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

function agr_monster_kirpich()
	local obj=alife():story_object(story_ids.agr_pda_luber)
	level.map_remove_object_spot(obj.id, "crlc_big")
	local table_monsters={
				{"pseudodog_normal",3},
				{"tushkano_normal",8},
				{"boar_normal",4}
				}
	local table_spawn={
				{position={x=-113.96,y=7.35,z=113.61},gv=590,lv=126107}, 
				{position={x=-139.58,y=13.25,z=150.68},gv=523,lv=99895}
				}
	local r = get_value("r_treas_items",3)
	local rand_monstr=table_monsters[r]
	local rand_point=lua_random(#table_spawn)
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\agr\\agr_monster_kirpich.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

function add_x18_monsters()
	local table_monsters={
				{"snork_indoor",3},
				{"tushkano_normal",8},
				{"m_poltergeist_strong_flame",2}
				}
	local table_spawn={
				{position={x=2.24,y=4.19,z=-2.83},gv=1124,lv=3078}
				}
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\dar\\x18_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local rand_point=lua_random(#table_spawn)
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

function add_ros_monsters()
	if lua_random() > 0.33 then
		return
	end
	ros_monsters_add()
end
function ros_monsters_add()
	local table_monsters={
				{"dog_normal",5},
				{"snork_strong",2},
				{"chimera_normal",1}
				}
	local table_spawn={
				{position={x=-96.51,y=0.00,z=148.26},gv=1422,lv=45539},
				{position={x=-113.40,y=0.00,z=128.34},gv=1315,lv=43547},
				{position={x=-163.66,y=0.00,z=128.11},gv=1314,lv=34646},
				{position={x=-152.32,y=0.00,z=158.00},gv=1327,lv=38436}
				}
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\ros\\ros_add_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local rand_point=lua_random(#table_spawn)
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end
function add_ros2_monsters()
	if not has_alife_info("ros_zombied_spawn_01") then
		ros2_monsters_add()
	else
		if lua_random() > 0.33 then
			return
		end
		ros2_monsters_add()
	end
end
function ros2_monsters_add()
	local table_monsters={
				{"dog_normal",5},
				{"snork_strong",2}
				}
	local table_spawn={
				{position={x=-47.42,y=-13.82,z=-201.48},gv=1433,lv=58323},
				{position={x=-96.60,y=-12.60,z=-142.94},gv=1437,lv=45471},
				{position={x=-149.08,y=-12.55,z=-274.51},gv=1435,lv=38993}
				}
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\ros\\ros2_add_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local rand_point=lua_random(#table_spawn)
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end
function add_ros3_monsters()
	if lua_random() > 0.33 then
		return
	end
	ros3_monsters_add()
end
function ros3_monsters_add()
	local table_monsters={
				{"dog_normal",5},
				{"snork_strong",2},
				{"chimera_normal",1}
				}
	local table_spawn={
				{position={x=-56.84,y=0,z=112.51},gv=1419,lv=56508},
				{position={x=-18.12,y=0,z=150.00},gv=1415,lv=64638},
				{position={x=-71.53,y=0,z=151.81},gv=1309,lv=51940}
				}
	local logic="[smart_terrains]\nnone = true\n[logic]\ncfg=scripts\\ros\\ros3_add_monsters.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local rand_point=lua_random(#table_spawn)
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

function agr_monsters_enteres()
	local table_monsters={
				{"pseudodog_normal",3},
				{"tushkano_normal",10},
				{"dog_normal",6},
				{"boar_normal",4}
				}
	local table_spawn={
				{position={x=240.580718994141,y=0.306022644042969,z=-9.32329177856445},gv=416,lv=424118}
				}
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local logic="[smart_terrains]\nnone = true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = solider_ambush_2_walk\nhome_min_radius = 25\nhome_max_radius = 50\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 17000|%=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 30000 | mob_home\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local a=table_spawn[1]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		set_st_conds(obj)
	end
end

local spawn_l01_escape = {
				{-210.6,-22.88,-122.39,42768,59},
				{-210.6,-22.88,-122.39,42768,59}
				}
local spawn_l02_garbage = {}
local spawn_l03_agroprom = {
				{-197.40832519531,-0.001372367143631,-217.87741088867,39202,555},
				{-197.40832519531,-0.001372367143631,-217.87741088867,39202,555},
				{-182.53715515137,1.0960040092468,-304.18606567383,53749,689},
				{-105.64331054688,-0.0010449588298798,-214.49771118164,134209,552},
				{-147.96534729004,-0.20088905096054,-224.84063720703,87306,554},
				{-184.15728759766,0.011988133192062,-185.3687286377,54584,666},
				{-150.07102966309,1.1019934415817,-160.90698242188,85935,669},
				{-133.22476196289,1.6374768018723,-140.18840026855,104045,697},
				{-124.13204193115,-0.00052705407142639,-169.2686920166,116029,564},
				{-150.96371459961,1.1015794277191,-148.06611633301,87391,668},
				{-181.03880310059,-0.0024654865264893,-166.3733215332,55326,560},
				{-189.67437744141,-0.069051057100296,-177.87515258789,46853,558},
				{-198.82919311523,-0.0045629143714905,-199.82818603516,37839,557},
				{-156.32991027832,-0.0021463334560394,-205.35818481445,82695,648},
				{-120.96133422852,14.999356269836,-200.72688293457,118927,642},
				{-138.17070007324,1.0594934225082,-197.22166442871,101724,649},
				{-113.6064453125,13.289253234863,-264.05694580078,126336,631},
				{50.503395080566,14.468194007874,-290.08377075195,286939,450},
				{-14.892495155334,-0.74388289451599,-156.57693481445,225328,437},
				{48.609634399414,2.1393494606018,-152.38336181641,285255,641},
				{80.252487182617,0.26916721463203,-58.579772949219,315716,425},
				{82.56184387207,0.62457859516144,28.336143493652,319820,423},
				{22.503131866455,-0.20140597224236,44.808353424072,261973,475},
				{-43.449123382568,-0.00015690922737122,40.219749450684,197553,672},
				{-27.942699432373,2.7175040245056,106.40400695801,212700,588},
				{50.801006317139,18.042943954468,131.48590087891,288146,580},
				{106.6749420166,8.0823307037354,145.79360961914,340920,504},
				{111.6714630127,12.138738632202,198.83236694336,346285,579},
				{38.866779327393,20.816883087158,209.17419433594,277682,694},
				{38.866779327393,20.816883087158,209.17419433594,277682,694}
				}
local spawn_l03u_agr_underground = {}
local spawn_l04_darkvalley = {}
local spawn_l04u_labx18 = {}
local spawn_l05_bar = {}
local spawn_l06_rostok = {}
local spawn_l07_military={
				{-138.06878662109,-0.94603538513184,-59.39884185791,176330,1622},
				{-108.22340393066,-5.7765727043152,-9.6930503845215,207044,1613},
				{-94.977043151855,-6.2111787796021,59.214408874512,213510,1616},
				{108.56769561768,-6.3105902671814,11.720973014832,405007,1561},
				{-8.2585945129395,-8.707555770874,48.819267272949,298787,1580},
				{-31.105308532715,-9.0780038833618,26.549795150757,276631,1606},
				{-72.398063659668,-7.1178121566772,-37.414375305176,239380,1605},
				{69.604995727539,-1.7951892614365,-57.483680725098,319753,1591},
				{10.633180618286,0.48450103402138,-14.111708641052,317797,1585}
				} 
local spawn_l08_yantar={
				{85.14,0.39204499125481,11.55,84105,1513},
				{96.16,0.15887573361397,26.37,87213,1512},
				{94.83,0.15944364666939,29.20,89336,1512},
				{86.62,1.0477981567383,-9.61,85526,1514},
				{94.52,0.02390930056572,-25.00,89248,1514},
				{61.35,-0.7736474275589,1.94,71786,1509},
				{59.39,-0.375148969888687,29.00,70081,1509},
				{38.52,0.13321402668953,43.02,59812,1510},
				{20.49,0.12415805459023,36.43,59538,1510},
				{35.35,-0.85104143619537,9.91,57954,1445},
				{49.72,7.3883419036865,17.10,64695,1445},
				{30.26,0.071936756372452,-6.35,53971,1507},
				{19.39,0.085919499397278,-5.84,48682,1507},
				{33.18,0.13766834139824,-24.27,56191,1506},
				{37.88,0.27733400464058,-71.78,63787,1517},
				{8.13,0.92447483539581,-11.77,44277,1503},
				{8.65,8.862042427063,4.62,43665,1502},
				{10.55,7.1110558509827,-12.37,45732,1445},
				{-15.83,0.34346553683281,-33.08,34470,1444},
				{-7.68,0.14076626300812,13.80,42729,1502},
				{3.40,1.3564069271088,0.99,41114,1525},
				{-4.49,9.3516025543213,1.49,37376,1525},
				{-0.76,14.985825538635,-16.29,38597,1525},
				{-2.68,5.4348163604736,-16.91,37917,1525},
				{87.45,0.052900612354279,41.43,85597,1520},
				{104.24,0.39546039700508,40.35,94948,1520},
				{157.77,-7.5283575057983,-93.00,128426,1451},
				{16.24,-8.2876586914063,-206.38,48451,1469},
				{-106.28,-1.8489271402359,-204.53,4855,1485}
				} 
local spawn_l08u_brainlab = {}
local spawn_l10_radar = {}
local spawn_limansk = {}
local spawn_lost_village = {}
local spawn_marsh = {}
local spawn_red_forest = {}
local spawn_warlab = {}
local spawn_labx10 = {}
local spawn_labx8 = {}
local spawn_generators = {}
local spawn_aver = {}
local spawn_hospital = {}
local spawn_deadcity = {
				{-146.58863830566,19.050142288208,-41.386787414551,171366,3793},
				{-149.80274963379,6.2662415504456,-1.861160993576,168833,3804},
				{6.8520812988281,1.2480462789536,-32.950668334961,301873,3888},
				{-181.51889038086,19.055055618286,-7.5016026496887,150990,3793}
				}
local spawn_av_peshera = {}
local spawn_l10u_bunker = {}
local spawn_l11_pripyat = {}
local spawn_l12_stancia_new = {}
local spawn_l12_stancia_2_new = {}
local spawn_l12u_control_monolith = {}
local spawn_l12u_sarcofag = {}

local leveles={
	["l01_escape"]=spawn_l01_escape,
	["l02_garbage"]=spawn_l02_garbage,
	["l03_agroprom"]=spawn_l03_agroprom,
	["l03u_agr_underground"]=spawn_l03u_agr_underground,
	["l04_darkvalley"]=spawn_l04_darkvalley,
	["l04u_labx18"]=spawn_l04u_labx18,
	["l05_bar"]=spawn_l05_bar,
	["l06_rostok"]=spawn_l06_rostok,
	["l07_military"]=spawn_l07_military,
	["l08_yantar"]=spawn_l08_yantar,
	["l08u_brainlab"]=spawn_l08u_brainlab,
	["l10_radar"]=spawn_l10_radar,
	["limansk"]=spawn_limansk,
	["lost_village"]=spawn_lost_village,
	["marsh"]=spawn_marsh,
	["red_forest"]=spawn_red_forest,
	["warlab"]=spawn_warlab,
	["labx10"]=spawn_labx10,
	["labx8"]=spawn_labx8,
	["generators"]=spawn_generators,
	["aver"]=spawn_aver,
	["hospital"]=spawn_hospital,
	["deadcity"]=spawn_deadcity,
	["av_peshera"]=spawn_av_peshera,
	["l10u_bunker"]=spawn_l10u_bunker,
	["l11_pripyat"]=spawn_l11_pripyat,
	["l12_stancia_new"]=spawn_l12_stancia_new,
	["l12_stancia_2_new"]=spawn_l12_stancia_2_new,
	["l12u_control_monolith"]=spawn_l12u_control_monolith,
	["l12u_sarcofag"]=spawn_l12u_sarcofag
	}
function spawn_items_on_escape()
	spawn_items_on_levels("l01_escape")
end
local max_kol_point =1
local game_difficulty=tonumber(level.get_game_difficulty())
local spawn_ini = ini_file("misc\\spawn_items_by_levels.ltx")
function spawn_items_on_levels(urov)
	local level_name = urov
	local kol_by_level={}
	if not spawn_ini:section_exist(level_name) then
		level_name = "default"
	end
	local n = spawn_ini:line_count(level_name)
	local id, value = "", ""
	for i=0,n-1 do
		result, id, value	= spawn_ini:r_line(level_name,i,"","")
		local m=tonumber(value)
		if m~=0 then
		kol_by_level[id] = m
		end
	end
	local tbl=leveles[level_name]
	max_kol_point = math.ceil(#tbl/(game_difficulty*2+4))
	local kol_point=lua_random(1,max_kol_point)
	for a=1, kol_point do
		local point=lua_random(1,#tbl)
		for k,v in pairs(kol_by_level) do
			if lua_random()<0.2 then
				local number = math.ceil(lua_random(1, v))
				for i=1,number do
					alife():create(k,sak.v3f(tbl[point][1]+0.05*i,tbl[point][2]+0.05*i,tbl[point][3]+0.05*i),tbl[point][4],tbl[point][5])
				end
			end
		end
	end
end
--спавн снорков, замеры у болота
function add_yan_izm1_monsters()
	if get_value("yan_izm1_monsters") == true then return end
	local table_spawn = {
				{-71.469215,-11.499264,-212.189102,13861,1447},
				{-103.1200880,-6.372991,-210.809509,5813,1485},
				{-89.266365,-12.460389,-243.925964,8494,1486}
				}
	for i=1,#table_spawn do
		local point = table_spawn[i]
		local obj = alife():create("snork_strong",sak.v3f(point[1],point[2],point[3]),point[4],point[5])
		teleport_particle:play_at_pos( sak.v3f(point[1],point[2],point[3]) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(point[1],point[2],point[3]), 1.0 )
	end
end
--спавн бюреров, замеры у автобуса
function add_yan_izm2_monsters()
	if get_value("yan_izm2_monsters") == true then return end
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home=yan_zombie_home_3\nhome_min_radius = 10\nhome_max_radius = 25\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 12000|%=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 30000 | mob_home"
	for i=1,2 do
		local obj=alife():create("burer_strong",sak.v3f(156.84,-7.42,-119.39),127776,1465)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(156.84,-7.42,-119.39) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(156.84,-7.42,-119.39), 1.0 )
		set_st_conds(obj)
	end
end
--доспавн кровососов в РЛ
-- [HE-PORT]
function red_smart_bloodsucker01()
	red_smart_bloodsucker()
end
function red_smart_bloodsucker()
    alife():create("red_bloodsucker1",sak.v3f(-32.25,2.45000004768372,-163.020004272461),40732,3268)
    alife():create("red_bloodsucker2",sak.v3f(-32.25,2.45000004768372,-163.020004272461),40732,3268)
end
--сканер в Лиманске
function add_lim_burers()
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home=lim_burers1\nhome_min_radius = 10\nhome_max_radius = 25\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 12000|%=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 30000 | mob_home"
	for i=1,2 do
		local obj=alife():create("burer_strong",sak.v3f(0.54,13.55,181.64),25108,3010) 
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		set_st_conds(obj)
	end
end
-- кровососы в подземке
function agr_und_blood()
	local table_spawn={
				{-98.14,-16.46,-77.91,1804,753},
				{-118.68,-3.99,-142.80,96,703},
				{-112.87,-16.51,-51.10,383,757},
				{-85.12,-16.45,-101.90,2457,784},
				{-129.05,-3.95,-139.81,9,719}
				}
	local timer=17131
	for i=1,#table_spawn do
		local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = agr_und_monsters"..i.."\nhome_min_radius = 10\nhome_max_radius = 25\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = "..timer.." | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = "..tostring(timer+1234).." | mob_home"
		timer=timer+1100
		local zomb="bloodsucker_normal"
		local point=table_spawn[i]
		local obj=alife():create(zomb,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)	
		set_st_conds(obj)
	end
end

function lim_monstr_enter()
	local table_monsters={
				{"tushkano_strong",8},
				{"dog_strong",6},
				{"cat_strong",4}
				}
	local table_spawn={
				{position={x=-19.60,y=1.12,z=-296.04},gv=3008,lv=15284}
				}
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local rand_point=lua_random(#table_spawn)
	local logic="[smart_terrains]\nnone=true\n[logic]\ncfg=scripts\\lim\\lim_monstrs_enter.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		set_st_conds(obj)
	end
end
--гигант на болотах
function add_marsh_gigant()
    local obj = alife():create("marsh_gigant",sak.v3f(-146.080001831055,0.75,87.2300033569336),72632,3379)
	if obj then
		set_value("marsh_gigant_id", obj.id)
	end
	marsh_monster_botans()
	sak.add_mar_gigant_spot()
end
-- крысы подземка
function agr_und_rats()
	local table_monsters={
				"rat_mad_weak",
				"rat_mad_normal",
				"rat_mad_strong",
				"rat_mad_wery_strong"
				}
	local table_spawn={
				{-70.3403625488281,-4.01451301574707,-134.107162475586,3422,800},
				{-86.6028289794922,-16.4646854400635,-43.1212501525879,2396,748},
				{-97.3905944824219,-16.4646854400635,-79.0139846801758,1865,754},
				{-70.4415512084961,-3.94728374481201,-132.262329101563,3367,705},
				{-129.051498413086,-3.95755624771118,-139.810028076172,9,719}
				}
	local timer=17131
	for ii=1,6 do
		for i=1,#table_spawn do
		local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = agr_und_monsters"..i.."\nhome_min_radius = 20\nhome_max_radius = 40\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = "..timer.." | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = "..tostring(timer+1234).." | mob_home"
			timer=timer+1100
			local zomb=table_monsters[lua_random(#table_monsters)]
			local point=table_spawn[i]
			local obj=alife():create(zomb,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
			local pk = get_netpk(obj)
			local data = pk:get()
			data.custom_data = logic
			pk:set(data)	
			set_st_conds(obj)
		end
	end
end
-- крысы x16
function spawn_brain_rats()
	local table_monsters={
				"rat_mad_weak",
				"rat_mad_normal",
				"rat_mad_strong",
				"rat_mad_wery_strong"
				}
	local table_spawn={
				{-8.64,1.11,-14.40,4041,1536},
				{-24.55,3.46,-6.84,3668,1532},
				{-127.13,21.56,-30.87,44,1529},
				{-90.71,21.57,-31.38,730,1529},
				{-53.78,19.18,2.36,1960,1530},
				{-43.03,19.18,5.40,2572,1530}
				}
	local timer=17131
	for ii=1,6 do
		for i=1,#table_spawn do
		local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = brain_rats"..i.."\nhome_min_radius = 20\nhome_max_radius = 40\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = "..timer.." | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = "..tostring(timer+1234).." | mob_home"
			timer=timer+1100
			local zomb=table_monsters[lua_random(#table_monsters)]
			local point=table_spawn[i]
			local obj=alife():create(zomb,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
			local pk = get_netpk(obj)
			local data = pk:get()
			data.custom_data = logic
			pk:set(data)	
			set_st_conds(obj)
		end
	end
end
-- brain_zombie x16
function spawn_brain_zombie()
	local table_monsters={
				"zombie_normal",
				"zombie_scientist_1",
				"zombie_scientist_2"
				}
	local table_spawn={
				{84.9947967529297,5.57230091094971,-14.1789569854736,6107,1539},
				{-43.864372253418,-4.23189926147461,-2.17875003814697,2417,1533},
				}
	local timer=17131
	local point = table_spawn[1]
	for i=1,#table_monsters do
		local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = x16_zombie_home_1\nhome_min_radius = 20\nhome_max_radius = 40\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = "..timer.." | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = "..tostring(timer+1234).." | mob_home"
		timer=timer+1100
		local zomb=table_monsters[i]
		local obj=alife():create(zomb,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)	
		set_st_conds(obj)
	end
	timer=17131
	point = table_spawn[2]
	for i=1,#table_monsters do
		local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = x16_zombie_home_5\nhome_min_radius = 20\nhome_max_radius = 40\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = "..timer.." | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = "..tostring(timer+1234).." | mob_home"
		timer=timer+1100
		local zomb=table_monsters[i]
		local obj=alife():create(zomb,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)	
		set_st_conds(obj)
	end
	
	local z1 = g_sim:create("zombie_scientist_1", sak.v3f(122.6484,30.2000,-12.4259), 7187, 1543)
	local z2 = g_sim:create("zombie_scientist_2", sak.v3f(134.2582,30.7063,-19.2894), 7329, 1542)
	for i=1,2 do
		local zomb = (isEven(i) and z1) or z2
		local pk = get_netpk(zomb)
		local data = pk:get()
		data.custom_data = "[smart_terrains]\nnone=true\n[logic]\ncfg=scripts\\labx16\\x16_zombies.ltx"
		data.base_out_restrictors = "x16_space_restrictor"
		pk:set(data)	
		set_st_conds(zomb)
	end
end

function add_matveev_monsters()
	local table_spawn={
				{-86.0258483886719,-19.0469608306885,-77.468109130859,9663,1496},
				{-55.2264671325684,-18.5290679931641,-53.156421661377,20021,1494},
				{-48.1676559448242,-19.087194442749,-97.1903305053711,22576,1456}
				}
	local timer=17131
	for ii=1,2 do
		for i=1,#table_spawn do
		local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = yan_tonnel_snorks_home_"..i.."\nhome_min_radius = 35\nhome_max_radius = 110\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = "..timer.." | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = "..tostring(timer+1234).." | mob_home"
			timer=timer+1100
			local zomb="snork_strong"
			local point=table_spawn[i]
			local obj=alife():create(zomb,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
			local pk = get_netpk(obj)
			local data = pk:get()
			data.custom_data = logic
			pk:set(data)	
			set_st_conds(obj)
		end
	end
end
-- смотреть в sak.script
function rad_zombied_pribor3()
	local table_monsters={
				"rad_zombied_respawn_1",
				"rad_zombied_respawn_2",
				"rad_zombied_respawn_3",
				"yan_zombied_respawn_1",
				"yan_zombied_respawn_2",
				"yan_zombied_respawn_3",
				"yan_zombied_respawn_4",
				"yan_zombied_respawn_5",
				"yan_zombied_respawn_6"
				}
	local table_spawn={
				{620.09484863281,-52.355792999268,-308.76190185547,222616,2113},
				{612.83728027344,-51.82381439209,-315.77239990234,220044,1881},
				{601.27368164063,-52.257698059082,-314.01718139648,215096,1881},
				{611.359375,-52.268257141113,-307.48843383789,219497,1881},
				{609.60083007813,-51.931880950928,-319.99203491211,218928,1881},
				{601.56201171875,-52.139381408691,-318.59118652344,215095,1881}
				}
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = walker1\n[walker1]\npath_walk = rad_zombi_exit_mil_walk\nsound_idle = state\non_timer = 29855| %=bar_arena_hit% walker2\n[walker2]\npath_walk = rad_zombi_exit_mil_walk\nsound_idle = state\non_timer = 29855| %=bar_arena_hit% walker1"
	for i=1,#table_spawn do
		local zomb=table_monsters[lua_random(#table_monsters)]
		local point=table_spawn[i]
		local obj=alife():create(zomb,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)	
		teleport_particle:play_at_pos( sak.v3f(point[1],point[2],point[3]) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(point[1],point[2],point[3]), 1.0 )
		set_st_conds(obj)
	end
end

function monsters_dar_crash_vertolet()
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home=dv_sak_1monstr\nhome_min_radius = 10\nhome_max_radius = 25\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 12000|%=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 30000 | mob_home"
	
	for i=1,3 do
		local obj=alife():create("chimera_strong",sak.v3f(176.83,8.37,-375.96),377568,938)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		set_st_conds(obj)
	end
end

function monsters_marsh_crash_vertolet()
	local logic="[smart_terrains]\nnone = true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = marsh_heli_monster\nhome_min_radius = 10\nhome_max_radius = 25\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 12000|%=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 30000 | mob_home"
		
	local obj=alife():create("m_controller_old",sak.v3f(-295.84,1.89,-113.37),2611,3343)
	local pk = get_netpk(obj)
	local data = pk:get()
	data.custom_data = logic
	pk:set(data)
	set_st_conds(obj)
end										

function bar_korovan_monsters()
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home=agr_korovan_chimers\nhome_min_radius = 10\nhome_max_radius = 25\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 12000|%=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 30000 | mob_home"
	for i=1,3 do
		local obj=alife():create("chimera_normal",sak.v3f(-170.30,3.94,-327.10),66612,658)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		set_st_conds(obj)
	end
end

function dsc_kolonna_spawn()
	alife():create("dsc_kolonna_burer1", vector():set(390.193359375,-2.15111756,336.83996582),882248,4133)
	alife():create("dsc_kolonna_burer2", vector():set(388.20590209,-2.16341972,355.02978515),879714,4133)
	alife():create("dsc_zombied_01", vector():set(-351.56964111,5.12980117,486.93011474),75955,3952)
	alife():create("dsc_zombied_02", vector():set(-340.40133666,5.00130796,494.72250366),81150,3952)
	alife():create("dsc_zombied_03", vector():set(-338.61941528,4.73968315,501.47418212),81760,3952)
	alife():create("dsc_kolonna_controller", vector():set(-340.47384643,5.04730987,491.68988037),81145,3952)	
	doc.dsc_quest_case()				  
end

-- х16 zombies
function brainlab_zombied_zasada()
	level.add_pp_effector("teleport.ppe", 1000, false)
	local table_zombied={
				"yan_zombied_respawn_3",
				"yan_zombied_respawn_4",
				"yan_zombied_respawn_5"
				}
	local table_spawn={
				{39.1378631591797,5.54797649383545,9.15358066558838,5024,1537},
				{41.2180442810059,5.57018232345581,8.4710807800293,5122,1538},
				{35.6750679016113,5.66753387451172,-9.28861713409424,4858,1538}
				}
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = walker\n[walker]\npath_walk = yan_zombied_walk_zasada_1\nsound_idle = state\non_timer = 3000| %=bar_arena_hit%"
	for i=1,#table_spawn do
		local zomb=table_zombied[lua_random(#table_zombied)]
		local point=table_spawn[i]
		local obj=alife():create(zomb,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)	
		set_st_conds(obj)
	end
end
function val_dram_bandit_monsters()
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home=val_dram_bandit_glavn_look\nhome_min_radius = 10\nhome_max_radius = 25\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 12000|%=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 30000 | mob_home"
	for i=1,6 do
		local obj=alife():create("snork_strong",sak.v3f(133.47,0.23,-259.63),330942,960)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		set_st_conds(obj)
	end
end

function mil_blood_spawn()
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home=mil_hunters_bloodsucker_home_1\nhome_min_radius = 10\nhome_max_radius = 25\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 12000|%=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 30000 | mob_home"
	
	for i=1,3 do
		local obj=alife():create("bloodsucker_normal",sak.v3f(-246.29,-22.39,295.42),87662,1797)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		set_st_conds(obj)
	end
end

function dsc_kolonna_burer_strong_spawn()
	alife():create("dsc_kolonna_burer_strong",vector():set(390.193359375,-2.15111756,336.83996582),882248,4133)
	se_respawn.spawn_amk("ros_hl")
end

function x18_zasada()
	local tbl = {
	"burer_strong",
	"snork_strong",
	"snork_strong"
	}

	local coords = {-13.74,-10.82,-4.31,1249,1150}
	for i=1,#tbl do
		local obj = g_sim:create(tbl[i],sak.v3f(coords[1],coords[2],coords[3]),coords[4],coords[5])
		if obj then
			local pk = get_netpk(obj)
			local data = pk:get()
			data.custom_data = "[smart_terrains]\nnone = true\n[spawner]\nday_night_switch=false\ncheck_distance=false\n"
			pk:set(data)	
			set_st_conds(obj)
		end
	end
end

function zapravka_zasada_boars()
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home=dsc_zapravka_zasada_look\nhome_min_radius = 10\nhome_max_radius = 30\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 12000|%=bar_arena_hit%\nmob_combat\n[mob_combat]\non_timer = 30000 | mob_home"
	local pos = sak.v3f(421.2138,-1.2954,-418.0041)
	
	for i=1,5 do
		local obj = alife():create("boar_strong",pos,939759,4147)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		set_st_conds(obj)
	end
	
	sak.play_spawn_eff(pos)
end

function st2_contr_spawn()
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home=st2_contr\nhome_min_radius = 15\nhome_max_radius = 70\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 10000|%=bar_arena_hit%\n[mob_combat]\non_timer = 30000 | mob_home"
	local pos = sak.v3f(944.4973,1.1941,70.9620)
	local obj = alife():create("m_controller_old",pos,548338,4519)
	local pk = get_netpk(obj)
	local data = pk:get()
	data.custom_data = logic
	pk:set(data)
	set_st_conds(obj)
	sak.play_spawn_eff(pos)
end

function st2_bs_spawn()
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home=st2_bs\nhome_min_radius = 15\nhome_max_radius = 70\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 10000|%=bar_arena_hit%\n[mob_combat]\non_timer = 30000 | mob_home"
	local pos = sak.v3f(584.8667,-0.0001,428.0557)
	local obj = alife():create("bloodsucker_strong",pos,343561,4433)
	local pk = get_netpk(obj)
	local data = pk:get()
	data.custom_data = logic
	pk:set(data)
	set_st_conds(obj)
	sak.play_spawn_eff(pos)
end

function st2_burer_spawn()
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home=st2_burer\nhome_min_radius = 15\nhome_max_radius = 70\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 10000|%=bar_arena_hit%\n[mob_combat]\non_timer = 30000 | mob_home"
	local pos = sak.v3f(291.1791,-0.0010,127.4323)
	local obj = alife():create("burer_strong",pos,162719,4377)
	local pk = get_netpk(obj)
	local data = pk:get()
	data.custom_data = logic
	pk:set(data)
	set_st_conds(obj)
	sak.play_spawn_eff(pos)
end

function bun_ambush_spawn()
	local pos = sak.v3f(-1.06372666358948,-8.98938369750977,7.89116859436035)
	local logic = "[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = bun_ambush_bs\nhome_min_radius = 10\nhome_max_radius = 40\naggressive_home\non_signal = sig_attacked | mob_combat\n[mob_combat]\non_timer = 30000 | mob_home"
	local obj = alife():create("bloodsucker_strong",pos,5564,2782)
	local pk = get_netpk(obj)
	local data = pk:get()
	data.custom_data = logic
	pk:set(data)
	set_st_conds(obj)
	
	pos = sak.v3f(-21.4150867462158,-8.99173736572266,16.6553764343262)
	logic = "[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = bun_poltergeists2\nhome_min_radius = 10\nhome_max_radius = 40\naggressive_home\non_signal = sig_attacked | mob_combat\n[mob_combat]\non_timer = 30000 | mob_home"
	obj = alife():create("m_controller_old_fat",pos,3175,2673)
	pk = get_netpk(obj)
	data = pk:get()
	data.custom_data = logic
	pk:set(data)
	set_st_conds(obj)
end

function agr_black_box_pseudodog()
	local obj
	local logic="[smart_terrains]\nnone = true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = agr_pseudodog_nest1_home_1\nhome_min_radius = 25\nhome_max_radius = 50\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 17000|%=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 30000 | mob_home\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	local pos = sak.v3f(97.1121139526367,10.2448768615723,189.096099853516)
	for i=1,3 do 
		obj = g_sim:create("pseudodog_weak",pos,332187,579)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		set_st_conds(obj)
	end
end

function dead_monolith_ambush_spawn()
	local sec, obj, pos
	local points = { {-333.9004,-24.5817,196.3016,297864,2891}, {-355.3854,-22.5740,184.0247,257585,2891}, {-358.5982,-19.9716,164.4703,255102,2891},
		{-339.1113,-23.2176,155.5743,286928,2891}, {-325.6859,-24.1284,172.6698,313860,2891} }
	for i=1,5 do
		if isEven(i) then
			sec = "pri_monolith_respawn_3"
		else
			sec = "pri_monolith_respawn_2"
		end
		pos = sak.v3f(points[i][1],points[i][2],points[i][3])
		local logic="[smart_terrains]\nnone = true\n[logic]\nactive = walker\n[walker]\npath_walk = dead_monolith_ambush"..i.."_walk\npath_look = dead_monolith_ambush_look\nmeet = no_meet"
		obj = g_sim:create(sec,pos,points[i][4],points[i][5])
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		set_st_conds(obj)
	end
end

function dolg_dummy_reward_bs()
	local pos = sak.v3f(30.9899,0,192.49)
	local logic = "[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = bar_dogs\nhome_min_radius = 10\nhome_max_radius = 30\naggressive_home\non_signal = sig_attacked | mob_combat\n[mob_combat]\non_timer = 30000 | mob_home"
	local obj = alife():create("bloodsucker_strong",pos,20071,1242)
	local pk = get_netpk(obj)
	local data = pk:get()
	data.custom_data = logic
	pk:set(data)
	set_st_conds(obj)
end

function fox_dogs_berserk()
	local t = get_value("fox_dogs_tbl",{})
	if t then
		for _,v in ipairs(t) do
			local cobj = client_obj(v)
			if cobj then
				cobj:berserk(true)
			end
		end
	end
end

function fox_dogs_spawn()
	local pos, lv, gv = sak.v3f(139.2623,0.2501,346.4197), 444253, 233
	local t = {}
	for i=1,5 do
		local obj
		if isEven(i) then
			obj = g_sim:create("pseudodog_weak_fox",pos,lv,gv)
		else
			obj = g_sim:create("dog_strong_fox",pos,lv,gv)
		end
		table.insert(t,obj.id)
	end
	set_value("fox_dogs_tbl",t)
end

-- [HE-PORT]
function gar_monster_bandits()
	local table_monsters={
				{"pseudodog_normal",2},
				{"tushkano_normal",7},
				{"dog_normal",4},
				{"boar_normal",2}
				}
	local table_spawn={
				{position={x=-179.36552429199,y=-4.0037069320679,z=-189.76043701172},gv=277,lv=43987},
				{position={x=-165.52903747559,y=-1.7383469343185,z=-145.98922729492},gv=278,lv=55066},
				{position={x=-247.58894348145,y=-4.4398550987244,z=-147.1573944091},gv=282,lv=9540}
				}
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local rand_point=lua_random(#table_spawn)
	local logic="[logic]\ncfg=scripts\\gar\\gar_monster_bandits.ltx\n[spawner]\nday_night_switch=false\ncheck_distance=false"
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

-- [HE-PORT]
function gar_monster_exit_agr()
	local table_monsters={
				{"pseudodog_normal",4},
				{"tushkano_normal",12},
				{"dog_normal",8},
				{"boar_normal",5}
				}
	local table_spawn={
				{position={x=-201.51083374023,y=0.79267346858978,z=32.624950408936},gv=268,lv=135713},
				{position={x=-212.97085571289,y=0.63914048671722,z=-16.244190216064},gv=308,lv=22403},
				{position={x=-179.76779174805,y=0.72647774219513,z=-54.675834655762},gv=308,lv=22402},
				{position={x=-119.74779510498,y=0.36166182160378,z=-46.291305541992},gv=301,lv=96098},
				{position={x=-88.224182128906,y=0.25210896134377,z=47.203319549561},gv=298,lv=106985}
				}
	local rand_point=lua_random(#table_spawn)
	local rand_monstr=table_monsters[lua_random(#table_monsters)]
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = garb_monster_exit_agr\nhome_min_radius = 15\nhome_max_radius = 80\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 17131 | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 16321 | mob_home"
	for i=1,rand_monstr[2] do
		local a=table_spawn[rand_point]
		local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(a.position.x,a.position.y,a.position.z) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(a.position.x,a.position.y,a.position.z), 1.0 )
		set_st_conds(obj)
	end
end

-- [HE-PORT]
function marsh_monster_oksana()
	local table_monsters={
				{"pseudodog_normal",3},
				{"tushkano_normal",10},
				{"dog_normal",7},
				{"boar_normal",5}
				}
	local table_spawn={
				{position={x=96.524658203125,y=1.7513536214828,z=266.92807006836},gv=3467,lv=192686},
				{position={x=225.9900970459,y=0.94395875930786,z=267.80520629883},gv=3499,lv=277218},
				{position={x=403.26336669922,y=1.6984423398972,z=129.51379394531},gv=3538,lv=405335},
				{position={x=388.15573120117,y=1.6630955934525,z=-73.797317504883},gv=3550,lv=394042}
				}
	for rand_point=1,#table_spawn do
		local rand_monstr=table_monsters[lua_random(#table_monsters)]
		local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = marsh_monster_oksana"..rand_point.."\nhome_min_radius = 20\nhome_max_radius = 50\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = 17131 | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 16321 | mob_home"
		for i=1,rand_monstr[2] do
			local a=table_spawn[rand_point]
			local obj=alife():create(rand_monstr[1],sak.v3f(a.position.x,a.position.y,a.position.z),a.lv,a.gv)
			local pk = get_netpk(obj)
			local data = pk:get()
			data.custom_data = logic
			pk:set(data)
			set_st_conds(obj)
		end
	end
end

-- [HE-PORT]
function rad_zombi_exit_mil()
	if has_alife_info("deactivate_radar_fall") then return end
	local table_monsters={
				"rad_zombied_respawn_1","rad_zombied_respawn_2","rad_zombied_respawn_3",
				"yan_zombied_respawn_1","yan_zombied_respawn_2","yan_zombied_respawn_3",
				"yan_zombied_respawn_4","yan_zombied_respawn_5","yan_zombied_respawn_6"
				}
	local table_spawn={
				{620.09484863281,-52.355792999268,-308.76190185547,222616,2113},
				{612.83728027344,-51.82381439209,-315.77239990234,220044,1881},
				{601.27368164063,-52.257698059082,-314.01718139648,215096,1881},
				{611.359375,-52.268257141113,-307.48843383789,219497,1881},
				{609.60083007813,-51.931880950928,-319.99203491211,218928,1881},
				{601.56201171875,-52.139381408691,-318.59118652344,215095,1881}
				}
	local logic="[smart_terrains]\nnone=true\n[logic]\nactive = walker1\n[walker1]\npath_walk = rad_zombi_exit_mil_walk\nsound_idle = state\non_timer = 29855| %=bar_arena_hit% walker2\n[walker2]\npath_walk = rad_zombi_exit_mil_walk\nsound_idle = state\non_timer = 29855| %=bar_arena_hit% walker1"
	for i=1,#table_spawn do
		local zomb=table_monsters[lua_random(#table_monsters)]
		local point=table_spawn[i]
		local obj=alife():create(zomb,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
		local pk = get_netpk(obj)
		local data = pk:get()
		data.custom_data = logic
		pk:set(data)
		teleport_particle:play_at_pos( sak.v3f(point[1],point[2],point[3]) )
		teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(point[1],point[2],point[3]), 1.0 )
		set_st_conds(obj)
	end
end

-- [HE-PORT]
function red_near_tank_monsters()
	local table_monsters={
				"snork_strong","snork_strong","snork_strong","dog_strong","dog_strong",
				"snork_normal","dog_strong","bloodsucker_normal","snork_normal"
				}
	local table_spawn={
				{234.75897216797,2.7300519943237,100.12407684326,83351,3263},
				{266.54183959961,2.8341615200043,57.633422851563,83351,3263},
				{178.13026428223,0.56457483768463,78.958869934082,119069,3319},
				{158.86454772949,1.2803754806519,80.693420410156,110716,3319},
				{173.3005065918,0.49827662110329,50.643337249756,110704,3319},
				{203.51692199707,-0.24843227863312,32.118606567383,112386,3319},
				{223.31674194336,1.9060944318771,23.043556213379,140959,3318},
				{236.50140380859,1.0859681367874,35.301368713379,147173,3318},
				{205.69625854492,-3.7869124412537,11.009967803955,132914,3318},
				{210.61515808105,-3.3101496696472,8.258752822876,135272,3318}
				}
	local timer=17131
	for i=1,#table_spawn do
		if lua_random()<0.7 then
			timer=timer+1100
			local logic="[smart_terrains]\nnone=true\n[logic]\nactive = mob_home\n[mob_home]\npath_home = red_near_tank_home_1\nhome_min_radius = 35\nhome_max_radius = 110\naggressive_home\non_signal = sig_attacked | mob_combat\non_timer = "..timer.." | %=bar_arena_hit%  mob_combat\n[mob_combat]\non_timer = 16321 | mob_home"
			local zomb=table_monsters[lua_random(#table_monsters)]
			local point=table_spawn[i]
			local obj=alife():create(zomb,sak.v3f(point[1],point[2],point[3]),point[4],point[5])
			local pk = get_netpk(obj)
			local data = pk:get()
			data.custom_data = logic
			pk:set(data)
			teleport_particle:play_at_pos( sak.v3f(point[1],point[2],point[3]) )
			teleport_snd:play_no_feedback( db.actor, sound_object.s3d, 0, sak.v3f(point[1],point[2],point[3]), 1.0 )
			set_st_conds(obj)
		end
	end
end

-- [HE-PORT]
function add_dsc_1_monsters()
	if lua_random()>0.4 then return end
	dsc_1_monsters_add()
end
