function proceed()
	local actor = db.actor

	if has_alife_info("tm_courier_1_completed") and has_alife_info("tm_courier_2_completed") and has_alife_info("tm_courier_3_completed") and has_alife_info("tm_courier_5_completed") and not has_alife_info("tm_courier_bonus") then
		actor:give_info_portion("tm_courier_bonus")		
	end	
	if has_alife_info("barmen_courier_1_completed") and has_alife_info("barmen_courier_2_completed") and has_alife_info("barmen_courier_3_completed") and has_alife_info("barmen_courier_4_completed") and not has_alife_info("barmen_courier_bonus") then
		actor:give_info_portion("barmen_courier_bonus")		
	end
	if has_alife_info("lim_trader_courier_1_completed") and has_alife_info("lim_trader_courier_2_completed") and has_alife_info("lim_trader_courier_3_completed") and has_alife_info("lim_trader_courier_5_completed") and not has_alife_info("lim_trader_courier_bonus") then
		actor:give_info_portion("lim_trader_courier_bonus")		
	end	
	
	if has_alife_info("mil_bloodsucker1_dead") and has_alife_info("mil_bloodsucker2_dead") and has_alife_info("mil_bloodsucker3_dead") and has_alife_info("mil_bloodsucker4_dead") and has_alife_info("mil_miser_task") and not has_alife_info("mil_bloodsucker_dead") then
		sak.send_tip_local(game.translate_string("mil_bloodsucker_dead"),game.translate_string("thinking_out_loud"),5,15,"g_g","sak","yellow")
		actor:give_info_portion("mil_bloodsucker_dead")		
	end	
	if has_alife_info("val_bloodsucker1_dead") and has_alife_info("val_bloodsucker2_dead") and has_alife_info("val_bloodsucker3_dead") and not has_alife_info("val_bloodsucker_dead") then
		actor:give_info_portion("val_bloodsucker_dead")
	end
	if has_alife_info("dsc_chimera1_dead") and has_alife_info("dsc_chimera2_dead") and has_alife_info("dsc_chimera3_dead") and not has_alife_info("dsc_chimera_dead") then
		actor:give_info_portion("dsc_chimera_dead")
	end
	if has_alife_info("marsh_controller1_dead") and has_alife_info("marsh_controller2_dead") and not has_alife_info("marsh_controller_dead") then
		actor:give_info_portion("marsh_controller_dead")
		-- [HE-PORT]
		doc.marsh_controller_spawn_add()
	end
	if has_alife_info("agr_gigant1_dead") and has_alife_info("agr_gigant2_dead") and not has_alife_info("agr_gigant_dead") then
		actor:give_info_portion("agr_gigant_dead")
	end
	if has_alife_info("sidor_artmod_31_reward_info") and has_alife_info("pahom_artmod_31_reward_info") and has_alife_info("ignat_artmod_31_reward_info") and not has_alife_info("gar_prapor_courier_poshta_done") then
		actor:give_info_portion("gar_prapor_courier_poshta_done")
	end
	if has_alife_info("labx8_pribor3_on") and has_alife_info("labx8_pribor4_on") and not has_alife_info("dead_prizrak_barmen_info") then
		actor:give_info_portion("dead_prizrak_barmen_info")
		sak.dead_prizrak_info() --sms		
	end	   
	if has_alife_info("sema_one_info") and has_alife_info("sema_two_info") and has_alife_info("sema_three_info") and not has_alife_info("semena_done_info") then
		actor:give_info_portion("semena_done_info")
	end
	if has_alife_info("semena_done_info") and has_alife_info("prizrak_said_everything") and not has_alife_info("lebedev_wait") then
		actor:give_info_portion("lebedev_wait")
		mike.timer_lebedev()
	end
	-- [HE-PORT]
	if has_alife_info("escape_lager_volk_info1") and has_alife_info("escape_lager_volk_info2") and has_alife_info("escape_lager_volk_info3") and has_alife_info("escape_lager_volk_info4") and not has_alife_info("escape_lager_volk_info_zone") then
		actor:give_info_portion("escape_lager_volk_info_zone")
	end
	-- [HE-PORT]
	if has_alife_info("escape_lager_volk_info_strelok") and has_alife_info("escape_lager_volk_info_cars") and has_alife_info("escape_lager_volk_info_zone") and not has_alife_info("escape_lager_volk_info_done") then
		actor:give_info_portion("escape_lager_volk_info_done")
		actor:disable_info_portion("escape_lager_volk_info_zone")
		actor:disable_info_portion("escape_lager_volk_info_strelok")
		actor:disable_info_portion("escape_lager_volk_info_cars")
		actor:disable_info_portion("escape_lager_volk_info1")
		actor:disable_info_portion("escape_lager_volk_info2")
		actor:disable_info_portion("escape_lager_volk_info3")
		actor:disable_info_portion("escape_lager_volk_info4")
	end
	if has_alife_info("agr_klyk_1faze") and has_alife_info("agr_klyk_2faze") and has_alife_info("agr_klyk_3faze") and not has_alife_info("agr_klyk_faze_done") then
		actor:give_info_portion("agr_klyk_faze_done")
		actor:disable_info_portion("agr_klyk_1faze")
		actor:disable_info_portion("agr_klyk_2faze")
		actor:disable_info_portion("agr_klyk_3faze")
	end
	if (has_alife_info("borov_11_done") or has_alife_info("borov_11_failed")) and not has_alife_info("borov_11_fdone") then
		actor:give_info_portion("borov_11_fdone")
	end
	if has_alife_info("sakharov_val_container_done_info") and not has_alife_info("borov_11_failed") then
		actor:give_info_portion("borov_11_failed")
	end
	if has_alife_info("borov_11_start") and not has_alife_info("borov_11_have") then
		if (sak.have_items_count("inventory_sakbox_borov",1)~=false or sak.have_items_count("scaintist_docs",1)~=false) then
			sak.borov_11_have_info()
			actor:give_info_portion("borov_11_have")
		end
	end
	if has_alife_info("bar_darklab_document_gain") and not has_alife_info("val_raid_start") then
		actor:give_info_portion("dar_document5")
		actor:give_info_portion("val_raid_start")
	end
	if has_alife_info("docent_pda_upgr_spot_info") and has_alife_info("docent_pda_upgr_hack_info") and not has_alife_info("docent_pda_upgr_info") then
		actor:give_info_portion("docent_pda_upgr_info")
	end
	-- [HE-PORT]
	if (has_alife_info("mil_dolg_dead") or has_alife_info("mil_dolg_collected") or this.is_actor_enemy_dolg() == true)
		and not has_alife_info("mil_dolg_skull_sniper_end")
	then
		actor:give_info_portion("mil_dolg_skull_sniper_end")
		actor:give_info_portion("mil_dolg_task_fail")
		actor:give_info_portion("mil_dolg_auto_attack")
	end
	if not has_alife_info("mil_dolg_skull_sniper_end") and this.is_actor_enemy_dolg() == false and has_alife_info("mil_dolg_skull_talk") then
		actor:give_info_portion("mil_dolg_skull_sniper_end")
	end
end

function process_info_portion(info_id)
	if info_id == "freeman_looted" then
		doc.barmen_freeman_msg()
	elseif info_id == "zub_night_star_receipt_have" then
		sak.dsc_zapravka_corpse_msg()
	elseif info_id == "red_ryaboi_looted" then
		sak.red_ryaboi_looted_msg()
	end
end

-- [HE-PORT-R2] перенос функций NLC HE из sak\sak_tasks.script
function bloodsuckers_dead()
    return ( db.actor:has_info( "mil_bloodsucker1_dead" ) and 
             db.actor:has_info( "mil_bloodsucker2_dead" ) and 
		     db.actor:has_info( "mil_bloodsucker3_dead" ) and 
		     db.actor:has_info( "mil_bloodsucker4_dead" ) ) ~= false   	
end
function bloodsuckers_not_dead()
	return not bloodsuckers_dead()
end

-- [HE-PORT]
function is_actor_enemy_dolg()
	local gulag = xr_gulag.get_gulag_by_name("mil_dolg")
	if gulag == nil or gulag:npc_is_enemy_to_anybody(db.actor) == false then
		return false
	end
	return true
end
