artmod_resiepts = {
	artmod_11 = {
		"mutant_dog_tail", "mutant_face_tushkano", "af_ameba_slime", "af_blood", "info_artmod_mincer_meat_mosquito_bald", "af_mincer_meat", "artmod_mincer_meat_mosquito_bald_text"
	},
	artmod_12 = {
		"mutant_boar_leg", "mutant_zombie_hand", "af_medusa", "af_vyvert", "info_artmod_gravi_gravi_zone", "af_gravi", "artmod_gravi_gravi_zone_text"
	},
	artmod_13 = {
		"mutant_dog_tail", "mutant_face_tushkano", "af_rusty_thorn", "af_medusa", "info_artmod_cristall_flower_mincer", "af_cristal_flower", "artmod_cristall_flower_mincer_text"
	},
	artmod_14 = { 
		"mutant_dog_tail", "mutant_boar_leg", "af_drops", "af_rusty_thorn", "info_artmod_rusty_kristall_buzz", "af_rusty_kristall", "artmod_rusty_kristall_buzz_text"
	},
	artmod_15 = { 
		"mutant_face_tushkano", "mutant_boar_leg", "af_medusa", "af_electra_sparkler", "info_artmod_electra_flash_zharka", "af_electra_flash", "artmod_electra_flash_zharka_text"
	},
	artmod_16 = { 
		"mutant_face_tushkano", "mutant_boar_leg", "af_rusty_thorn", "af_drops", "info_artmod_fireball_galant", "af_fireball", "artmod_fireball_galant_text"
	},
	
	artmod_19 = { 
		"af_dummy_battery", "af_dummy_dummy_new", "af_rusty_sea_urchin_dyn5d", "mutant_tail_cat", "info_artmod_battery_psi", "af_battery", "enc_artmod_battery_psi"
	},	
	
	artmod_21 = { 
		"mutant_dog_tail", "mutant_face_tushkano", "mutant_boar_leg", "af_drops", "info_artmod_electra_sparkler_mosquito_bald", "af_electra_sparkler", "artmod_electra_sparkler_mosquito_bald_text"
	},
	artmod_22 = { 
		"mutant_dog_tail", "mutant_boar_leg", "mutant_zombie_hand", "af_medusa", "info_artmod_rusty_kristall_gravi_zone", "af_blood", "artmod_rusty_kristall_gravi_zone_text"
	},
	artmod_23 = { 
		"mutant_face_tushkano", "mutant_boar_leg", "mutant_zombie_hand", "af_vyvert", "info_artmod_drops_mincer", "af_drops", "artmod_drops_mincer_text"
	},
	artmod_24 = {
		"mutant_face_tushkano", "mutant_boar_leg", "mutant_zombie_hand", "af_blood", "info_artmod_rusty_thorn_buzz", "af_rusty_thorn", "artmod_rusty_thorn_buzz_text"
	},
	artmod_25 = {
		"mutant_dog_tail", "mutant_face_tushkano", "mutant_zombie_hand", "af_medusa", "info_artmod_ameba_slime_zharka", "af_ameba_slime", "artmod_ameba_slime_zharka_text"
	},
	artmod_26 = {
		"mutant_dog_tail", "mutant_zombie_hand", "af_vyvert", "af_medusa", "info_artmod_cristall_flower_galant", "af_cristal_flower", "artmod_cristall_flower_galant_text"
	},
	artmod_31 = {
		"mutant_dog_tail", "mutant_boar_leg", "af_blood", "af_ameba_slime", "info_artmod_ameba_slug_mosquito_bald", "af_ameba_slug", "artmod_ameba_slug_mosquito_bald_text"
	},
	artmod_32 = {
		"mutant_dog_tail", "mutant_zombie_hand", "af_blood", "af_electra_sparkler", "info_artmod_electra_flash_gravi_zone", "af_electra_flash", "artmod_electra_flash_gravi_zone_text"
	},
	artmod_33 = {
		"mutant_dog_tail", "mutant_boar_leg", "af_medusa", "af_rusty_thorn", "info_artmod_rusty_kristall_mincer", "af_rusty_kristall", "artmod_rusty_kristall_mincer_text"
	},
	artmod_34 = {
		"mutant_dog_tail", "mutant_face_tushkano", "af_vyvert", "af_drops", "info_artmod_fireball_buzz", "af_fireball", "artmod_fireball_buzz_text"
	},
	artmod_35 = {
		"mutant_face_tushkano", "mutant_zombie_hand", "af_blood", "af_vyvert", "info_artmod_gravi_zharka", "af_gravi", "artmod_gravi_zharka_text"
	},
	artmod_36 = {
		"mutant_psevdodog_tail", "mutant_snork_leg", "af_mincer_meat", "af_ameba_slug", "info_artmod_ameba_mica_galant", "capsule@af_ameba_mica", "artmod_ameba_mica_galant_text"
	},
	artmod_41 = {
		"mutant_flesh_eye","mutant_snork_leg","af_rusty_kristall","af_fireball","info_artmod_cristall_mosquito_bald","capsule@af_cristall","artmod_cristall_mosquito_bald_text"
	},
	artmod_42 = {
		"mutant_tail_cat", "mutant_snork_leg", "af_ameba_slug", "af_cristal_flower", "info_artmod_night_star_gravi_zone", "capsule@af_night_star", "artmod_night_star_gravi_zone_text"
	},
	artmod_43 = {
		"mutant_burer_hand", "mutant_flesh_eye", "af_gravi", "af_electra_flash", "info_artmod_electra_moonlight_mincer", "capsule@af_electra_moonlight","artmod_electra_moonlight_mincer_text"
	},
	artmod_44 = {
		"mutant_krovosos_jaw", "af_rusty_thorn", "af_drops", "af_fireball", "info_artmod_cristall_buzz", "capsule@af_cristall", "artmod_cristall_buzz_text"
	},
	artmod_45 = {
		"mutant_chimera_kogot", "af_ameba_slime", "af_medusa", "af_cristal_flower", "info_artmod_night_star_zharka", "capsule@af_night_star", "artmod_night_star_zharka_text"
	},
	artmod_46 = {
		"mutant_burer_hand", "mutant_psevdodog_tail", "af_ameba_slug", "af_mincer_meat", "info_artmod_electra_moonlight_galant", "capsule@af_soul", "artmod_electra_moonlight_galant_text"
	},
	artmod_51 = {
		"mutant_burer_hand", "mutant_flesh_eye", "af_fireball", "af_rusty_kristall", "info_artmod_rusty_sea-urchin_mosquito_bald", "capsule@af_rusty_sea_urchin", "artmod_rusty_sea-urchin_mosquito_bald_text"
	},
	artmod_52 = {
		"mutant_chimera_kogot", "af_ameba_slime", "af_blood", "af_mincer_meat", "info_artmod_soul_gravi_zone", "capsule@af_soul", "artmod_soul_gravi_zone_text"
	},
	artmod_53 = {
		"mutant_krovosos_jaw", "af_blood", "af_ameba_slime", "af_ameba_slug", "info_artmod_ameba_slug_mincer", "capsule@af_ameba_mica", "artmod_ameba_slug_mincer_text"
	},
	artmod_54 = {
		"mutant_burer_hand", "mutant_tail_cat", "af_cristal_flower", "af_gravi", "info_artmod_night_star_buzz", "capsule@af_gold_fish", "artmod_night_star_buzz_text"
	},
	artmod_55 = {
		"mutant_krovosos_jaw", "af_vyvert", "af_electra_sparkler", "af_electra_flash", "info_artmod_electra_moonlight_zharka", "capsule@af_electra_moonlight", "artmod_electra_moonlight_zharka_text"
	},
	artmod_56 = {
		"mutant_chimera_kogot", "af_medusa", "af_vyvert", "af_gravi", "info_artmod_gold_fish_galant", "capsule@af_gold_fish", "artmod_gold_fish_galant_text"
	},
	artmod_61 = {
		"mutant_hand_kontroler", "af_drops_dyn5d", "af_fireball", "af_cristall", "info_artmod_dummy_dummy_mosquito_bald", "capsule@af_dummy_dummy", "artmod_dummy_dummy_mosquito_bald_text"
	},
	artmod_62 = {
		"mutant_poltergeist_glas", "af_ameba_slime_dyn5d", "af_ameba_slug", "af_ameba_mica", "info_artmod_dummy_pellicle_gravi_zone", "capsule@af_dummy_pellicle", "artmod_dummy_pellicle_gravi_zone_text"
	},
	artmod_63 = {
		"mutant_hand_kontroler", "af_medusa_dyn5d", "af_cristal_flower", "af_night_star", "info_artmod_dummy_glassbeads_mincer", "capsule@af_dummy_glassbeads", "artmod_dummy_glassbeads_mincer_text"
	},
	artmod_64 = {
		"mutant_psevdogigant_hand", "af_vyvert_dyn5d", "af_gravi", "af_gold_fish", "info_artmod_fuzz_kolobok_buzz", "capsule@af_dummy_kolobok", "artmod_fuzz_kolobok_buzz_text"
	},
	artmod_65 = {
		"mutant_poltergeist_glas", "af_electra_sparkler_dyn5d", "af_electra_flash", "af_electra_moonlight", "info_artmod_dummy_battery_zharka", "capsule@af_dummy_battery", "artmod_dummy_battery_zharka_text"
	},
	artmod_66 = {
		"mutant_psevdogigant_hand", "af_rusty_thorn_dyn5d", "af_rusty_kristall", "af_rusty_sea_urchin", "info_artmod_dummy_spring_galant", "capsule@af_dummy_spring", "artmod_dummy_spring_galant_text"
	},
	artmod_71 = {	
		"mutant_face_tushkano", "mutant_boar_leg", "af_rusty_thorn", "af_ameba_slime", "info_artmod_ameba_slug_ice", "af_ameba_slug", "artmod_ameba_slug_ice_text"
	},
	artmod_72 = {
		"mutant_e_chimera_kidney", "af_dummy_glassbeads", "mutant_krovosos_jaw", "mutant_hand_kontroler", "info_artmod_glassbeads_ice", "af_glassbeads", "artmod_glassbeads_ice_text"
	},
	artmod_73 = {
		"mutant_boar_leg", "mutant_zombie_hand", "af_medusa", "af_blood", "info_artmod_blood_ice", "af_mincer_meat", "artmod_blood_ice_text"
	},
	artmod_74 = {
		"mutant_dog_tail", "mutant_face_tushkano", "mutant_boar_leg", "af_ameba_slime", "info_artmod_vyvert_buzz", "af_vyvert", "artmod_vyvert_buzz_text"
	},
	artmod_75 = {
		"mutant_krovosos_jaw", "af_drops", "af_rusty_thorn", "af_rusty_kristall", "info_artmod_rusty_sea-urchin_ice", "capsule@af_rusty_sea_urchin", "artmod_rusty_sea-urchin_ice_text"
	},
	artmod_76 = {
		"mutant_dog_tail", "mutant_face_tushkano", "mutant_boar_leg", "af_rusty_thorn", "info_artmod_medusa_galant", "af_medusa", "artmod_medusa_galant_text"
	},
	artmod_81 = {
		"mutant_krovosos_jaw", "af_blood", "af_mincer_meat", "af_soul", "info_artmod_baloon_sakbuzz", "af_baloon", "artmod_baloon_sakbuzz_text"
	},
	artmod_84 = {
		"af_medusa_dyn1d", "af_drops_dyn5d", "af_blood_dyn5d", "af_rusty_thorn_dyn1d", "info_amk_recipt_simbion", "af_dummy_simbion", "artmod_simbion_buzz_text"
	},
	artmod_85 = {
		"energy_drink", "kolbasa", "vodka", "af_medusa", "info_energy_drink_new", "energy_drink_new", "energy_drink_new_text"
	},
	artmod_94 = {
		"af_dummy_buliz", "af_electra_moonlight_new", "af_electra_flash_new", "af_dummy_sparkler", "info_artmod_sul_buzz", "af_sul_new", "artmod_sul_buzz_text"
	} 
}

amk_resiepts = {
	{ "af_soul", 				"info_amk_recipt_souls_drops", 							"af_spirit_1_name",			"enc_amk_recipt_souls_drops_text" 						},
	{ "af_spirit_1", 			"info_amk_recipt_souls_fire", 							"af_spirit_2_name", 		"enc_amk_recipt_souls_fire_text"						},
	{ "af_spirit_2", 			"info_amk_recipt_souls_cristal", 						"af_spirit_3_name", 		"enc_amk_recipt_souls_cristal_text"						},
	{ "af_spirit_3", 			"info_amk_recipt_souls_bengal", 						"af_spirit_4_name", 		"enc_amk_recipt_souls_bengal_text"						},
 
	{ "af_electra_moonlight", 	"info_amk_recipt_tears_electra", 						"af_cry_1_name",	  		"enc_amk_recipt_tears_electra_text"						},
	{ "af_cry_1", 				"info_amk_recipt_tears_fire", 							"af_cry_2_name",			"enc_amk_recipt_tears_fire_text"						},
	{ "af_cry_2", 				"info_amk_recipt_tears_chimaera", 						"af_cry_3_name",			"enc_amk_recipt_tears_chimaera_text"					},
	{ "af_cry_3", 				"info_amk_recipt_tears_gigant", 						"af_cry_4_name",			"enc_amk_recipt_tears_gigant_text"						},
 
	{ "af_rusty_sea_urchin", 	"info_amk_recipt_dikoobraz", 							"af_dik_1_name",			"enc_amk_recipt_dikoobraz_text"							},
	{ "af_dik_1", 				"info_amk_recipt_electra_dikoobraz",					"af_dik_2_name",			"enc_amk_recipt_electra_dikoobraz_text"					},
	{ "af_dik_2", 				"info_amk_recipt_sopl_dikoobraz", 						"af_dik_3_name",			"enc_amk_recipt_sopl_dikoobraz_text"					},
	{ "af_dik_3", 				"info_amk_recipt_stone_dikoobraz", 						"af_dik_4_name",			"enc_amk_recipt_stone_dikoobraz_text"					},
 
	{ "af_dummy_kolobok", 		"info_amk_recipt_steel_kolobok", 						"af_kol_1_name",			"enc_amk_recipt_steel_kolobok_text"						},
	{ "af_kol_1", 				"info_amk_recipt_titan_kolobok", 						"af_kol_2_name",			"enc_amk_recipt_titan_kolobok_text"						},
	{ "af_kol_2", 				"info_amk_recipt_almaz_kolobok", 						"af_kol_3_name",			"enc_amk_recipt_almaz_kolobok_text"						},
	{ "af_kol_3", 				"info_amk_recipt_giant_small_brother", 					"af_kol_4_name",			"enc_amk_recipt_giant_small_brother_text"				},
 
	{ "af_dummy_dummy", 		"info_amk_recipt_dummy_fire", 							"af_pudd_1_name",			"enc_amk_recipt_dummy_fire_text"						},
	{ "af_pudd_1", 				"info_amk_recipt_dummy_bright", 						"af_pudd_2_name",			"enc_amk_recipt_dummy_bright_text"						},
	{ "af_pudd_2", 				"info_amk_recipt_dummy_moon", 							"af_pudd_3_name",			"enc_amk_recipt_dummy_moon_text"						},
	{ "af_pudd_3",			 	"info_amk_recipt_dummy_puding", 						"af_pudd_4_name",			"enc_amk_recipt_dummy_puding_text"						},
 
	{ "af_dummy_pellicle", 		"info_amk_recipt_shkura", 								"af_armor_1_name",			"enc_amk_recipt_shkura_text"							},
	{ "af_armor_1", 			"info_amk_recipt_cheshya", 								"af_armor_2_name",			"enc_amk_recipt_cheshya_text"							},
	{ "af_armor_2", 			"info_amk_recipt_pancir", 								"af_armor_3_name",			"enc_amk_recipt_pancir_text"							},
	{ "af_armor_3", 			"info_amk_recipt_controller_skalp", 					"af_armor_4_name",			"enc_amk_recipt_controller_skalp_text"					},
 
	{ "af_dummy_glassbeads", 	"info_amk_recipt_grandmother_glassbeards", 				"af_babka_1_name", 			"enc_amk_recipt_grandmother_glassbeards_text"			},
	{ "af_babka_1", 			"info_amk_recipt_pra_grandmother_glassbeards", 			"af_babka_2_name", 			"enc_amk_recipt_pra_grandmother_glassbeards_text"		},
	{ "af_babka_2", 			"info_amk_recipt_burer_grandmother_glassbeards", 		"af_babka_3_name", 			"enc_amk_recipt_burer_grandmother_glassbeards_text"		},
	{ "af_babka_3", 			"info_amk_recipt_burer_pra_grandmother_glassbeards",	"af_babka_4_name", 			"enc_amk_recipt_burer_pra_grandmother_glassbeards_text"	}
}

unique_resiepts = {
	{ "actor_jump_info", 				"Прыгалка",						"af_battery"			},							
	{ "info_artmod_glassbeads_ice", 	"Электробусы",					"af_glassbeads"			},
	{ "info_artmod_baloon_sakbuzz", 	"Баллончик",					"af_baloon"				},
	{ "info_artmod_sul_buzz", 			"Дирижабль",					"af_sul_new"			},
	{ "info_artmod_activ_anom",			"Снежок",						"af_dummy_sparkler"		},
	{ "info_dummy_dummy_new", 			"Аккумулятор",					"af_dummy_dummy_new"	},
	{ "info_red_battery", 				"Рубиновая батарейка",			"af_red_dummy_battery"	},
	{ "info_red_spring", 				"Рубиновая пружина",			"af_red_dummy_spring"	},
	{ "info_red_pellicle", 				"Рубиновая плёнка",				"af_red_dummy_pellicle"	},
	{ "info_green_blood", 				"Изумрудная Кровь камня", 		"af_dummy_green_blood"	},
	{ "info_green_medusa", 				"Изумрудная Медуза", 			"af_dummy_green_medusa"	},
	{ "info_green_vyvert", 				"Изумрудный Выверт",			"af_dummy_green_vyvert"	},
	{ "info_artmod_battery_psi", 		"Прыгалка из Пси-поля", 		"af_battery" }
}
	

amk_resiepts = {
	{ "af_soul", 				"info_amk_recipt_souls_drops", 							"af_spirit_1_name",			"enc_amk_recipt_souls_drops_text" 						},
	{ "af_spirit_1", 			"info_amk_recipt_souls_fire", 							"af_spirit_2_name", 		"enc_amk_recipt_souls_fire_text"						},
	{ "af_spirit_2", 			"info_amk_recipt_souls_cristal", 						"af_spirit_3_name", 		"enc_amk_recipt_souls_cristal_text"						},
	{ "af_spirit_3", 			"info_amk_recipt_souls_bengal", 						"af_spirit_4_name", 		"enc_amk_recipt_souls_bengal_text"						},
 
	{ "af_electra_moonlight", 	"info_amk_recipt_tears_electra", 						"af_cry_1_name",	  		"enc_amk_recipt_tears_electra_text"						},
	{ "af_cry_1", 				"info_amk_recipt_tears_fire", 							"af_cry_2_name",			"enc_amk_recipt_tears_fire_text"						},
	{ "af_cry_2", 				"info_amk_recipt_tears_chimaera", 						"af_cry_3_name",			"enc_amk_recipt_tears_chimaera_text"					},
	{ "af_cry_3", 				"info_amk_recipt_tears_gigant", 						"af_cry_4_name",			"enc_amk_recipt_tears_gigant_text"						},
 
	{ "af_rusty_sea_urchin", 	"info_amk_recipt_dikoobraz", 							"af_dik_1_name",			"enc_amk_recipt_dikoobraz_text"							},
	{ "af_dik_1", 				"info_amk_recipt_electra_dikoobraz",					"af_dik_2_name",			"enc_amk_recipt_electra_dikoobraz_text"					},
	{ "af_dik_2", 				"info_amk_recipt_sopl_dikoobraz", 						"af_dik_3_name",			"enc_amk_recipt_sopl_dikoobraz_text"					},
	{ "af_dik_3", 				"info_amk_recipt_stone_dikoobraz", 						"af_dik_4_name",			"enc_amk_recipt_stone_dikoobraz_text"					},
 
	{ "af_dummy_kolobok", 		"info_amk_recipt_steel_kolobok", 						"af_kol_1_name",			"enc_amk_recipt_steel_kolobok_text"						},
	{ "af_kol_1", 				"info_amk_recipt_titan_kolobok", 						"af_kol_2_name",			"enc_amk_recipt_titan_kolobok_text"						},
	{ "af_kol_2", 				"info_amk_recipt_almaz_kolobok", 						"af_kol_3_name",			"enc_amk_recipt_almaz_kolobok_text"						},
	{ "af_kol_3", 				"info_amk_recipt_giant_small_brother", 					"af_kol_4_name",			"enc_amk_recipt_giant_small_brother_text"				},
 
	{ "af_dummy_dummy", 		"info_amk_recipt_dummy_fire", 							"af_pudd_1_name",			"enc_amk_recipt_dummy_fire_text"						},
	{ "af_pudd_1", 				"info_amk_recipt_dummy_bright", 						"af_pudd_2_name",			"enc_amk_recipt_dummy_bright_text"						},
	{ "af_pudd_2", 				"info_amk_recipt_dummy_moon", 							"af_pudd_3_name",			"enc_amk_recipt_dummy_moon_text"						},
	{ "af_pudd_3",			 	"info_amk_recipt_dummy_puding", 						"af_pudd_4_name",			"enc_amk_recipt_dummy_puding_text"						},
 
	{ "af_dummy_pellicle", 		"info_amk_recipt_shkura", 								"af_armor_1_name",			"enc_amk_recipt_shkura_text"							},
	{ "af_armor_1", 			"info_amk_recipt_cheshya", 								"af_armor_2_name",			"enc_amk_recipt_cheshya_text"							},
	{ "af_armor_2", 			"info_amk_recipt_pancir", 								"af_armor_3_name",			"enc_amk_recipt_pancir_text"							},
	{ "af_armor_3", 			"info_amk_recipt_controller_skalp", 					"af_armor_4_name",			"enc_amk_recipt_controller_skalp_text"					},
 
	{ "af_dummy_glassbeads", 	"info_amk_recipt_grandmother_glassbeards", 				"af_babka_1_name", 			"enc_amk_recipt_grandmother_glassbeards_text"			},
	{ "af_babka_1", 			"info_amk_recipt_pra_grandmother_glassbeards", 			"af_babka_2_name", 			"enc_amk_recipt_pra_grandmother_glassbeards_text"		},
	{ "af_babka_2", 			"info_amk_recipt_burer_grandmother_glassbeards", 		"af_babka_3_name", 			"enc_amk_recipt_burer_grandmother_glassbeards_text"		},
	{ "af_babka_3", 			"info_amk_recipt_burer_pra_grandmother_glassbeards",	"af_babka_4_name", 			"enc_amk_recipt_burer_pra_grandmother_glassbeards_text"	}
}

unique_resiepts = {
	{ "actor_jump_info", 				"Прыгалка",						"af_battery"			},							
	{ "info_artmod_glassbeads_ice", 	"Электробусы",					"af_glassbeads"			},
	{ "info_artmod_baloon_sakbuzz", 	"Баллончик",					"af_baloon"				},
	{ "info_artmod_sul_buzz", 			"Дирижабль",					"af_sul_new"			},
	{ "info_artmod_activ_anom",			"Снежок",						"af_dummy_sparkler"		},
	{ "info_dummy_dummy_new", 			"Аккумулятор",					"af_dummy_dummy_new"	},
	{ "info_red_battery", 				"Рубиновая батарейка",			"af_red_dummy_battery"	},
	{ "info_red_spring", 				"Рубиновая пружина",			"af_red_dummy_spring"	},
	{ "info_red_pellicle", 				"Рубиновая плёнка",				"af_red_dummy_pellicle"	},
	{ "info_green_blood", 				"Изумрудная Кровь камня", 		"af_dummy_green_blood"	},
	{ "info_green_medusa", 				"Изумрудная Медуза", 			"af_dummy_green_medusa"	},
	{ "info_green_vyvert", 				"Изумрудный Выверт",			"af_dummy_green_vyvert"	},
	{ "info_artmod_battery_psi", 		"Прыгалка из Пси-поля", 		"af_battery" }
}

artCollections={
	{ "af_dummy_green_vyvert", 		"af_dummy_green_medusa", 		"af_dummy_green_blood", 		"", 		"", 		"sak.gg_go_down()" 				},
	{ "af_vyvert_dyn6d", 			"af_gravi_dyn5d", 				"af_gold_fish_dyn5d", 			"", 		"", 		"sak.gg_add_mass()" 			},
	{ "af_unknown_28_new",			"af_dummy_buliz",				"af_gold_fish_dyn6d", 			"",			"",			"sak.gg_disable_black_tip()"	},
}


function artCollections_close()
	local at = artCollections
	if not sak.arts_operate then return end
	local actor = db.actor
	for aC = 1, #artCollections do
		if 
				sak_inventory.belt_items[ at[ aC ][ 1 ] ] 
			and sak_inventory.belt_items[ at[ aC ][ 2 ] ] 
			and sak_inventory.belt_items[ at[ aC ][ 3 ] ] 
		then 
			for i, k in pairs( sak_inventory.belt_items ) do
				if i == at[ aC ][ 1 ] then
					actor_params.toggle_slot( actor:object( at[ aC ][ 1 ] ):id(), false )
					set_value( "belt_art_1", actor:object( at[ aC ][ 1 ] ):id() )
				elseif i == at[ aC ][ 2 ] then
					actor_params.toggle_slot( actor:object( at[ aC ][ 2 ] ):id(), false )        
					set_value( "belt_art_2", actor:object( at[ aC ][ 2 ] ):id() )
				elseif i == at[ aC ][ 3 ] then
					actor_params.toggle_slot( actor:object( at[ aC ][ 3 ] ):id(), false )  
					set_value( "belt_art_3", actor:object( at[ aC ][ 3 ] ):id() )
				end
			end
			local obj_f
			if at[ aC ][ 4 ] ~= "" then
				amk.spawn_item_in_inv( at[ aC ][ 4 ] )
				amk.spawn_item_in_inv( at[ aC ][ 4 ] )
				amk.spawn_item_in_inv( at[ aC ][ 4 ] )
			else
				if at[ aC ][ 5 ] ~= "" then
					local item_in_slot = actor:item_in_slot( 6 )
					if item_in_slot ~= nil then 
						params.add_coll = tonumber( at[ aC ][ 5 ] )
						amk.spawn_item_in_inv( "art_collection_fake" )
						amk.spawn_item_in_inv( "art_collection_fake" )
						amk.spawn_item_in_inv( "art_collection_fake" )
					else 
						amk.spawn_item_in_inv( "art_collection_fake" )
						amk.spawn_item_in_inv( "art_collection_fake" )
						amk.spawn_item_in_inv( "art_collection_fake" )
					end
				else
					amk.remove_item( actor:object( at[ aC ][ 1 ] ) )
					amk.remove_item( actor:object( at[ aC ][ 2 ] ) )
					amk.remove_item( actor:object( at[ aC ][ 3 ] ) )
					loadstring( at[ aC ][ 6 ] )()
				end
			end
			sak.send_tip(
				"Вроде как что-то изменилось... Вроде бы артефакты в сборе по иному действуют",
				"Неужели? Сборка!", 0, 10, "artmod", "rememb", "green"
			)
			break
		end
	end
end


function artCollections_open()
	params.add_coll = 0
	local at = artCollections
	local actor = db.actor
	for aC = 1, table.getn( artCollections ) do
		local fake = sak_inventory.belt_items[ at[ aC ][ 4 ] ] or sak_inventory.belt_items[ "art_collection_fake" ]
		if fake then
			for i = 1, 3 do
				actor_params.toggle_slot( fake[ i ], false )  
				g_sim:release( g_sim:object( fake[ i ] ), true )
			end
			local art_1 = get_value( "belt_art_1", 0 )
			local art_2 = get_value( "belt_art_2", 0 )
			local art_3 = get_value( "belt_art_3", 0 )
			if 
				   art_1 == 0 
				or art_2 == 0 
				or art_3 == 0 
			then 
				return 
			end
			actor_params.to_belt( art_1 )
			actor_params.to_belt( art_2 )
			actor_params.to_belt( art_3 )  
			for a = 1, 3 do 
				remove_value( "belt_art_" .. a )
			end	
			sak_inventory.need_update_inventory()
			break
		end
	end
end

function artmod_components_have( num )
	local mod = "artmod_" .. num
	if 
			sak.have_items_count( artmod_resiepts[ mod ][ 1 ], 1 ) ~= false 
		and sak.have_items_count( artmod_resiepts[ mod ][ 2 ], 1 ) ~= false 
		and sak.have_items_count( artmod_resiepts[ mod ][ 3 ], 1 ) ~= false 
		and sak.have_items_count( artmod_resiepts[ mod ][ 4 ], 1 ) ~= false 
	then
		return true
	else
		return false
	end
end

function artmod_components_give( num )
	local mod = "artmod_" .. num
	for i, k in pairs( sak_inventory.rucksack ) do
		for a = 1, 4 do
			if strpos( i, artmod_resiepts[ mod ][ a ], 1, true ) then 	
				for m = 1, #k do
					local obj = client_obj( k[ m ] )
					if obj then
						misc.release_obj( obj )
						sak.relocate_item( "out", artmod_resiepts[ mod ][ a ], 1 )
						break
					end
				end
			end
		end
	end	
end

-- g_loadstring sak_artmods.artmod_components_create(36)
function artmod_components_create(num, part, cond)
	local mod = "artmod_" .. num
	local rnd = level.get_time_days() % 4 + 1

	local items = {}
	if part == "in" then
		items = {
			artmod_resiepts[mod][1],
			artmod_resiepts[mod][2],
			artmod_resiepts[mod][3],
			artmod_resiepts[mod][4]
		}
	else
		items = {
			artmod_resiepts[mod][6]
		}
	end

	for _, item in ipairs(items) do
		local payload = nlc_capsules.from_descriptor(item)
		if payload then
			payload.dyn = rnd
			kotovod.add_bad_item( nlc_capsules.descriptor(payload), cond and tonumber(cond) or 1 )
		elseif
			string.find(item, "af_", 1, true)
			and not string.find(item, "af_dummy_", 1, true)
			and not string.find(item, "_dyn", 1, true)
			and not string.find(item, "_new", 1, true)
		then
			kotovod.add_bad_item(item .. "_dyn" .. rnd .. "d", cond and tonumber(cond) or 1)
		else
			kotovod.add_bad_item(item, cond and tonumber(cond) or 1)
		end
	end
end

function artmod_components_info( num )
	local mod = "artmod_" .. num
	if has_alife_info( artmod_resiepts[ mod ][ 5 ] ) then return true end
	return false
end


function artmod_timer_start( num )
	sak_dialog.start_time( "time_start_artmod_" .. num )
end

function is_ready_time_artmod( num, time )
	return sak_dialog.is_ready_time( "time_start_artmod_" .. num, time ) == true
end

function not_ready_time_artmod( num, time )
	return sak_dialog.not_ready_time( "time_start_artmod_" .. num, time ) == true
end

function clear_ready_time_artmod( num )
	sak_dialog.clear_ready_time( "time_start_artmod_" .. num )
end


function artmod_84_have()
	return artmod_components_have( 84 ) == true
end