-- [HE-PORT]
function attach( sm )
	sm:subscribe({ signal = "on_take", fun = this.check_taked_item })
end

local check_item_tbl = {}

check_item_tbl[ 'amk_zapiska' ] = function( obj )
	if level.name() == "l03_agroprom" then
		sak.add_new_escape_100()
		sak.add_new_lost_agr_176()
	else
		kotovod.modificat_recipes()
	end
	misc.release_obj( obj )
end

function check_taked_item( obj, sobj )
	local sect = obj:section()
	if check_item_tbl[ sect ] then
		check_item_tbl[ sect ]( obj, sobj )
	end
end
