-- [HE-PORT]
function attach( sm )
	sm:subscribe({ signal = "on_take", fun = this.check_taked_item })
end

local check_item_tbl = {}

check_item_tbl[ 'amk_zapiska' ] = function( obj )
	if level.name() == "l03_agroprom" then
		sak.add_new_escape_100()
		sak.add_new_lost_agr_176()
	else
		kotovod.modificat_recipes()
	end
	misc.release_obj( obj )
end

check_item_tbl[ 'amk_zapiska_sak' ] = function()
	if has_alife_info( "provodnik_senks_have" ) then return end
	give_info( "provodnik_senks_have" )
end

check_item_tbl[ 'arc_art_box_1basic' ] = function()
	if has_alife_info( "kvest_art_have" ) then return end
	give_info( "kvest_art_have" )
end

check_item_tbl[ 'x18_botan_book' ] = function()
	if has_alife_info( "info_amk_recipt_simbion" ) then return end
	give_info( "info_amk_recipt_simbion" )
	kotovod.sms_recipt_found( "info_amk_recipt_simbion" )
end

check_item_tbl["pda_chip_rad"] = function() he_pda_access.module_pickup() end

function check_taked_item( obj, sobj )
	local sect = obj:section()
	if check_item_tbl[ sect ] then
		check_item_tbl[ sect ]( obj, sobj )
	end
end
