local KEY = "gluzov_art_id"

function attach(sm)
	sm:subscribe({ signal = "on_item_to_belt", fun = this.on_item_to_belt })
end

function set_locked_id(id)
	if type(id) == "number" then
		set_value(KEY, id)
	end
end

function unlock()
	remove_value(KEY)
end

function is_locked_id(id)
	local locked = get_value(KEY, nil)
	return locked ~= nil and id == locked
end

function is_locked(obj)
	if not obj then return false end
	return is_locked_id(obj:id())
end

function on_item_to_belt(obj, sobj)
	if not is_locked(obj) then return end
	dsh.exec_on_update(
		function()
			local id = get_value(KEY, nil)
			local item = id and level.object_by_id(id)
			if item and db.actor and db.actor:is_on_belt(item) then
				db.actor:move_to_ruck(item)
			end
		end
	)
end
