
-- [HE-PORT] perenos kvestovyh funkcij iz NLC HE (kotovod\nlc_fixes.script)
function create_limansk_corpse()
	sak.create_corpse( "limansk_mielofon_corpse",
        sak.v3f( -50.284, -10.629, -183.869 ), 2993, 2894, 10108
    )
end
function rewrite_val_box_data()
	local box = g_sim:object( "dv_sak_box_ammo" )
	if box then 
		local pk         = get_netpk( box )
		local data       = pk:get()
		data.custom_data = "bes"
		pk:set( data )
	end
end
function create_wpngm()
	local obj = g_sim:create( "wpn_gm94",
		sak.v3f( -50.077, -10.756, -185.717 ),
		3717, 2991
	)
	local pda = g_sim:create( "anomaly_pda",
		sak.v3f( -50.077, -10.756, -185.717 ),
		3717, 2991
	)
	local ruck = amk.spawn_item( "rukzak_inventory_box",
		sak.v3f( -49.433, -10.761, -185.326 ),
		2993, 2894
	)
	misc.process_spawn()
	if ruck then
		local tbl = { "af_dummy_simbion", "af_dummy_buliz", "af_dummy_fire" }
		local art = misc.spawn_to( tbl[ get_value("r_treas_items", 1) ], ruck )
		local akk = misc.spawn_to( "af_full_akkum_big", ruck )
		local rnd = lua_random( 55, 73 ) / 100
		kotovod.update_item_condition( art, rnd )
		kotovod.update_item_condition( akk, rnd )
		kotovod.add_box_protection( ruck:name() )
		sak.off_on( ruck )
	end
end

-- [HE-PORT]
function new_game_init()
	x18_botan_book_spawn()
	dsh.get_next_random( "pda_drop_chance", 1, 1000 )
	dsh.get_next_random( "pda_status_rnd", 1, 10 )
	dsh.get_next_random( "pda_treas_rnd", 1, 100 )
	dsh.get_next_random( "sultan_weapon_treasure", 1, 3 )
	dsh.get_next_random( "generate_mutant_table", 1, 3 )
	dsh.get_next_random( "generate_mutant_request", 1, 5 )
	dsh.get_next_random( "generate_mutant_reward", 1, 5 )
	start_randoms()
	doc.add_playboy()
	give_yantar_room_lamp_info()
end

function start_randoms()
	for _, v in ipairs({
		"kotovod.rec_art_info",
		"kotovod.gg_identic_item_have_give",
		"amk_mod.af_start_transform",
		"amk_anoms.randomize_arts",
		"arc_diary.controler_random",
		"kotovod.rnd_item",
		"kotovod.rnd_item_amount",
		"generic_rnd",
		"news_main.do_eternal_stalker",
		"xr_box.ph_item_box"
	}) do
		dsh.get_next_random( v )
	end
	for _, v in ipairs({
		"minigame_bet_rnd"
	}) do
		dsh.get_fixed_random( v, 1 )
	end
end

function x18_botan_book_spawn()
	local t = { "x18_inventory_box", "x18_inventory_box_0002", "x18_inventory_box1" }
	local box = server_obj( t[ get_value( "r_treas_items", 1 ) ] )
	if box then
		misc.spawn_to( "x18_botan_book", box )
	end
end

function give_yantar_room_lamp_info()
	if has_alife_info( "yantar_room_lamp_on" ) then return end
	if has_alife_info( "yantar_room_lamp_off" ) then return end
	db.actor:give_info_portion( "yantar_room_lamp_off" )
end

function save()
	_G.flag_can_save = true
	if get_value("blowout", 0) == 0 and _G.flag_can_save then
		local lname = level.name()
		local where = ( lname == "l01_escape" and "Бункер Сидоровича" ) or "Бункер Сахарова"
		local bl_save = string.format( "День %s %s. %s [%s]", timers.Get_Game_Days(), level.get_time_hours(), level.get_time_minutes(), where )
		cmd("save", dsh.safe_file_name(bl_save))
	end
end
