local noise_snd = nil
local texture_name = "ui\\ui_pda_noise"

function on_info( info_id )
	if info_id == "off" then
		if noise_snd and noise_snd:playing() then
			noise_snd:stop()
		end
		noise_snd = nil
		sak.close_window()
	elseif info_id == "on" then
		texture_name = "ui\\ui_pda_noise"
		level.start_stop_menu( PdaNoiseWnd(), true )
	elseif info_id == "on_broken" then
		texture_name = "ui\\ui_pda_broken"
		level.start_stop_menu( PdaNoiseWnd(), true )
	end
end

class "PdaNoiseWnd" ( CUIScriptWnd )
function PdaNoiseWnd:__init() super()
	self:Init( 0, 0, 1024, 768 )
	self.ClickBtnExit = function() level.start_stop_menu( self, true ) end
	self.noise = CUIStatic()
	self.noise:InitTexture( texture_name )
	self.noise:SetOriginalRect( 0, 0, 1024, 768 )
	self.noise:Init( 3, 20, 891, 643 )
	self:AttachChild( self.noise )
	self.ignore_first_press = true
	bind_stalker.set_pda_cb(true)
	-- [HE-PORT]
	if texture_name == "ui\\ui_pda_noise" then
		noise_snd = xr_sound.get_safe_sound_object( "device\\pda\\noise_on" )
		if noise_snd then
			noise_snd:play_at_pos( db.actor, vector(), 0.1, sound_object.s2d + sound_object.looped )
			noise_snd.volume = 0.25
		end
	end
end
function PdaNoiseWnd:OnKeyboard( dik, keyboard_action )
	if self.ignore_first_press then
		self.ignore_first_press = false
		return true
	end
	CUIScriptWnd.OnKeyboard( self, dik, keyboard_action )
	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		local bind = dik_to_bind( dik )
		if dik == DIK_keys.DIK_ESCAPE
			or bind == key_bindings.kACTIVE_JOBS
			or bind == key_bindings.kMAP
			or bind == key_bindings.kPDA_CLOCK
		then
			if bind_stalker.get_pda_on() then
				if noise_snd and noise_snd:playing() then
					noise_snd:stop()
				end
				noise_snd = nil
				self:ClickBtnExit()
				bind_stalker.set_pda_cb(false)
			end
		end
	end
	return true
end
