-- fix_manager v. 1.2
-- Как пользоваться:
-- Названия выполняемых функций должны быть внесены в таблицу fixes_pack или fixes_pack_all (функции run_fixes) в ковычках, через запятую: "script_name.fix_name", "other_script_name.othter_fix_name", ...
-- Функции, выполненные из таблицы fixes_pack, сохраняются и повторно не вызываются, в отличии от ф-ий из fixes_pack_all, которые отрабатывают при каждой (пере)загрузке.
-- Для очистки сохранённого списка вызовов следует выполнить run_fixes с аргументом true, т.е. run_fixes(true).

function fix_mgr()
	run_fixes()
end

function run_fixes(clear)  
	local fixes_pack = {
		"s_fixes.create_underground_safe_zones",		
		"s_fixes.create_x8_safe_zone",
		"s_fixes.give_yantar_room_lamp_info",
		"s_fixes.create_esc_notebook",
		"s_fixes.fix_lc"
	}
	
	local fixes_pack_all = {
	}
	
	if clear then
		log2("[ s_fixes ]: clearing saved vars")
		local t = {}
		set_value("fixes_done_tbl", t)
	end

	if #fixes_pack == 0 and #fixes_pack_all == 0 then 
		log2("[ s_fixes ]: fixes_pack is empty")
		return
	end
	
	if #fixes_pack_all > 0 then
		for _,fix_name in ipairs(fixes_pack_all) do
			log2("[ s_fixes ]: trying to apply fix = %s from [fixes_pack_all]", fix_name)
			loadstring(fix_name.."()")()
		end
	end
	
	if #fixes_pack > 0 then
		local fixes_done_tbl = get_value("fixes_done_tbl", {}) --- таблица для хранения названий всех фиксов
		local fix_tbl = {}
		for _, fix_name in pairs(fixes_pack) do
			if str_in_tab (fix_name,fixes_done_tbl) then
				log2("[ s_fixes ]: fix_name = %s has already been executed earlier --> ignoring", fix_name)
			else
				log2("[ s_fixes ]: trying to apply fix = %s", fix_name)
				loadstring(fix_name.."()")()
			end	
			table.insert(fix_tbl, fix_name)
		end
		set_value("fixes_done_tbl", fix_tbl)
	end
end

function new_game_spawn()
	log2("~~[%s.new_game_spawn]: done!", script_name())

	red_forest_eco_restr()
	red_forest_kill_restr()
	x18_kill_restr()
	sanek_trade_res()
	x18_botan_book_spawn()
	ros_kill_restr()
	rad_greedys()
	bar_tp()
	-- bar_rad()
	garb_lv_rad()
	dsh.get_next_random("pda_drop_chance", 1, 1000)
	dsh.get_next_random("pda_status_rnd", 1, 10)
	dsh.get_next_random("pda_treas_rnd", 1, 100)
	dsh.get_next_random("sultan_weapon_treasure", 1, 3)
	dsh.get_next_random("generate_mutant_table", 1, 3)
	dsh.get_next_random("generate_mutant_request", 1, 5)
	dsh.get_next_random("generate_mutant_reward", 1, 5)
	start_randoms()
	doc.add_playboy()
	amk.spawn_item("sleeping_pill",sak.v3f(-213.0025,-22.5375652313232,-126.3443),59,41279)
end

--new kotovod
function start_randoms()
    for _, v in ipairs({ 
		"kotovod.rec_art_info",		
		"kotovod.gg_identic_item_have_give",	
		"amk_mod.af_start_transform",	
        "amk_anoms.randomize_arts",		
		"arc_diary.controler_random",
		"kotovod.rnd_item",
		"kotovod.rnd_item_amount",
		"generic_rnd",
		"news_main.do_eternal_stalker",
		"xr_box.ph_item_box"		
    }) do
		dsh.get_next_random( v )	
    end
    for _, v in ipairs({
        "minigame_bet_rnd"
    }) do
        dsh.get_fixed_random( v, 1 )
    end	
end

-- Фиксирование костей физ. объектов, смена позиции, если они не должны перемещаться



function create_x8_safe_zone()
	local lab_safe_zones = get_value( "lab_safe_zones", {} )
	if #lab_safe_zones > 1 then return end	
	local sr_obj = alife():create( "space_restrictor", vector():set( 2.38, 9.26, 23.37 ), 4834, 3210 )		
	if sr_obj then 
		local custom = [=[
			[logic]
			active = sr_idle@wait
			[sr_idle@wait]
			on_actor_inside = sr_idle@inside %=undergrounds_hits.enable_sz_protection%
			[sr_idle@inside]
			on_actor_outside = sr_idle@wait %=undergrounds_hits.disable_sz_protection%
		]=]		
		kotovod_restrictors.rewrite_box_restrictor( sr_obj, custom, 50, 35, 9 )
        sr_obj.direction = sak.v3f( 0, 1.6, 0 )
		sr_obj:set_name( "safe_zone_x8_sleep" )
		table.insert( lab_safe_zones[ sr_obj.level_name ], sr_obj.id )		
	end
	set_value( "lab_safe_zones", lab_safe_zones )
end



function give_yantar_room_lamp_info()
	if has_alife_info( "yantar_room_lamp_on" ) then return end
	if has_alife_info( "yantar_room_lamp_off" ) then return end
	db.actor:give_info_portion( "yantar_room_lamp_off" )
end

function create_esc_notebook()
	local old_note = g_sim:object( "physic_object0025" )
	if old_note then 
		misc.release_obj( old_note )
	end	
	local sobj = alife():create( "physic_object", sak.v3f( -245.128, -23.945, -133.611 ), 12442, 4 )
	if sobj then 
		local pk 		 = get_netpk( sobj, 1 )	
		local data 		 = pk:get()		
		data.physic_type = 3
		data.mass 		 = 10	
		data.visual_name = "equipments\\item_notebook"		
		data.custom_data = 
			"[collide]\n" ..
			"ignore_dynamic\nignore_ragdoll\nignore_static\n\n" .. 
			"[ph_heavy]\n" ..
			"[logic]\n" .. 
			"active = ph_idle@enable\n" ..
			"[ph_idle@enable]\n" ..			
			"tips = ui_mm_save\n" ..
			"on_use = %=s_fixes.save()%"
		pk:set( data )		
		sobj.direction = sak.v3f( 0, 0.871, 0 )
		sobj:set_name( "esc_notebook" )
	end
end

function save()
	_G.flag_can_save = true
	if get_value("blowout", 0) == 0 and _G.flag_can_save then
		local lname = level.name()
		local where = ( lname == "l01_escape" and "Бункер Сидоровича" ) or "Бункер Сахарова" 
		local bl_save = string.format( "День %s %s. %s [%s]", timers.Get_Game_Days(), level.get_time_hours(), level.get_time_minutes(), where )
		cmd("save", dsh.safe_file_name(bl_save))
	end	
end

-- Сюда надо будет добавлять те, которым не нужно показывать окно, например: тп в чащу из агро! 
-- Не забыть добавить все остальные по тп

local skip_lc = {
	[ "argu_teleport_aver" ] = true,
}

function fix_lc()
    for a = 1, MAX_OBJ_ID do
        local sobj = g_sim:object(a)
        if sobj and sobj:clsid() == clsid.level_changer then
            local name = sobj:name()
            if not skip_lc[name] then
                local pk = get_netpk(sobj)
                local data = pk:get()
                data.silent_mode = 0
                pk:set(data)
                -- sak.send_tip(name, "Изменили переход:", 0, 10, "nlc", "pda_news", "gray")
            end
        end
    end
end