-- fix_manager v. 1.2
-- Как пользоваться:
-- Названия выполняемых функций должны быть внесены в таблицу fixes_pack или fixes_pack_all (функции run_fixes) в ковычках, через запятую: "script_name.fix_name", "other_script_name.othter_fix_name", ...
-- Функции, выполненные из таблицы fixes_pack, сохраняются и повторно не вызываются, в отличии от ф-ий из fixes_pack_all, которые отрабатывают при каждой (пере)загрузке.
-- Для очистки сохранённого списка вызовов следует выполнить run_fixes с аргументом true, т.е. run_fixes(true).

function fix_mgr()
	run_fixes()
	fix_physic_objects()
	fix_npc_pos()
end

function run_fixes(clear)  
	local fixes_pack = {
		"s_fixes.playboy_spawn_tuzla_nlc30",
		"s_fixes.restore_nlc30_static_items",
		"s_fixes.remove_dumenko_content",
		"s_fixes.create_underground_safe_zones",		
		"s_fixes.create_x8_safe_zone",
		"s_fixes.remove_petrenko_items",
		"s_fixes.give_yantar_room_lamp_info",
		"s_fixes.create_esc_notebook",
		"s_fixes.fix_lc"
	}
	
	local fixes_pack_all = {
	}
	
	if clear then
		log2("[ s_fixes ]: clearing saved vars")
		local t = {}
		set_value("fixes_done_tbl", t)
	end

	if #fixes_pack == 0 and #fixes_pack_all == 0 then 
		log2("[ s_fixes ]: fixes_pack is empty")
		return
	end
	
	if #fixes_pack_all > 0 then
		for _,fix_name in ipairs(fixes_pack_all) do
			log2("[ s_fixes ]: trying to apply fix = %s from [fixes_pack_all]", fix_name)
			loadstring(fix_name.."()")()
		end
	end
	
	if #fixes_pack > 0 then
		local fixes_done_tbl = get_value("fixes_done_tbl", {}) --- таблица для хранения названий всех фиксов
		local fix_tbl = {}
		for _, fix_name in pairs(fixes_pack) do
			if str_in_tab (fix_name,fixes_done_tbl) then
				log2("[ s_fixes ]: fix_name = %s has already been executed earlier --> ignoring", fix_name)
			else
				log2("[ s_fixes ]: trying to apply fix = %s", fix_name)
				loadstring(fix_name.."()")()
			end	
			table.insert(fix_tbl, fix_name)
		end
		set_value("fixes_done_tbl", fix_tbl)
	end
end

function new_game_spawn()
	log2("~~[%s.new_game_spawn]: done!", script_name())

	red_forest_eco_restr()
	red_forest_kill_restr()
	x18_kill_restr()
	spawn_agro_blocks()
	sanek_trade_res()
	x18_botan_book_spawn()
	ros_kill_restr()
	rad_greedys()
	bar_tp()
	-- bar_rad()
	mil_aver_lc_debris_spawn()
	garb_lv_rad()
	dsh.get_next_random("pda_drop_chance", 1, 1000)
	dsh.get_next_random("pda_status_rnd", 1, 10)
	dsh.get_next_random("pda_treas_rnd", 1, 100)
	dsh.get_next_random("sultan_weapon_treasure", 1, 3)
	dsh.get_next_random("generate_mutant_table", 1, 3)
	dsh.get_next_random("generate_mutant_request", 1, 5)
	dsh.get_next_random("generate_mutant_reward", 1, 5)
	start_randoms()
	doc.add_playboy()
	restore_nlc30_static_items()
	remove_dumenko_content()
	amk.spawn_item("sleeping_pill",sak.v3f(-213.0025,-22.5375652313232,-126.3443),59,41279)
end

--new kotovod
function start_randoms()
    for _, v in ipairs({ 
		"kotovod.rec_art_info",		
		"kotovod.gg_identic_item_have_give",	
		"amk_mod.af_start_transform",	
        "amk_anoms.randomize_arts",		
		"arc_diary.controler_random",
		"kotovod.rnd_item",
		"kotovod.rnd_item_amount",
		"generic_rnd",
		"news_main.do_eternal_stalker",
		"xr_box.ph_item_box"		
    }) do
		dsh.get_next_random( v )	
    end
    for _, v in ipairs({
        "minigame_bet_rnd"
    }) do
        dsh.get_fixed_random( v, 1 )
    end	
end

-- Фиксирование костей физ. объектов, смена позиции, если они не должны перемещаться
function fix_physic_objects()
	local pt = profile_timer()
	pt:start()

	local ph_objects = {
		-- {"bar_kletka_0001", "bone01", 161.990005493164, 0.100000001490116, 82.0299987792969, 42125, 1211} -- машина в баре на проходе к Лисапеду // Sn: этот объект теперь статик
	}

	for _, v in ipairs(ph_objects) do
		local sobj = server_obj(v[1])
		if sobj then
			local pk = get_netpk(sobj, 1)
			local data = pk:get()
			data.fixed_bones = v[2]
			pk:set(data)
			sobj:used_ai_locations(false)

			-- Manool: эти свойства доступны для записи
			-- Всё-таки позиция обновляется после свитча оффлайн-онлайн,
			-- если свойства перезаписать ПОСЛЕ перезаписи нетпакета
			sobj.position = vector():set(v[3], v[4], v[5])
			sobj.m_level_vertex_id = v[6]
			sobj.m_game_vertex_id = v[7]

			local ini = sobj:spawn_ini()
			ini.readonly = false
			ini:w_bool("collide", "ignore_static", true) -- игнорирование статики (если у какого-нибудь объекта его нет)
			sobj:save_spawn_ini()
		end
	end
	pt:stop()
	log2("[%s.fix_physic_objects]: Time: %.2fms (%s)", script_name(), pt:time() / 1000, pt:time())
end

function fix_npc_pos()
	local level_npc = {
		["l01_escape"] = {
			{"esc_vergas", -219.050003051758,-19.8999996185303,-168.899993896484, 34087, 47},
		},
		["l05_bar"] = {
			{"bar_lisaped", 164.899993896484, 0.25, 108.449996948242, 43119, 1187},
		},
		["l04_darkvalley"] = {
			{"val_bandit_trader", 28.7099990844727,4.53999996185303,-85.3899993896484, 209382, 1099},
		},
	}
	local npct = level_npc[level.name()]
	if not npct then return end
	for _, par in pairs(npct) do
		local sobj = alife():object(par[1])
		local targ_pos = vector():set(par[2], par[3], par[4])
		if sobj and sobj.level_name == level.name() then
			-- log2("[%s.fix_npc_pos]: [%s] has wrong pos: {%s, %s, %s} %s, %s",
			-- 	script_name(), sobj:name(), sobj.position.x, sobj.position.y, sobj.position.z, sobj.m_level_vertex_id, sobj.m_game_vertex_id
			-- )
			alife():teleport_object(sobj.id, targ_pos, par[5], par[6])
		end
	end
end

function mil_aver_lc_debris_spawn()
	local obj = amk.spawn_item("physic_object",sak.v3f(-31.4152,-7.9518,-56.8445),1592,276525)
	if obj then
		local pk = get_netpk(obj,1)
		local data = pk:get()
		data.visual_name = "new_item\\stena_yantar"
		data.physic_type=3
		data.fixed_bones="link"
		data.mass=250
		data.custom_data = "[collide]\nignore_static"
		pk:set(data)
		set_value("mil_aver_lc_debris",obj.id)
	end
end

function spawn_agro_blocks()
	local blocks = g_sim:create("physic_object",vector():set(-130.0938,0.3198,-139.0064),4,810)
	local pk, data
	if blocks then
		pk = get_netpk(blocks,1)
		data = pk:get()
		data.visual_name="physics\\prop_3bloks"
		data.mass=300
		data.fixed_bones = "bone01","bone02","bone03","bone04","bone05"
		pk:set(data)
	end
end

function red_forest_eco_restr()
	local res = g_sim:create("space_restrictor",vector():set(-152.3122,2.2915,-28.1060),6298,3240)
    local custom = "[logic]\nactive = sr_idle@idle\n[sr_idle@idle]\non_info = {+info_saharov_scientist_rf_start} sr_idle@work\n[sr_idle@work]\non_actor_inside = nil %+scientist_red_forest_dead =doc.red_corpses()%"
	kotovod_restrictors.rewrite_restrictor(res, custom, 10.0)
end

function red_forest_kill_restr()
	local res = g_sim:create("space_restrictor",vector():set(-135.3259,0.2873,-304.2229),6830,3239)
    local custom = "[logic]\nactive = sr_idle@work\n[sr_idle@work]\non_actor_inside = %=sak.red_kill_zone()%"
	kotovod_restrictors.rewrite_restrictor(res, custom, 15.0)
end

function x18_kill_restr()
	local res = g_sim:create("space_restrictor",vector():set(40.1262,-6.3599,-27.6872),7403,1142)
    local custom = "[logic]\nactive = sr_idle@work\n[sr_idle@work]\non_info = {+yan_labx16_switcher_primary_off} nil\non_actor_inside = %=sak.x18_kill_zone()%"
	kotovod_restrictors.rewrite_restrictor(res, custom, 10.0)
	set_value("x18_kill_restr", res.id)
end

function ros_kill_restr()
	local res = g_sim:create("space_restrictor",vector():set(-186.4515,5.7944,103.6908),29751,1324)
    local custom = "[logic]\nactive = sr_idle@work\n[sr_idle@work]\non_actor_inside = %=sak.ros_kill_zone()%"
	kotovod_restrictors.rewrite_restrictor(res, custom, 6.0)
	
	res = g_sim:create("space_restrictor",vector():set(47.4888,-0.2157,140.1440),67708,1308)
    custom = "[logic]\nactive = sr_idle@work\n[sr_idle@work]\non_actor_inside = %=sak.ros_kill_zone2()%"
	kotovod_restrictors.rewrite_restrictor(res, custom, 6.0)
end

function rad_greedys()
	local shape={shtype=0,radius=6.0,center={0,0.5,0}}
	amk_anoms.spawn_anomaly("greedy_zone",sak.v3f(498.4261,-49.7434,22.3555),1920,165835, shape, "static")
	amk_anoms.spawn_anomaly("greedy_zone",sak.v3f(498.4777,-50.3591,-11.2008),1920,165796, shape, "static")
	amk_anoms.spawn_anomaly("greedy_zone",sak.v3f(504.044,-50.006,10.531),1920,168238,shape,"static")
	
	shape = {shtype=0,radius=2.5,center={0,0.5,0}}
	amk_anoms.spawn_anomaly("greedy_zone",sak.v3f(506.7563,-50.0328,-2.0918),1901,209938, shape, "static")
	amk_anoms.spawn_anomaly("amk_zone_mosquito_bald_strong",sak.v3f(-153.8413,0.4049,-314.1360),3239,6006, shape, "static")
	amk_anoms.spawn_anomaly("amk_zone_mosquito_bald_strong",sak.v3f(-149.8607,0.5639,-309.2581),3239,6751, shape, "static")
	
	local res = g_sim:create("space_restrictor",vector():set(-161.71,-0.9,-318.46),5153,3237)
    local custom = "[logic]\nactive = sr_idle@work\n[sr_idle@work]\non_actor_inside = %=sak.red_kill_zone2()%"
	kotovod_restrictors.rewrite_restrictor(res, custom, 5.5)
end

function sanek_trade_res()
	local res = g_sim:create("space_restrictor",vector():set(1.1799,-6.8299,-28.1200),308719,1585)
    local custom = "[logic]\nactive = sr_idle\n[sr_idle]\non_actor_inside = %=sak_dialog.out_all_money% sr_idle@near\n[sr_idle@near]\non_actor_outside = %=sak_dialog.in_all_money% sr_idle"
	kotovod_restrictors.rewrite_restrictor(res, custom, 4.0)
	
	res = g_sim:create("space_restrictor",vector():set(109.9199,0.1000,73.1100),33034,1225)
	kotovod_restrictors.rewrite_restrictor(res, custom, 3.5)
end

function x18_botan_book_spawn()
	local t = {"x18_inventory_box", "x18_inventory_box_0002", "x18_inventory_box1"}
	local r = get_value("r_treas_items", 1)
	local box = server_obj(t[r])
	if box then
		misc.spawn_to("x18_botan_book",box)
	end
end

function bar_tp()
	local res = g_sim:create("space_restrictor",vector():set(62.7021,-0.0013,76.8490),29236,1240)
	local logic = "[logic]\nactive = sr_teleport\n[sr_teleport]\npoint1 = bar_sak_teleport_0001_exit_walk\nlook1 = bar_sak_teleport_0001_exit_look\ntimeout = 5\nbypass = sak.bar_tp_bypass()"
	kotovod_restrictors.rewrite_restrictor(res, logic, 21.0)
	
	res = g_sim:create("space_restrictor",vector():set(83.3692,-0.0014,115.5599),29686,1221)
	kotovod_restrictors.rewrite_restrictor(res, logic, 6.0)
end

function bar_rad()
	amk_anoms.spawn_anomaly("amk_zone_sakbuzz_strong",{x=234.8296,y=0.3217,z=-77.8983},1269,60017,{shtype=0,radius=1.6,center={0,0.2,0}},"static")
	amk_anoms.spawn_anomaly("amk_zone_sakbuzz_strong",{x=233.3265,y=0.9132,z=-75.2567},1269,59627,{shtype=0,radius=1,center={0,0.2,0}},"static")
end

function garb_lv_rad()
	amk_anoms.spawn_anomaly("zone_radioactive_weak",{x=-293.7174,y=12.4659,z=-214.4214},260,254,{shtype=0,radius=5.0,center={0,0.5,0}},"static")
end
-- Sn: на релизе убрать
function playboy_spawn_tuzla_nlc30()
	doc.add_playboy()
end

function restore_nlc30_static_items()
	if not get_value("nlc30_static_items_spawned", false) then
		amk.spawn_item("amk_zapiska", sak.v3f(-132.93, 11.04, -203.2), 629, 105467)
		amk.spawn_item("rad_document6", sak.v3f(-28.4, -0.26, -173.55), 676, 211656)
		amk.spawn_item("quest_case_02", sak.v3f(-150.2, 12.1, -198.2), 628, 88768)
		set_value("nlc30_static_items_spawned", true)
	end
	if not get_value("nlc30_agro_vss_spawned", false) then
		local obj = g_sim:story_object(story_ids.agr_inventory_box_sak)
		if obj then
			misc.spawn_to("wpn_vintorez_m1", obj)
			sak.obj_off_on(obj)
			set_value("nlc30_agro_vss_spawned", true)
		end
	end
end

function remove_dumenko_content()
	misc.release_by_name("dumenko")
end

function create_underground_safe_zones()
   local lab_safe_zones = get_value( "lab_safe_zones", {} )
   if #lab_safe_zones > 1 then return end
   
   local tbl_levels = {
       "l04u_labx18", 
	   "l08u_brainlab", 
	   "labx8", 
	   "labx10", 
       "warlab", 
	   "l10u_bunker", 
	   "l12u_control_monolith", 
	   "l12u_sarcofag"
   }
   
   for i = 1, MAX_OBJ_ID do
       local obj = g_sim:object( i )
       if obj and str_in_tab( obj.level_name, tbl_levels ) then
           local name = obj:name()
           if ( strpos( name, "_koster_", 1, true ) or strpos( name, "_candle_", 1, true ) ) and not strpos( name, "zone", 1, true ) then
				local radius = strpos( name, "_koster_", 1, true ) and 3.5 or 2.2

				local sr_obj = alife():create( "space_restrictor", obj.position, obj.m_level_vertex_id, obj.m_game_vertex_id )

				if sr_obj then	
					local unique_name = string.format( "safe_zone_%d", sr_obj.id )					
					sr_obj:set_name( unique_name )
					
					local custom = [=[
						[logic]
						active = sr_idle@wait
						[sr_idle@wait]
						on_actor_inside = sr_idle@inside %=undergrounds_hits.enable_sz_protection%
						[sr_idle@inside]
						on_actor_outside = sr_idle@wait %=undergrounds_hits.disable_sz_protection%
					]=]
				   
                   kotovod_restrictors.rewrite_restrictor( sr_obj, custom, radius )
                   
                   if not lab_safe_zones[ obj.level_name ] then
                       lab_safe_zones[ obj.level_name ] = {}
                   end
                   table.insert( lab_safe_zones[ obj.level_name ], sr_obj.id )
               end
           end
       end
   end
   set_value( "lab_safe_zones", lab_safe_zones )
end

function create_x8_safe_zone()
	local lab_safe_zones = get_value( "lab_safe_zones", {} )
	if #lab_safe_zones > 1 then return end	
	local sr_obj = alife():create( "space_restrictor", vector():set( 2.38, 9.26, 23.37 ), 4834, 3210 )		
	if sr_obj then 
		local custom = [=[
			[logic]
			active = sr_idle@wait
			[sr_idle@wait]
			on_actor_inside = sr_idle@inside %=undergrounds_hits.enable_sz_protection%
			[sr_idle@inside]
			on_actor_outside = sr_idle@wait %=undergrounds_hits.disable_sz_protection%
		]=]		
		kotovod_restrictors.rewrite_box_restrictor( sr_obj, custom, 50, 35, 9 )
        sr_obj.direction = sak.v3f( 0, 1.6, 0 )
		sr_obj:set_name( "safe_zone_x8_sleep" )
		table.insert( lab_safe_zones[ sr_obj.level_name ], sr_obj.id )		
	end
	set_value( "lab_safe_zones", lab_safe_zones )
end

function remove_petrenko_items()
	local items = { 22, 56, 57, 62, 63, 66 }
	for _, v in pairs( items ) do 
		local obj = g_sim:object( "bar_petrenko_item_" .. v )
		if obj then 
			misc.release_obj( obj )
		end
	end	
end

function give_yantar_room_lamp_info()
	if has_alife_info( "yantar_room_lamp_on" ) then return end
	if has_alife_info( "yantar_room_lamp_off" ) then return end
	db.actor:give_info_portion( "yantar_room_lamp_off" )
end

function create_esc_notebook()
	local old_note = g_sim:object( "physic_object0025" )
	if old_note then 
		misc.release_obj( old_note )
	end	
	local sobj = alife():create( "physic_object", sak.v3f( -245.128, -23.945, -133.611 ), 12442, 4 )
	if sobj then 
		local pk 		 = get_netpk( sobj, 1 )	
		local data 		 = pk:get()		
		data.physic_type = 3
		data.mass 		 = 10	
		data.visual_name = "equipments\\item_notebook"		
		data.custom_data = 
			"[collide]\n" ..
			"ignore_dynamic\nignore_ragdoll\nignore_static\n\n" .. 
			"[ph_heavy]\n" ..
			"[logic]\n" .. 
			"active = ph_idle@enable\n" ..
			"[ph_idle@enable]\n" ..			
			"tips = ui_mm_save\n" ..
			"on_use = %=s_fixes.save()%"
		pk:set( data )		
		sobj.direction = sak.v3f( 0, 0.871, 0 )
		sobj:set_name( "esc_notebook" )
	end
end

function save()
	_G.flag_can_save = true
	if get_value("blowout", 0) == 0 and _G.flag_can_save then
		local lname = level.name()
		local where = ( lname == "l01_escape" and "Бункер Сидоровича" ) or "Бункер Сахарова" 
		local bl_save = string.format( "День %s %s. %s [%s]", timers.Get_Game_Days(), level.get_time_hours(), level.get_time_minutes(), where )
		cmd("save", dsh.safe_file_name(bl_save))
	end	
end

-- Сюда надо будет добавлять те, которым не нужно показывать окно, например: тп в чащу из агро! 
-- Не забыть добавить все остальные по тп

local skip_lc = {
	[ "argu_teleport_aver" ] = true,
}

function fix_lc()
    for a = 1, MAX_OBJ_ID do
        local sobj = g_sim:object(a)
        if sobj and sobj:clsid() == clsid.level_changer then
            local name = sobj:name()
            if not skip_lc[name] then
                local pk = get_netpk(sobj)
                local data = pk:get()
                data.silent_mode = 0
                pk:set(data)
                -- sak.send_tip(name, "Изменили переход:", 0, 10, "nlc", "pda_news", "gray")
            end
        end
    end
end