function attach( sm )
	sm:subscribe({ signal = "on_safe_spawn",  fun = this.on_safe_spawn })
end

function on_safe_spawn()	
	if
		const.ground_levels[ level.name() ] -- наземные уровни	
	then
		ogse_signals.get_mgr():subscribe({ signal = "on_update_6sec", fun = this.on_upd_if_raining })
	end
end


function on_upd_if_raining()
	local rain_factor = level.rain_factor()
	if rain_factor <= 0.02 then return end 				
	local range = 10
	
	local RP = level.ray_query( db.actor:position(), vector():set( 0, 1, 0 ), 200, rq_target.rqtStatic, nil )
	if RP and RP.result then 
		range = RP.range 
	end
		
	if range <= 10 then return end 						
	if lua_random() < 0.3 then return end
	
	local armor = db.actor:item_in_slot( 6 )
	if not armor then return end
	
	if vergas_masks.get_flag_mask() == false then return end	
	
	local armor_custom = vergas_masks.set_get_armor_custom( 2 )
	if 
			not armor_custom 
		or armor_custom == "none|none|none" 
	then 
		return 
	end
	log2( "Mask condition is %s", tostring( armor_custom ) )
	local t = vergas_lib.str_explode( "|", armor_custom, true )
	local number_dirt_phase = tonumber( t[ 2 ] )
	number_dirt_phase = number_dirt_phase - lua_random( 2 )
	if number_dirt_phase < 1 then
		number_dirt_phase = 1
	end
	armor_custom = t[1].."|"..tostring( number_dirt_phase ).."|0"
	vergas_masks.set_get_armor_custom( 1, armor_custom )
end

