-- Идея частично взята из ДШ-мода

local snd_attach = sound_object( "interface\\inv_attach_addon" )
local snd_detach = sound_object( "interface\\inv_detach_addon" )

addons = {
	"wpn_addon_1pso",
	"wpn_addon_1p78",
	"wpn_addon_cobra",
	"wpn_addon_g36l",
	"wpn_addon_mt",
	"wpn_addon_acog",
	"wpn_addon_eotech",
	"wpn_addon_pe",
	"wpn_addon_po",
	-- new
	"9x39scope",
	"ac10632",
	"microt1",
	"specter",
	"okp", 
	"rakurs"	
}
	
function switch_addons()
    local active_slot = db.actor:active_slot()
    if not (active_slot == 1 or active_slot == 2) then return end
    
    if snd_attach:playing() or snd_detach:playing() then return end
    
    local wpn = db.actor:active_item()
    if not wpn then return end
    
    local wm = wpn:get_weapon_m()
    if not wm then return end
    
    local scope_status = ogse_wpn_utils.get_scope_status(wpn)
    if scope_status == 0 then
        --sak.send_tip("Это оружие не поддерживает прицелы", nil, 0, 5, "g_g", "no", "yellow")
        return
    end

    local has_scope = ogse_wpn_utils.get_scope_flag(wpn)
	
	if has_scope then 
		return detach_scope(wpn, wm) 
	else
		return attach_scope(wpn, wm)
	end	
end

function attach_scope(wpn, wm)
    local pouch_scope_id = get_value("pouch_addon_id")
    if not pouch_scope_id then return end
	
	-- Может нужна проверка, что вещь действительно у актора? 
    local scope = level.object_by_id( pouch_scope_id )
    if not scope then return end	
	
	local sect = scope:section()

    local scope_sections = get_string_wq(wpn:section(), "scope_names", nil)
    if not scope_sections then
        --sak.send_tip("Нет информации о совместимых прицелах", nil, 0, 5, "g_g", "no", "red")
        return
    end
    
	-- Через вергасовский str_explode не получилось, возвращало запятую и все
    if string.find(scope_sections, sect) == nil then
        --sak.send_tip("К этому оружию не подходит", nil, 0, 5, "g_g", "no", "red")
        return
    end
    
	local ascope = scope:get_inventory_item()
	wm:attach_addon(ascope, true)
	--sak.send_tip( string.format( "%s присоединили к %s", sect, wpn:section() ), nil, 0, 5, "g_g", "no", "green")
	snd_attach:play(db.actor, 0, sound_object.s2d)
	set_value("pouch_addon_id", nil)
	return true
end

function detach_scope(wpn, wm)
    local weapon = wpn:get_weapon()
    local scope_name = weapon.scope_name
    
    if not scope_name or scope_name == "" then
        --sak.send_tip("Прицел не установлен", nil, 0, 5, "g_g", "no", "yellow")
        return
    end
    
    snd_detach:play(db.actor, 0, sound_object.s2d)
    wm:detach_addon(scope_name, false)
   	local scope = misc.spawn_to( scope_name, db.actor ) 
	
    local pouch_content = razgruzka.load_pouch_content("ui_cheat_podsumok")
    
    if not pouch_content or type(pouch_content) ~= "userdata" then
        return
    end
    
    local item = pouch_content(1)
    if not item then return end
    
    -- Если секция не совпадает с именем прицела, помещаем в рюкзак
    if item.sect ~= "?" and item.sect ~= scope_name then
        --sak.send_tip( string.format( "%s помещен в рюкзак из-за %s", scope_name, item.sect ), nil, 0, 5, "g_g", "no", "blue")
        return
	end	
	
	-- Нужна запись в подсумок. Это не работает! Удалено
	--if item.sect == "?" then 
	--	ui_cheat_podsumok.pouch_dialog:add_to_pouch({ sect = scope_name, count = 1 })	
    --end
	
	if scope then 
		set_value("pouch_addon_id", scope.id )
		--sak.send_tip( string.format( "%s помещен в подсумок", scope_name ), nil, 0, 5, "g_g", "no", "sky_blue")	
	end
	return true
end