-- -*- mode: lua; coding: windows-1251-dos -*-

function attach( sm )
	sm:subscribe({ signal = "level_changer_action", fun = this.on_level_changer_action })
	sm:subscribe({ signal = "on_spawn",        		fun = this.on_spawn })
end

local already_added = {}

function on_spawn()
	local table_monsters_on_lc = get_value( "table_monsters_on_lc", {} )
	if not table_monsters_on_lc or next( table_monsters_on_lc ) == nil then
		return
	end
		
	log3( "table_monsters on spawn is %s", table_monsters_on_lc )
	
	local pos = db.actor:position()
	local gvd = db.actor:game_vertex_id()		
	local lvd = db.actor:level_vertex_id()	
	local stm = time_global()

	dsh.wait_condition(
		function() 
			local new_pos = db.actor:position()
			local dist = new_pos:distance_to( pos ) 
			return dist >= 9 or time_global() >= stm + 10000
		end,
		
		function()
			for k, v in pairs( table_monsters_on_lc ) do
				local obj = g_sim:object( v )
				if obj then 
					g_sim:set_switch_online( obj.id, true )				
					g_sim:teleport_object( obj.id, sak.v3f( pos.x, pos.y, pos.z ), lvd, gvd )	
				--	obj:clear_smart_terrain()
					sak.send_tip( obj:name(), "Teleported:", 1, 5, "g_g", "no", "red" )			
				--	local conds = {}
				--	conds[ "none" ] = xr_logic.parse_condlist( obj, "smart_terrains", "none", "true" )
				--	obj.smart_terrain_conditions = conds	
				
					local conds = obj.smart_terrain_conditions or {}
					conds["none"] = xr_logic.parse_condlist(obj, "smart_terrains", "none", "true")
					obj.smart_terrain_conditions = conds				
				
					level.client_spawn_manager():add(
						obj.id, -1,
						function( id, obj )
							fake_actor_hit( obj )
						end
					)					
					
					table_monsters_on_lc[ k ] = nil
					level.map_add_object_spot_ser(obj.id,"crlc_big_treasure3", obj:name() )	
				else
					log3("object %s not found, teleport skipped", tostring(v))
				end	
			end
			remove_value( "table_monsters_on_lc" )
			already_added = {}		
		end )
end


function on_level_changer_action( obj, wnd )
	--[[
	log3( "changed %s", obj:id() )
  dsh.exec_periodic(
    1000,
    function( timer )
      if not wnd:IsShown() then
			log3( "changed %s", obj:name() )
      end
    end
  )	
  ]]--
  
  
	local table_monsters_on_lc = {}
	local distance = has_alife_info( "time_night" ) and 20 or 45
	for k, v in pairs( db.creatures ) do
		local obj = level.object_by_id( k )
		if obj and IsMonster( obj ) and obj:alive() and obj.health > 0.3 and obj:position():distance_to_xz( db.actor:position() ) <= distance then
			log3( "obj_health %s", obj.health )
			local enemy = obj:get_enemy()
			if enemy and enemy:id() == db.actor:id() and obj:see( enemy ) then 
			--if obj:relation(db.actor) == game_object.enemy then
				if not already_added[ obj:id() ] then
					table.insert( table_monsters_on_lc, obj:id() )
					already_added[ obj:id() ] = true
				end
			end	
		end
	end
	log3( "table_monsters on add is %s", table_monsters_on_lc )
	set_value( "table_monsters_on_lc", table_monsters_on_lc )
end

function fake_actor_hit( obj )
    if not obj or not obj:alive() then return end

    obj:set_custom_panic_threshold( 0 )

    local h = hit()
    h.draftsman = db.actor
    h.direction = obj:position():sub(db.actor:position()):normalize()
    h.type = hit.fire_wound
    h.impulse = 0
    h.power = 0

    obj:hit(h)

    dsh_battle_radius.create_radius(obj, 10, nil, true)
end

function aaa()
    for a = 1, MAX_OBJ_ID do 
        local sobj = g_sim:object( a )
        if sobj and sobj:clsid() and sobj:clsid() == clsid.level_changer then 
            local pk     = get_netpk( sobj )
            local data     = pk:get()
            data.silent_mode = 0
            pk:set( data )
            -- sak.send_tip( sobj:name(), "Изменили переход:", 0, 10, "nlc", "pda_news", "gray" )
        end
    end
end