-- sivol_emp_sources.script
local sources = {}  -- [obj_id] = { pos = vector, active = bool, tier = table }

function register(obj_id, pos, active, tier)
    sources[obj_id] = { pos = pos, active = active, tier = tier }
end

function unregister(obj_id)
    sources[obj_id] = nil
end

function get_sources()
    return sources
end

function attach(sm)
    sm:subscribe({signal = "on_monster_death", fun = function(obj, who) sivol_emp_sources.unregister(obj:id()) end})
    sm:subscribe({signal = "on_monster_net_destroy", fun = function(obj) sivol_emp_sources.unregister(obj:id()) end})
end