local my_table  = ""
local new_index = nil
local tab_index = nil

table_kill_npc = {
	">>>>>>>>>> Мутанты <<<<<<<<<<",
	"monster",
	"poltergeist",
	"zombi",
	"gigant",
	"zombied",	
	">>>>>>>>>> Человеки <<<<<<<<<<",
	"stalker",
	"bandit",
	"monolith",
	"military",
	"freedom",
	"killer",
	"dolg",
	"ecolog",
	"tehnic",
}

table_community = {
	"stalker",
	"bandit",
	"military",
	"freedom",
	"dolg",
	"ecolog",
	"monolith",
	"killer",
}

table_translate = {
	[ "monster" 		] = "Монстры",
	[ "poltergeist" 	] = "Полтергейсты",
	[ "zombi" 			] = "Зомби",
	[ "gigant" 			] = "Гиганты",	
	[ "zombied" 		] = "Зомбированные",	
	[ "stalker" 		] = "Сталкеры",
	[ "bandit" 			] = "Бандиты",
	[ "monolith" 		] = "Монолитовцы",
	[ "military" 		] = "Военные",
	[ "freedom" 		] = "Свободовцы",
	[ "killer"			] = "Наёмники",	
	[ "dolg" 			] = "Долговцы",
	[ "ecolog"			] = "Учёные",
	[ "tehnic"			] = "Техника",
}

table_modificats = {
	"af_armor_1",
	"af_armor_2",
	"af_armor_3",
	"af_armor_4",
	"af_babka_1",
	"af_babka_2",
	"af_babka_3",
	"af_babka_4",
	"af_cry_1",
	"af_cry_2",
	"af_cry_3",
	"af_cry_4",
	"af_dik_1",
	"af_dik_2",
	"af_dik_3",
	"af_dik_4",
	"af_kol_1",
	"af_kol_2",
	"af_kol_3",
	"af_kol_4",
	"af_pudd_1",
	"af_pudd_2",
	"af_pudd_3",
	"af_pudd_4",
	"af_spirit_1",
	"af_spirit_2",
	"af_spirit_3",
	"af_spirit_4",
	"af_spirit_8",
}

table_spawn_npc = {
	"agr_bandit_respawn_1",
	"agr_bandit_respawn_2",
	"agr_soldier_regular",
	"agr_soldier_veteran",
	"agr_stalker_regular",
	"agr_stalker_veteran",
	"bar_dolg_respawn_1",
	"bar_dolg_respawn_2",
	"bar_dolg_respawn_3",
	"bar_stalker_respawn_1",
	"bar_stalker_respawn_2",
	"bar_stalker_respawn_3",
	"bar_stalker_respawn_4",
	"mar_provodnik_out",
	"cit_bandit_respawn_1",
	"cit_bandit_respawn_2",
	"cit_killer_respawn_1",
	"cit_killer_respawn_2",
	"cit_killer_respawn_3",
	"dolg_regular",
	"ds_bandit_respawn_1",
	"ds_bandit_respawn_2",
	"ds_bandit_respawn_3",
	"ds_stalker_respawn_1",
	"ds_stalker_respawn_2",
	"esc_bandit_respawn_1",
	"esc_bandit_respawn_2",
	"esc_green_respawn_1",
	"esc_green_respawn_2",
	"esc_green_respawn_3",
	"esc_green_respawn_4",
	"esc_green_respawn_5",
	"esc_soldier_respawn_1",
	"esc_soldier_respawn_specnaz",
	"esc_stalker_respawn_1",
	"esc_stalker_respawn_2",
	"gar_bandit_respawn_1",
	"gar_bandit_respawn_2",
	"gar_dolg_respawn_1",
	"gar_dolg_respawn_2",
	"gar_stalker_flame_quest23",
	"gar_stalker_respawn_1",
	"gar_stalker_respawn_2",
	"lost_vil_stalker_regular",
	"mil_freedom_barier_respawn_1",
	"mil_freedom_respawn_1",
	"mil_freedom_respawn_2",
	"mil_freedom_respawn_3",
	"mil_freedom_respawn_sniper",
	"mil_killer_respawn_1",
	"mil_killer_respawn_2",
	"mil_killer_respawn_3",
	"mil_killer_respawn_4",
	"mil_monolit_rush_respawn_1",
	"mil_neutral_barier_respawn_1",
	"mil_stalker_respawn_1",
	"mil_stalker_respawn_2",
	"mil_stalker_respawn_3",
	"new_killer_veteran1",
	"new_killer_veteran2",
	"new_killer_veteran3",
	"new_killer_veteran4",
	"new_killer_veteran5",
	"new_killer_veteran6",
	"new_killer_veteran7",
	"new_killer_veteran8",
	"new_killer_veteran9",
	"new_killer_veteran10",
	"new_killer_x12",
	"pri_monolith_respawn_1",
	"pri_monolith_respawn_2",
	"pri_monolith_respawn_3",
	"pri_respawn_dolg",
	"pri_respawn_freedom",
	"pri_respawn_military",
	"pri_respawn_neutral",
	"rad_freedom_respawn_1",
	"rad_freedom_respawn_2",
	"rad_freedom_respawn_3",
	"rad_monolith_respawn_1",
	"rad_monolith_respawn_2",
	"rad_monolith_respawn_3",
	"rad_soldier_master",
	"rad_specnaz_respawn_specnaz",
	"ros_bandit_respawn_2",
	"ros_bandit_respawn_3",
	"ros_bandit_respawn_4",
	"ros_killer_respawn_1",
	"ros_killer_respawn_2",
	"ros_killer_respawn_3",
	"ros_killer_respawn_4",
	"sar_monolith_respawn",
	"sim_freedom_master_quest",
	"stalker",
	"stalker_sakharov",
	"stalker_fresh_zombied",
	"trup_marsh_tuzla",
	"trup_stalker",
	"val_bandit_respawn_1",
	"val_bandit_respawn_2",
	"val_bandit_respawn_3",
	"val_bandit_respawn_4",
	"val_soldier_respawn_1",
	"yan_ecolog_respawn_1",
}

table_spawn_monsters = {
	"bloodsucker_weak",
	"bloodsucker_normal",
	"bloodsucker_strong",
	"bloodsucker_mil",
	"boar_weak",
	"boar_normal",
	"boar_strong",
	"burer_weak",
	"burer_normal",
	"burer_strong",
	"burer_hos",
	"burer_yan",
	"cat_weak",
	"cat_normal",
	"cat_strong",
	"chimera_weak",
	"chimera_normal",
	"chimera_strong",
	"electro_chimera",
	"m_controller_normal",
	"m_controller_old",
	"m_controller_old_fat",
	"controller_tubeman",
	"controller_new",
	"dog_weak",
	"dog_normal",
	"dog_strong",
	"dog_sak",
	"flesh_weak",
	"flesh_normal",
	"flesh_strong",
	"m_gigant_normal",
	"marsh_gigant",
	"gigant_normal",
	"gigant_strong",
	"karlik",
	"m_poltergeist_normal",
	"m_poltergeist_normal_tele",
	"m_poltergeist_tele_outdoor",
	"m_poltergeist_normal_flame",
	"m_poltergeist_strong_flame",
	"m_poltergeist_dark_flame",
	"pseudodog_weak",
	"pseudodog_normal",
	"pseudodog_strong",
	"psy_dog",
	"psy_dog_radar",
	"dogfrend",
	"rat_weak",
	"rat_normal",
	"rat_strong",
	"rat_mad_wery_strong",
	"snork_weak",
	"snork_normal",
	"snork_strong",
	"aes_snork",
	"snork_indoor",
	"snork_outdoor",
	"snork_jumper",
	"tushkano_normal",
	"tushkano_strong",
	"electro_tushkano_normal",
	"zombie_weak",
	"zombie_normal",
	"zombie_strong",
	"zombie_trup",
	"zombie_trup2",
	"zombie_blow",
	"zombie_beee",
	"rad_zombied_respawn_1",
	"rad_zombied_respawn_2",
	"rad_zombied_respawn_3",
	"yan_zombied_respawn_1",
	"yan_zombied_respawn_2",
	"yan_zombied_respawn_3",
	"yan_zombied_respawn_4",
	"yan_zombied_respawn_5",
	"yan_zombied_respawn_6",
	"amk_zombied_1",
	"amk_zombied_2",
	"amk_zombied_3",
}

table_items = {                            
	"belt_2_art",                              
	"belt_3_art",                             
	"belt_4_art",  
	"belt_5_art",  
	"belt_6_art", 
	"rucksack",
	"arc_art_box_basic",
	"arc_art_box_1basic",
	"arc_art_box_8basic",
	"sleeping_bag",
	"kanistra",
	"amk_kanistra",
	"flask_army",
}

table_ammo = {
	"ammo_9x18_fmj",
	"ammo_9x18_pmm",
	"ammo_9x19_fmj",
	"ammo_9x19_pbp",
	"ammo_5.45x39_fmj",
	"ammo_5.45x39_ap",
	"ammo_5.56x45_ss190",
	"ammo_5.56x45_ap",
	"ammo_12x70_buck",
	"ammo_12x76_zhekan",
	"ammo_12x76_dart",
	"ammo_9x39_sp5",
	"ammo_9x39_pab9",
	"ammo_9x39_ap",
	"ammo_8.6x70",
	"ammo_8.6x70_ap",
	"ammo_7.62x54r",
	"ammo_7.62x54_ap",
	"ammo_7.62x54_7h1",
	"ammo_7.62x54_7h14",
	"ammo_7.62x51_fmj",
	"ammo_7.62x51_ap",
	"ammo_7.62x39_fmj",
	"ammo_7.62x39_ap",
	"ammo_11.43x23_fmj",
	"ammo_11.43x23_hydro",
	"ammo_super_gauss",
	"ammo_gauss_oboima",
	"ammo_gauss",
	"grenade_rgd5",
	"grenade_gd-05",
	--"grenade_light",
	"ammo_og-7b",
	"ammo_vog-25p",
	"ammo_vog-25",
	"grenade_f1",
	"ammo_m209",
}


table_wpn = {
">>>>>>>>>> Пистолеты <<<<<<<<<<",
"wpn_aps",
"wpn_beretta",
"wpn_beretta93",
"wpn_colt1911",
"wpn_desert_eagle",
"wpn_eagle_m1",
"wpn_fort",
"wpn_fort_m1",
"wpn_gungauss",
"wpn_pb",
"wpn_pm",
"wpn_sig220",
"wpn_usp",

">>>>>>>>>> Пистолеты (Improved) <<<<<<<<<<",
"wpn_ak74_m3",
"wpn_glock",
"wpn_glock_m1",
"wpn_walther",

">>>>>>>>>> Пистолеты-пулемёты <<<<<<<<<<",
"wpn_bizon",
"wpn_mp5",
"wpn_mp5_m1",
"wpn_pp19",
"wpn_ump45",

">>>>>>>>>> Пистолеты-пулемёты (Improved) <<<<<<<<<<",
"wpn_glock_m2",
"wpn_mp5_m2",

">>>>>>>>>> Дробовики <<<<<<<<<<",
"wpn_bm16",
"wpn_bm16_full",
"wpn_mp133_full",
"wpn_mp153",
"wpn_mp153_m1",
"wpn_saiga12c",
"wpn_saiga12c_m1",
"wpn_spas12",
"wpn_spas12_m1",
"wpn_toz34",
"wpn_winchester_m1",

">>>>>>>>>> Дробовики (Improved) <<<<<<<<<<",
"wpn_hunters_toz_new",
"wpn_spas15",
"wpn_spas15_m1",
"wpn_toz34_m1",
"wpn_wincheaster1300",

">>>>>>>>>> Автоматы <<<<<<<<<<",
"wpn_abakan",
"wpn_ak47",
"wpn_ak74",
"wpn_ak74m",
"wpn_ak74u",
"wpn_akm",
"wpn_aks47",
"wpn_aks47_he",
"wpn_fn2000",
"wpn_g36",
"wpn_g36c",
"wpn_groza",
"wpn_rpk74",
"wpn_sig550",
"wpn_val",
"wpn_vintorez",
"wpn_vintorez_m1",

">>>>>>>>>> Автоматы (Improved) <<<<<<<<<<",
"wpn_aek971",
"wpn_ak104",
"wpn_ak108",
"wpn_ak74_m1",
"wpn_ak74_m2",
"wpn_groza_nimble",
"wpn_m16a4",
"wpn_saiga12c_m2",
"wpn_soc308",
"wpn_soc308_m1",
"wpn_val_nimble",

">>>>>>>>>> Автоматы (Hard Edition) <<<<<<<<<<",
"wpn_ak47_old",
"wpn_ak74_old",
"wpn_ak74pbn",
"wpn_ak74u_old",
"wpn_lr300",
"wpn_lr300_m1",

">>>>>>>>>> Снайперки <<<<<<<<<<",
"wpn_awm",
"wpn_m110",
"wpn_mosin",
"wpn_sv98",
"wpn_svd",
"wpn_svu",

">>>>>>>>>> Снайперки (Improved) <<<<<<<<<<",
"wpn_mr308",

">>>>>>>>>> Прочее <<<<<<<<<<",
"wpn_flame",
"wpn_gauss",
"wpn_gm94",
"wpn_knife",
"wpn_pkm",
"wpn_rpg7",

">>>>>>>>>> Прочее (Improved) <<<<<<<<<<",
"wpn_gauss_auto",
"wpn_pkp",
"wpn_rg6",
"wpn_rpk",

">>>>>>>>>> Прочее (Hard Edition) <<<<<<<<<<",
"wpn_knife_m1",
}

table_unique_arts = {
	">>>>>>>>>> Аккумуляторы <<<<<<<<<<",
	"af_full_akkum",
	"af_full_akkum_big",
	">>>>>>>>>> Уникальные <<<<<<<<<<",	
	"af_baloon",
	"af_compass", 
	"af_crist_new",
	"af_cristall",    
	"af_star_new",
	"af_life_heart",	
	"af_resonator",
	"af_medus_new",   
	"af_electra_blue_new",
	"af_electra_flash_new",
	"af_electra_moonlight_new",  
	"af_eye", 
	"af_flower_new",  
	"af_glass_new",
	"af_glassbeads", 	
	"af_dummy_simbion",
	"af_dummy_sparkler",	
	">>>>>>>>>> Капсулы <<<<<<<<<<",	
	"af_capsule",
	"af_capsule",
	"af_capsule",
	"af_capsule",
	"af_capsule",
	"af_capsule",
	"m_capsule",
	"m_capsule",
	"m_capsule",
	"m_capsule",
	"m_capsule",
	"m_capsule",
	">>>>>>>>>> Пустышки <<<<<<<<<<",		
	"af_dummy_battery", 
    "af_dummy_kolobok",
	"af_dummy_dummy", 	
	"af_dummy_glassbeads", 
	"af_dummy_pellicle",
	"af_dummy_spring",  	
	"af_dummy_black_tip",
	"af_dummy_buliz",  
	"af_dummy_dummy_new", 
	"af_dummy_fire",        
	"af_battery", 	
	"af_sul_new",		
	"af_ice", 
	">>>>>>>>>> Изумруды <<<<<<<<<<",		
	"af_dummy_green_blood",
	"af_dummy_green_medusa",
	"af_dummy_green_vyvert", 	
	">>>>>>>>>> Рубинки <<<<<<<<<<",		
	"af_red_dummy_battery",  
	"af_red_dummy_pellicle", 
	"af_red_dummy_spring",   
	"af_red_dummy_compass",	
	">>>>>>>>>> Маятники <<<<<<<<<<",	
	"af_mayatnik_chaes_new", 
	"af_mayatnik_les_new", 
	"af_mayatnik_radar_new", 
	"af_mayatnik_stadion_new", 
	"af_mayatnik_tesla_new", 
	"af_mayatnik_tuman_new", 
	">>>>>>>>>> Аномальные Образования <<<<<<<<<<",	
	"af_unknown_1_new",
	"af_unknown_2_new",
	"af_unknown_3_new",
	"af_unknown_4_new",
	"af_unknown_5_new",
	"af_unknown_6_new",
	"af_unknown_7_new",
	"af_unknown_8_new",
	"af_unknown_9_new",
	"af_unknown_10_new",
	"af_unknown_11_new",
	"af_unknown_12_new",
	"af_unknown_13_new",
	"af_unknown_14_new",
	"af_unknown_15_new",
	"af_unknown_16_new",
	"af_unknown_17_new",
	"af_unknown_18_new",
	"af_unknown_19_new",
	"af_unknown_20_new",
	"af_unknown_21_new",
	"af_unknown_22_new",
	"af_unknown_23_new",
	"af_unknown_24_new",
	"af_unknown_25_new",
	"af_unknown_26_new",	
	"af_unknown_27_new",
	"af_unknown_28_new",
	"af_unknown_29_new",
	"af_unknown_30_new",
	"af_unknown_31_new",
}

table_outfits = {
	"bandit_gaz_outfit_m1",
	"bandit_master_outfit",
	"bandit_master_outfit_gas",
	"bandit_master_outfit_m1",
	"bandit_outfit",
	"cs_heavy_outfit",
	"cs_light_outfit",
	"dolg_black_exoskeleton",
	"dolg_gaz_outfit_m1",
	"dolg_outfit",
	"dolg_scientific_outfit",
	"ecolog_outfit",
	"ecolog_outfit_m1",
	"exo_bandit_outfit",
	"exo_outfit",
	"freedom_scientific_outfit",
	"killer_blue_exoskeleton",
	"killer_gaz_outfit_m1",
	"killer_outfit",
	"merc_scientific_outfit",
	"militaryspec_outfit",
	"military_outfit",
	"monolit_exoskeleton",
	"monolit_gaz_outfit_m1",
	"monolit_outfit",
	"monolit_scientific_outfit",
	"neytral_gaz_outfit_m1",
	"neytral_gaz_outfit_m2",
	"neytral_novice_gaz_outfit_m1",
	"neytral_novice_outfit_m1",
	"novice_outfit",
	"outfit_bandit_m1",
	"outfit_dolg_m1",
	"outfit_exo_m1",
	"outfit_killer_m1",
	"outfit_novice_m1",
	"outfit_soldier_m1",
	"outfit_specnaz_m1",
	"outfit_stalker_m1",
	"outfit_stalker_m2",
	"outfit_svoboda_m1",
	"protection_outfit",	
	"scientific_outfit",
	"soldier_outfit",
	"specops_outfit",
	"stalker_guard_outfit",
	"stalker_outfit",
	"stalker_outfit_m3",
	"super_scientific_outfit",
	"svoboda_exoskeleton",
	"svoboda_gaz_outfit_m1",
	"svoboda_heavy_gaz_outfit_m1",
	"svoboda_heavy_outfit",
	"svoboda_light_outfit",	
	">>>>>>>>>> Укреплённая Броня <<<<<<<<<<",	
	"bandit_q_gaz_q_outfit_q_m1",
	"bandit_q_master_q_outfit",
	"bandit_q_master_q_outfit_q_gas",
	"bandit_q_master_q_outfit_q_m1",
	"bandit_q_outfit",
	"bandit_q_veteran_q_outfit",
	"bandit_q_veteran_q_outfit_q_gas",
	"bandit_q_veteran_q_outfit_q_m1",	
	"bandit_veteran_outfit",
	"bandit_veteran_outfit_gas",
	"bandit_veteran_outfit_m1",
	"broken_exoskeleton",
	"broken_q_exoskeleton",
	"cs_q_heavy_q_outfit",
	"cs_q_light_q_outfit",	
	"dolg_q_black_q_exoskeleton",
	"dolg_q_gaz_q_outfit_q_m1",
	"dolg_q_outfit",
	"dolg_q_scientific_q_outfit",	
	"ecolog_q_outfit",
	"ecolog_q_outfit_q_m1",
	"exo_q_bandit_q_outfit",
	"exo_q_outfit",
	"exo_q_outfit_q_m1",
	"freedom_q_scientific_q_outfit",	
	"killer_q_blue_q_exoskeleton",
	"killer_q_gaz_q_outfit_q_m1",
	"killer_q_outfit",
	"merc_q_scientific_q_outfit",
	"militaryspec_q_outfit",	
	"military_q_outfit",
	"monolit_q_exoskeleton",
	"monolit_q_gaz_q_outfit_q_m1",
	"monolit_q_outfit",
	"monolit_q_scientific_q_outfit",	
	"neytral_q_exo_q_antigas_q_outfit",
	"neytral_q_gaz_q_outfit_q_m1",
	"neytral_q_gaz_q_outfit_q_m2",
	"neytral_q_novice_q_gaz_q_outfit_q_m1",
	"neytral_q_novice_q_outfit_q_m1",
	"novice_q_outfit",	
	"outfit_q_bandit_q_m1",
	"outfit_q_dolg_q_m1",
	"outfit_q_exo_q_m1",
	"outfit_q_killer_q_m1",
	"outfit_q_novice_q_m1",
	"outfit_q_soldier_q_m1",
	"outfit_q_specnaz_q_m1",
	"outfit_q_stalker_q_m1",
	"outfit_q_stalker_q_m2",
	"outfit_q_svoboda_q_m1",
	"protection_q_outfit",
	"scientific_q_outfit",
	"soldier_q_outfit",
	"specops_q_outfit",		
	"stalker_q_guard_q_outfit",
	"stalker_q_outfit",
	"stalker_q_outfit_q_m3",	
	"svoboda_q_exoskeleton",
	"svoboda_q_gaz_q_outfit_q_m1",
	"svoboda_q_heavy_q_gaz_q_outfit_q_m1",
	"svoboda_q_heavy_q_outfit",
	"svoboda_q_light_q_outfit",
}

table_quest_items = {
	"razgruzka",
	"2bearer_cheque",    
	"bearer_cheque",                          
	"acid_banka",                    
	"agroprom_pda",  			
	"agr_black_box",  
	"agr_shema",                                                         
	"ara_pda",  				
	"aver_bandit_letter",  
	"bad_psy_helmet",  
	"ballon",   
	"banka",                                         
	"banka_full",                                 
	"bar_ecolog_flash",  
	"bar_lucky_pda",                                                   
	"bochonok_vine",  
	"borzyi_letter",  
	"box_ammo",  
	"box_conserv",  
	"bun_document",  
	"cherep_decoder",  
	"anagramm_flash",  			
	"computer",  					
	"dar_document1",  
	"dar_document2",  
	"dar_document3",  
	"dar_document4",  
	"dar_document5",  
	"dead_novice_letter",  
	"decoder",  	
	"decoder1",  			
	"decoder2",  			
	"diplomat",  			
	"docs_2_rad_psy",  
	"docs_for_borov",  
	"docs_rad_psy",  		                 
	"drunk_dolg_letter",  
	"dynamite",  
	"esc_bandit_letter",  
	"esc_wounded_flash",  
	"flamethrower_bad",  
	"flesh_leather",  			
	"fraer_pda",  			
	"freedoms_pda",
	"garbage_pda",  			
	"gar_bandit_letter",  
	"good_psy_helmet",  	
	"gunslinger_flash",  
	"hard_disc",  		 
	"instrument_box",  			
	"instrument_box_shurup",  
	"inventory_sakbox_01",  		
	"inventory_sakbox_02",  		
	"inventory_sakbox_03",  		
	"inventory_sakbox_04",  		
	"inventory_sakbox_04_lim",  
	"inventory_sakbox_05",  		
	"inventory_sakbox_bar",  
	"inventory_sakbox_borov",  
	"inventory_sakbox_dolg_petrenko",  
	"inventory_sakbox_gar_flame",  
	"inventory_sakbox_mil_skraga",  
	"inventory_sakbox_mil_svoboda",  
	"inventory_sakbox_rad",  
	"inventory_sakbox_repair_box",  
	"inventory_sakbox_yan_kruglov",  
	"item_battery_02",  			 
	"item_psi_helmet_01",  	
	"item_psi_helmet_02",  		
	"krujka_1",
	"krujka_2",
	"krujka_3",
	"krujka_4",
	"krujka_5",
	"krujka_6", 			
	"kartina04",  			
	"klava_feik",  
	"klyk_pribor_1c",  			
	"kruglov_flash",  
	"kruglov_letter",  			
	"kulinar_voron_box",  
	"lab_x16_documents",  
	"leshyi_letter",  
	"letter_for_borov",  		
	"marsh_document",  
	"marsh_inventory_box",  
	"marsh_pribor",  
	"marsh_tuzla_document",  
	"mar_ecolog_theory",  		 			
	"memory_module",
	"mil_kurjer_pda",
	"mil_rjaboi_letter",
	"mixture",
	"neum_drags",
	"noghost_letter",
	"note-book",			
	"paper_box",
	"pda_krysyka",			 			
	"personal_things",
	"postmens_bag",      
	"pri_doktor_documents",
	"quest_case_01",
	"quest_case_02",
	"quest_case_05",			
	"quest_case_06",			
	"quest_manycase_01",		
	"quest_manycase_01_ivancov",
	"quest_manycase_01_kruglov",
	"quest_manycase_01_mil_kurjer",
	"rad_cart",
	"rad_document6",			
	"rad_document7",			
	"rad_pda",				
	"rad_scaintist_doc",
	"rashpil_letter",
	"redcatcher_albom",
	"red_shtreck_letter",
	"resiept_activ_anom",
	"rygyi_med_r",
	"sak_book1",			
	"sak_book2",			
	"sak_book3",			
	"sak_book4",			
	"sak_document",			
	"sak_document2",			
	"sak_document3",
	"sak_document4",
	"sak_plan",			
	"sak_resiver",			
	"sak_resiver_yantar",		
	"same_quest_case",
	"scaintist_docs",			
	"scaintist_pda",			
	"scanner_anomaly",
	"scanner_artefact",
	"scarman_pda",
	"self_made_decoder",
	"solt_bag",
	"strelok_book1",
	"strelok_book2",		
	"strelok_sheets",
	"svoboda_letter",
	"uncoder",
	"und_pda",				
	"val_key_to_underground",		
	"vasiljev_letter",			
	"volkodav_pda",			
	"war_document",
	"weapon_box",			
	"x8_botan_book",
	"x8_document",
	"x10_document1",
	"x10_document2",
	"x16_flash",
	"x18_botan_book",
	"x18_door3_code",
	"x18_order_code",
	"yan_pda",				
	"zapiska_muller",			
	"zapiska_volk",
	"gorelka",
	"manometr",
	"trubka",
}

table_medkits = {
	">>>>>>>>>> Медицина <<<<<<<<<<",	
	"medkit",
	"medkit_army",	
	"medkit_scientic",
	"antirad",
	"bandage",	
	"dimedrol",	
	"flask_army",
	">>>>>>>>>> Провизия <<<<<<<<<<",		
	"bread",
	"kolbasa",
	"conserva",
	"green_kolbasa",
	"suhpay",
	"vodka",
	"energy_drink",	
	"matches",
	"zippo",
	"batt_torch",
	">>>>>>>>>> Ремки <<<<<<<<<<",		
	"repair_boxoutfit",
	"repair_item_outfit",
	"repair_item_weapon",
}

table_wpn_addons = {
	">>>>>>>>>> Прицелы <<<<<<<<<<",	
	"wpn_addon_1pso",
	"wpn_addon_1p78",
	"wpn_addon_cobra",
	"wpn_addon_g36l",
	"microt1",
	"wpn_addon_eotech",
	"wpn_addon_pe",
	"wpn_addon_po",
	"ac10632",
	"specter",
	"okp",
	"rakurs",
	"g28_scope",
	">>>>>>>>>> Подстволы <<<<<<<<<<",		
	"wpn_addon_grenade_launcher",
	"wpn_addon_grenade_launcher_m203",
	"wpn_addon_grenade_launcher_ag36",
	"wpn_addon_grenade_launcher_groza",
	">>>>>>>>>> Глушители <<<<<<<<<<",			
	"wpn_addon_sil_9_p",
	"wpn_addon_sil_545_ar",
	"wpn_addon_sil_556_ar",
	"wpn_addon_sil_762_ar",
	"wpn_addon_sil_762_sr1",
	"wpn_addon_sil_762_sr2",
	"wpn_addon_sil_mosin",	
	"wpn_addon_sil_45_p",
	"wpn_addon_sil_glock",
	"wpn_addon_sil_apb",
	"wpn_addon_sil_vsk",
	"wpn_addon_sil_co_salvo",
	"wpn_addon_sil_groza",
}

table_mutant_parts = {
	"mutant_face_tushkano",
	"mutant_dog_tail",	
	"mutant_boar_leg",
	"mutant_zombie_hand",	
	"mutant_flesh_eye",	
	"mutant_psevdodog_tail",	
	"mutant_tail_cat",	
	"mutant_snork_leg",	
	"mutant_burer_hand",
	"mutant_krovosos_jaw",	
	"mutant_chimera_kogot",
	"mutant_e_chimera_kidney",
	"mutant_hand_kontroler",
	"mutant_psevdogigant_hand",
	"mutant_poltergeist_glas",	
	"mutant_flesh_shkura",	
	"flesh_leather",
}

table_devices = {
	"wpn_binoc",
	"device_torch",
	"device_pda_npc",
	"detector_art",
	"detector_simple",
	"detector_advances",
	"detector_elite",
	"detector_sakbuzz_elite",
	"detector_sakbuzz_simple",
	"detector_sakbuzz_sak",
	"detector_elite_sak",
	"device_watch",
	"device_pda",
	"device_pda_upgraded",
	"nvd_bad",
	"nvd_good",
	"nvd_elite",
}

table_arts_dynamic = {
	">>>>>>>>>> Первый уровень <<<<<<<<<<",	
	"af_medusa",	
	"af_vyvert",
	"af_blood",	
	"af_drops",	
	"af_ameba_slime",	
	"af_rusty_thorn",	
	"af_electra_sparkler",
	">>>>>>>>>> Второй уровень <<<<<<<<<<",		
	"af_cristal_flower",	
	"af_gravi",	
	"af_mincer_meat",	
	"af_fireball",	
	"af_ameba_slug",
	"af_rusty_kristall",	
	"af_electra_flash",	
	">>>>>>>>>> Третий уровень <<<<<<<<<<",		
	"af_night_star",
	"af_gold_fish",
	"af_soul",	
	"af_cristall",
	"af_ameba_mica",	
	"af_rusty_sea_urchin",
	"af_electra_moonlight",
	">>>>>>>>>> Капсулы <<<<<<<<<<",	
	"af_capsule",
	"af_capsule",
	"af_capsule",
	"af_capsule",
	"af_capsule",
	"af_capsule",
	"af_capsule",	
}

local current_dyn = 3
---------------------------------------------------------
class "spawn_items_dialog" ( CUIScriptWnd )

function spawn_items_dialog:__init() super()
	if self.menu_index == nil then self.menu_index = 1 end
	local eng = [[qwertyuiop[]asdfghjkl;'zxcvbnm,./QWERTYUIOP{}ASDFGHJKL:"ZXCVBNM<>?!@#$%^&*()-_+=\| 0123456789]]
	local rus = [[йцукенгшщзхъфывапролджэячсмитьбюёЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ,!"№;%:?*()-_+=\/ 0123456789]]
	self.translit = {}
	for i = 1, string.len(rus) do
		self.translit[string.sub(eng, i, i)] = string.sub(rus, i, i)
	end	
	self.need_lang = false
	self.was_found = -1		
	self:InitControls()
	self:InitCallBacks()
end

function spawn_items_dialog:__finalize()	end

function spawn_items_dialog:InitControls()
	self:SetWndRect( Frect():set( 0, 0, 1024, 1024 ) )
	local xml = CScriptXmlInit()
	xml:ParseFile	( "ui_spawner.xml" )
	xml:InitStatic	( "background", self )	
	self.list = xml:InitList( "list", self )	
	self.list:ShowSelectedItem( true )
	
	self:Register( self.list, "list_window" )
	
	self:Update_DynArtefact( current_dyn )
	
	self:Register( xml:Init3tButton( "btn_item", 			self ),		"btn_item"			)
	self:Register( xml:Init3tButton( "btn_wpn", 			self ),		"btn_wpn"			)
	self:Register( xml:Init3tButton( "btn_addon", 			self ),		"btn_addon"			)
	self:Register( xml:Init3tButton( "btn_outf", 			self ),		"btn_outf"			)	
	self:Register( xml:Init3tButton( "btn_mp", 				self ),		"btn_mp"			)	
	self:Register( xml:Init3tButton( "btn_ammo", 			self ),		"btn_ammo"			)	
	self:Register( xml:Init3tButton( "btn_help", 			self ),		"btn_help"			)
	self:Register( xml:Init3tButton( "btn_quest", 			self ),		"btn_quest"			)
	self:Register( xml:Init3tButton( "btn_chess", 			self ),		"btn_chess"			)
	---------------------------------------------------------
	self:Register( xml:Init3tButton( "btn_dyn_arts", 		self ),		"btn_dyn_arts"		)
	self:Register( xml:Init3tButton( "btn_modificats",    	self ),		"btn_modificats"	)		
	self:Register( xml:Init3tButton( "btn_unique_art", 		self ),		"btn_unique_art"	)
	self:Register( xml:Init3tButton( "btn_infoportions", 	self ),		"btn_infoportions"	)	
	---------------------------------------------------------	
	self:Register( xml:Init3tButton( "btn_kill",      		self ),		"btn_kill"			)	
	self:Register( xml:Init3tButton( "btn_gg_com",    		self ),		"btn_gg_com"		)	
	self:Register( xml:Init3tButton( "btn_st", 				self ),		"btn_st"			)
	self:Register( xml:Init3tButton( "btn_mob", 			self ),		"btn_mob"			)
	self:Register( xml:Init3tButton( "btn_money", 			self ),		"btn_money"			)
	--self:Register( xml:Init3tButton( "btn_tp", 	    		self ),		"btn_tp"			)	
	
	self:Register( xml:Init3tButton( "btn_save", 			self ),		"btn_save"			)	
	-- self:Register( xml:Init3tButton( "btn_close", 		self ),		"btn_close"			)	

	------------------------
	self.lang = "RUS"
	self.btn_lang = CUIButton()
	self.btn_lang:Init( "ui\\ui_hud", 670, 635, 37, 25 )
	self.btn_lang:SetText( self.lang )
	self.btn_lang:SetTextAlign( CGameFont.alCenter )
	self.btn_lang:SetTextY( 1 )
	self.btn_lang:SetTextColor( 255,240,165,25 )
	self.btn_lang:SetOriginalRect( 65,704,37,25 )
	self:Register( self.btn_lang, "btn_lang" )
	self:AttachChild( self.btn_lang )	
	------------------------
	self.text = ""	
	self.edit_box = xml:InitEditBox( "frame_search",	self )	
	
	self.search = CUIStatic()
	self.search:SetWindowName("search")
	self.search:SetAutoDelete(true)
	self.search:SetText("Поиск")
	self.search:SetTextColor(255,200,255,200)
	self.search:SetFont(GetFontLetterica18Russian())
    self.search:Init(672,585,200,200)
    self:AttachChild(self.search)
	self:AddCallback("search", ui_events.WINDOW_LBUTTON_DB_CLICK, self.RemoveText, self)
	------------------------
	self.btn_find = CUIButton()
	self.btn_find:Init("ui\\ui_hud",720,635,45,25)
	self.btn_find:SetText("Найти")
	self.btn_find:SetTextAlign(CGameFont.alCenter)
	self.btn_find:SetTextY(1)
	self.btn_find:SetTextColor(255,240,165,25)
	self.btn_find:SetOriginalRect(65,704,37,25)
	self.btn_find:SetStretchTexture(true)
	self:Register(self.btn_find, "btn_find")
	self:AttachChild(self.btn_find)
	self:AddCallback("btn_find", ui_events.BUTTON_DOWN, self.SearchItem, self)
	---------------------------
	self.btn_spot = CUIButton()
	self.btn_spot:Init( "ui\\ui_hud", 770, 635, 45, 25 )
	self.btn_spot:SetText( "Метка" )
	self.btn_spot:SetTextAlign( CGameFont.alCenter )
	self.btn_spot:SetTextY( 1 )
	self.btn_spot:SetTextColor( 255, 240, 165, 25 )
	self.btn_spot:SetOriginalRect( 65, 704, 37, 25 )
	self.btn_spot:SetStretchTexture(true)
	self:Register( self.btn_spot, "btn_spot" )
	self:AttachChild( self.btn_spot )
	self:AddCallback( "btn_spot", ui_events.BUTTON_DOWN, self.MakeSpot, self )
	---------------------------
	xml:InitFrame( "frame_descr", self )
	self.cap_descr = CUIStatic()
	self.cap_descr:SetAutoDelete( true )
	self.cap_descr:SetFont( GetFontGraffiti19Russian() )
	self.cap_descr:Init( 25,58,70,25 )
    self:AttachChild( self.cap_descr )
	self.descr = xml:InitStatic( "descr_list", self )	
end


function spawn_items_dialog:InitCallBacks()
	self:AddCallback( "btn_item",	  		ui_events.BUTTON_CLICKED,					self.FillList_Items, 						self )
	self:AddCallback( "btn_wpn",	      	ui_events.BUTTON_CLICKED,					self.FillList_Wpns, 		    			self )
	self:AddCallback( "btn_addon",	  		ui_events.BUTTON_CLICKED,					self.FillList_Addns, 						self )
	self:AddCallback( "btn_outf",	  		ui_events.BUTTON_CLICKED,					self.FillList_Outfits, 						self )
	self:AddCallback( "btn_mp",	      		ui_events.BUTTON_CLICKED,					self.FillList_MutantParts, 		    		self )	
	self:AddCallback( "btn_ammo",	  		ui_events.BUTTON_CLICKED,					self.FillList_Ammo, 						self )
	self:AddCallback( "btn_help",	  		ui_events.BUTTON_CLICKED,					self.FillList_Medic, 						self )	
	self:AddCallback( "btn_quest",	  		ui_events.BUTTON_CLICKED,					self.FillList_Quest, 						self )
	self:AddCallback( "btn_chess",	  		ui_events.BUTTON_CLICKED,					self.FillList_Devices, 						self )
	---------------------------------------------------------
	self:AddCallback( "btn_dyn_arts",  		ui_events.BUTTON_CLICKED,					self.FillList_DynArtefacts, 				self )
	self:AddCallback( "btn_modificats",	  	ui_events.BUTTON_CLICKED,	   				self.FillList_Modificats,             		self )		
	self:AddCallback( "btn_unique_art",	    ui_events.BUTTON_CLICKED,					self.FillList_Unique, 		    			self )	
	self:AddCallback( "btn_infoportions",	ui_events.BUTTON_CLICKED,	   				self.FillList_Infoportions,         		self )		
	---------------------------------------------------------
	self:AddCallback( "btn_kill",	  		ui_events.BUTTON_CLICKED,	   				self.FillList_KillNPCs,             		self )		
	self:AddCallback( "btn_gg_com",	  		ui_events.BUTTON_CLICKED,	   				self.FillList_Community,             		self )
	self:AddCallback( "btn_st",	      		ui_events.BUTTON_CLICKED,					self.FillList_Stalkers, 		    		self )
	self:AddCallback( "btn_mob",	      	ui_events.BUTTON_CLICKED,					self.FillList_Monsters, 		    		self )	 
	self:AddCallback( "btn_money",	  		ui_events.BUTTON_CLICKED,					self.OnButton_rich_actor, 					self )	
	--self:AddCallback( "btn_tp",	      		ui_events.BUTTON_CLICKED,	   				self.Teleport,         				    	self )		
	---------------------------------------------------------	
	self:AddCallback( "btn_save",	  		ui_events.BUTTON_CLICKED,					self.OnButton_save_clicked,   				self )
	--self:AddCallback( "btn_close",	  	ui_events.BUTTON_CLICKED,		       		self.OnButton_close_clicked,    			self )
	self:AddCallback( "list_window",	  	ui_events.WINDOW_LBUTTON_DB_CLICK,			self.OnButton_create_clicked,           	self )	
	self:AddCallback( "list_window",		ui_events.LIST_ITEM_CLICKED, 				self.OnListItemClicked,						self )	
	self:AddCallback( "btn_lang", 			ui_events.BUTTON_DOWN, 						self.ClickBtnLang, 							self )	
		
end

---------------------------------------------------------
class "load_item" (CUIListItemEx)

function load_item:__init() super()
	self:SetWndRect		( 0, 0, 430, 22 )
	
	local ca = 255
	local cr = 255 -- 255
	local cg = 255 -- 234
	local cb = 255 -- 104
	
	self.fn					= CUIStatic()
	self.fn:SetAutoDelete	( true)
	self:AttachChild		( self.fn )
	self.fn:SetWndRect		( 0, 0, 230, 22 )
	self.fn:SetText			( "item" )
	self.fn:SetFont			( GetFontLetterica18Russian() )
	self.fn:SetTextColor	( ca, cr, cg, cb )
end

function spawn_items_dialog:OnTableNameFillList(table_name, type)
    my_table = table_name
    local list = self:GetListWnd("list_window")

    -- Сбрасываем индекс ДО очистки списка
    new_index = nil
    self.was_found = -1

    if list:GetSize() > 0 then
        list:SetFocusedItem(-1)  -- снимаем фокус перед очисткой
        list:RemoveAll()
    end

    spawn_type = tostring(type)
    self.tbl = table_name or {}

    for i = 1, #self.tbl do
        self:AddItemToList(self.tbl[i])
    end
end

-- Для предметов спавнящихся в рюкзак

function spawn_items_dialog:AddItemToList( sect )
	local list = self:GetListWnd( "list_window" )
	local ini = system_ini()
	local itm_name	
	if ini and ini:section_exist( sect ) and sect ~= "stalker" then
		if self.lang == "RUS" then 
			if strpos( sect, "_capsule" ) then
				itm_name = "Капсула артефакта " .. tostring( game.translate_string( string.gsub( sect, "_capsule", "_name" ) )	)
			else	
				-- itm_name = game.translate_string( read_if_exist( ini, sect, "inv_name", nil ) ) or sect
				itm_name = game.translate_string( read_if_exist_new( "s", ini, sect, "inv_name", nil ) ) or sect
			end	
		else
			itm_name = sect
		end	
	elseif string.find( sect, "^>" ) then 
		itm_name = sect			
	elseif spawn_type == "kill" or spawn_type == "community" then 
		itm_name = table_translate[ sect ]
	elseif spawn_type == "stalker" then 
		itm_name = sect
	else
		itm_name = "Секция \"".. sect .."\" отсутствует в игре!"
	end
	
	-- if string.len( itm_name ) > 50 then itm_name = string.sub(itm_name,1,48).."..." end 	-- Укоротим длинные названия
	
	if strpos( sect, "info_" ) then
		for k, v in pairs( sak_artmods.artmod_resiepts ) do
			for i = 1, #v do
				if v[ i ] == sect then
					itm_name = game.translate_string( sak_artmods.artmod_resiepts[ k ][ 7 ] )
				end
			end
		end
		for k, v in pairs( sak_artmods.amk_resiepts ) do
			for i = 1, #v do
				if v[ i ] == sect then
					itm_name = game.translate_string( sak_artmods.amk_resiepts[ k ][ 3 ] )		
				end
			end
		end
		for k, v in pairs( sak_artmods.unique_resiepts ) do
			for i = 1, #v do
				if v[ i ] == sect then   			
					itm_name = game.translate_string( sak_artmods.unique_resiepts[ k ][ 2 ] )			
				end
			end
		end						
    end	
	
	local _itm				= load_item()
	_itm.fn:SetText			( itm_name )
	list:AddItem		( _itm )
	
	if string.find( sect, "^>" ) then 
		_itm.fn:SetTextColor( 255, 40, 210, 43 )	
	end	
end

function spawn_items_dialog:FillList_Items()			self:OnTableNameFillList( table_items, 			"actor"  	)	end	
function spawn_items_dialog:FillList_Wpns()				self:OnTableNameFillList( table_wpn, 			"actor"  	)	end	
function spawn_items_dialog:FillList_Addns()			self:OnTableNameFillList( table_wpn_addons, 	"actor"  	)	end	
function spawn_items_dialog:FillList_Outfits()			self:OnTableNameFillList( table_outfits, 		"actor"  	)	end
function spawn_items_dialog:FillList_MutantParts()		self:OnTableNameFillList( table_mutant_parts, 	"actor"  	)	end
function spawn_items_dialog:FillList_Ammo()				self:OnTableNameFillList( table_ammo, 			"actor"  	)	end
function spawn_items_dialog:FillList_Medic()			self:OnTableNameFillList( table_medkits, 		"actor"  	)	end
function spawn_items_dialog:FillList_Quest()			self:OnTableNameFillList( table_quest_items, 	"actor"  	)	end
function spawn_items_dialog:FillList_Devices()			self:OnTableNameFillList( table_devices, 		"actor"  	)	end
function spawn_items_dialog:FillList_Modificats()		self:OnTableNameFillList( table_modificats, 	"actor"  	)	end		
function spawn_items_dialog:FillList_Unique()			self:OnTableNameFillList( table_unique_arts, 	"actor"  	)	end

function spawn_items_dialog:FillList_DynArtefacts()		self:OnTableNameFillList( table_arts_dynamic, 	"dynamic"   )	end		
function spawn_items_dialog:FillList_KillNPCs()			self:OnTableNameFillList( table_kill_npc, 		"kill" 		)	end
function spawn_items_dialog:FillList_Community()		self:OnTableNameFillList( table_community, 	 	"community" )	end	
function spawn_items_dialog:FillList_Monsters()			self:OnTableNameFillList( table_spawn_monsters, "stalker" 	)	end	
function spawn_items_dialog:FillList_Stalkers()			self:OnTableNameFillList( table_spawn_npc, 	 	"stalker" 	)	end	

--\\-- Возможен вылет при сборке поршней. В таком случае удалить содержимое all_article_disable, потом добавить в collect_info.ltx
-- flush !collect_info_portions.main(true)

function spawn_items_dialog:FillList_Infoportions()
	if self.owner.info_menu == nil then
		self.owner.info_menu = ui_info_menu.CUIInfoMenu()
		self.owner.info_menu.owner = self.owner
	end
	self:GetHolder():start_stop_menu( self.owner.info_menu, true )
	self:GetHolder():start_stop_menu( self, true )
	self.owner:Show( true )	
	-- this.init_cheat_table()	-- Включить сортировку секций при нажатии на поршень
end


function spawn_items_dialog:ClickBtnLang()
	self.lang = ( self.lang == "RUS" and "ENG" ) or "RUS"
	self.btn_lang:SetText( self.lang )
	self:OnTableNameFillList( my_table, "actor" )	
end

function make_static( name, own, text, x, y, width, height )
    local static = CUIStatic()
    static:SetWindowName( name )
    static:SetAutoDelete( true )
    if text then
        static:SetTextComplexMode( true )
        static:SetText( text )
    end
    static:Init( x, y, width, height )
    own:AttachChild( static )
    return static
end

function spawn_items_dialog:Update_DynArtefact( current_dyn )
	if self.dyn then self:DetachChild( self.dyn ) end
	self.dyn = make_static( "dyn", self, "".. current_dyn .."", 160, 638, 60, 60 )
	self.dyn:SetTextColor( 255, 20,  230,  40 )
	self.dyn:SetFont( GetFontGraffiti22Russian() )	
end

function spawn_items_dialog:OnListItemClicked()
    if self.list:GetSize() == 0 then return end
    local itm_index = self.list:GetSelectedItem()
    if itm_index < 0 then return end
    if not self.tbl or itm_index + 1 > #self.tbl then return end
    self.list:SetFocusedItem(itm_index)
    self:GetDescription(itm_index)
    new_index = itm_index
end

function spawn_items_dialog:OnButton_rich_actor()
	sak_dialog.relocate_money( db.actor, 10000, "in" )
	local snd = xr_sound.get_safe_sound_object([[device\decoder]])
	snd:play( db.actor, 0, sound_object.s2d )
end

function spawn_items_dialog:OnButton_create_clicked()
	local list = self:GetListWnd( "list_window" )	
	if list:GetSize() == 0 then return end	
	
	local itm_index		= list:GetSelectedItem()
	
	if new_index ~= nil then itm_index = new_index end

	if ( not itm_index ) or itm_index < 0 then return end	
	local item = self.tbl[ itm_index + 1 ]
	local ini = system_ini()
	
	if spawn_type == "actor" and item == "af_capsule" then
		nlc_capsules.give( nlc_capsules.random_regular( true ) )
		return
	elseif spawn_type == "actor" and item == "m_capsule" then
		nlc_capsules.give( nlc_capsules.random_mayatnik() )
		return
	elseif spawn_type == "actor" and not ( ini and ini:section_exist( item ) ) then return end	
	
	if alife() and db.actor:alive() then

		local pos = db.actor:position()
		local dir = db.actor:direction()
		------------------------------------------------------
        if spawn_type == "actor" then	
			if item == "flask_army" then 
				vergas_flask.create_water_flask( current_dyn or 5 )
			elseif item == "device_pda_npc" then 
				mike.add_pda_npc_amount( 1, math.min( math.max( current_dyn or 1, 1 ), 3 ) )
			else 
				sak.create_items( item, 1 )
			end	
		end
		------------------------------------------------------
		if spawn_type == "dynamic" then
			if string.find( item, "^>" ) then return end
			if current_dyn < 1 or current_dyn > 6 then current_dyn = 3 end
			sak.create_items( item .. "_dyn" .. current_dyn .. "d", 1 )	
		end		
		------------------------------------------------------
      	if spawn_type == "stalker" then
			pos = pos:add( dir:mul( 3 ) )
			local spawned = alife():create( item, pos, db.actor:level_vertex_id(), db.actor:game_vertex_id() )
			if IsMonster( spawned ) and current_dyn == 5 then 
				local part = utils.cfg_get_string( ini, item, "Spawn_Inventory_Item_Section", false, false, false, "" )			
				if part then 
					misc.spawn_to( part, spawned )
				end
			end	
        end
		------------------------------------------------------		
		if spawn_type == "info" then		
			db.actor:give_info_portion( item )	
			kotovod.sms_recipt_found( item )
        end		
		------------------------------------------------------		
		if spawn_type == "kill" then
			if str_in_tab( item, { "poltergeist", "zombi", "gigant", "zombied" } ) then 
				for id, obj in pairs( db.creatures ) do
					if g_sim:object( id ) then
						if obj and obj:alive() then 	
							if 
									( item == "poltergeist" and strpos( obj:section(), "m_poltergeist_", 1, true ) )
								or 	( item == "zombi" and strpos( obj:section(), "zombie_", 1, true ) )
								or  ( item == "gigant" and strpos( obj:section(), "gigant_", 1, true ) and obj:section() ~= "marsh_gigant" )
								or  ( item == "zombied" and strposx( obj:name(), "zombied" ) )
							then
								log2( "item is %s", item )
								obj:kill( db.actor )
							end	
						end
					end
				end	
			elseif item == "tehnic" then 
				for a = 1, MAX_OBJ_ID do
					local obj = g_sim:object( a )
					if obj then 
						local posobj 	= obj.position
						local actorpos 	= db.actor:position()	
						if posobj:distance_to( actorpos ) < 100 then	
							if obj:clsid() == 94 or obj:clsid() == 47 then  
								misc.release_obj( obj )
							end
						end
					end
				end	
			elseif str_in_tab( item, table_community ) then
				for id, obj in pairs( db.creatures ) do
					if g_sim:object( id ) and obj and obj:alive() and obj:is_stalker() then
						if obj:character_community() and strpos( obj:character_community(), item, 1, true ) then
							log2( "kill: %s -> %s (%s)", item, obj:name(), obj:section() )
							obj:kill( db.actor )
						end
					end	
				end
				
			else
				local to_kill = {}
				for id, obj in pairs( db.creatures ) do
					if obj and obj:alive() and obj:is_monster() then
						table.insert( to_kill, obj )
					end
				end
				for _, obj in ipairs( to_kill ) do
					obj:kill( db.actor )
				end
			end
		end
		------------------------------------------------------		
		if spawn_type == "community" then
			relation_registry.set_community_goodwill( item, db.actor:id(), 5000 )
		end  
		------------------------------------------------------		
	end
	local snd = xr_sound.get_safe_sound_object([[device\decoder]])
	snd:play( db.actor, 0, sound_object.s2d )
end


function spawn_items_dialog:OnButton_close_clicked()
	self:GetHolder():start_stop_menu( self, true )
	self.owner:Show( true )
	if level.present() and db.actor and db.actor:alive() then
		get_console():execute( "main_menu off" )
		ogse_signals.get_mgr():call("on_mm_return_game")	-- torch восстановление, мб потом еще что
	end
end

function spawn_items_dialog:OnButton_save_clicked()
	_G.flag_can_save = true
	if get_value("blowout", 0) == 0 and _G.flag_can_save then
		local bl_save = string.format( "День %s %s. %s [СПАВНЕР]", timers.Get_Game_Days(), level.get_time_hours(), level.get_time_minutes())
		cmd("save", dsh.safe_file_name(bl_save))
	end
	--	_G.flag_can_save = false

	--savemgmt.on_wakeup()	
	--schedule.add( "rename_cheat", "spawner.rename_cheat_save()", 200 )		
	-- local snd = xr_sound.get_safe_sound_object([[characters_voice\human_01\bandit\fight\cover_fire\cover_fire_6]])
	local snd = xr_sound.get_safe_sound_object([[device\decoder]])	
	snd:play( db.actor, 0, sound_object.s2d )	
end

function rename_cheat_save()
	local last_save = alife().save_name
	local fs = getFS()
	if fs:exist( "$game_saves$", last_save ) then    
		local file = string.sub( last_save, 1, string.len( last_save ) - 4 )
		local sg = CSavedGameWrapper( file )
		local lname = sg:level_name()            
		local y, m, d, h, min, sec, ms = 0, 0, 0, 0, 0, 0, 0
		y, m, d, h, min, sec, ms = sg:game_time():get( y, m, d, h, min, sec, ms )
		local start_month = 5
		local days = ui_load_dialog.GetDaysByMonth( m ) - ui_load_dialog.GetDaysByMonth( start_month ) + d    
       
		--local safe_lname = game.translate_string(lname):gsub('"', "'"):gsub('[<>:"/\\|?*]', ''):gsub('«', '"'):gsub('»', '"')
        local safe_lname = game.translate_string( lname )
            :gsub('«', '"')           	-- Заменяем открывающую ёлочку на обычную кавычку
            :gsub('»', '"')           	-- Заменяем закрывающую ёлочку на обычную кавычку
            :gsub('[<>:/\\|?*]', '')  	-- Удаляем недопустимые символы
            :gsub('%s+', ' ')         	-- Заменяем множественные пробелы на один
            :gsub('^%s*(.-)%s*$', '%1') -- Убираем пробелы в начале и конце
            :gsub('"', "'")           	-- Заменяем обычные кавычки на одинарные

        local new_save = string.format( "%s сутки %s - %s [Спавнер]", 
            days, 
            string.format( "%02u.%02u", h, min ), 
            safe_lname
        )
       
		WriteIni( db.stor_ltx, "stor", "last_save_name", new_save )
       
		local f1 = fs:update_path( "$game_saves$", last_save )
		local f2 = fs:update_path( "$game_saves$", new_save ..".sav" )
		fs:file_copy( f1, f2 )
		fs:file_delete( f1 )
		rename_saves.rename_dds_file( file, new_save )        
	end        
end

--\\ Поиск предметов --------------

function spawn_items_dialog:RemoveText()
	self.text = ""
	self.search:SetText( "_" )
	self.was_found = -1
end

function spawn_items_dialog:SearchText( letter ) 
	local lett = letter and ( self.lang == "RUS" and self.translit[ letter ] or letter ) or ""
	if lett == "%" then return end
	if string.len( self.text ) >= 40 then return end
	if string.len( self.text ) > 1 then self.text = string.sub( self.text, 1, -2 ) .. lett .. "_"
	else self.text = lett .. "_" end
	
	self.search:SetText( self.text )
end

function spawn_items_dialog:SearchItem()
	if self.text == "" then return end
	local size = self.list:GetSize()
	local search_text = string_lower( string.sub( self.text, 1, -2 ) )
	search_text = string.gsub( search_text, "-", " " )
	for i = 0, size - 1 do
		local item = self.list:GetItem( i )
		local item_text = string_lower( item.fn:GetText() )
		item_text = string.gsub( item_text, "-", " " )
		item_text = string.gsub( item_text, "ё", "е" )
		if #item_text >= #search_text and string.find( item_text, search_text ) then
			if self.was_found < i then
				self.was_found = i
				self.list:ScrollToPos( i )
				self.list:SetFocusedItem( i )
				self:GetDescription( i )
				break
			end
		end
	end
end

function spawn_items_dialog:BackSpace()
	if self.text ~= "" and string.len( self.text ) > 2 then
		self.text = string.sub( self.text, 1, -3 ) .. "_"
		self.search:SetText( self.text )
	else
		self.text = "_"
	end
	self.was_found = -1
	self.search:SetText( self.text )
end

function spawn_items_dialog:NavigateList( where )
	if not where then return end
	if spawn_type == nil then return end
	local size = self.list:GetSize()
	local index = self.list:GetFocusedItem()
	new_index = 0
	if where == "down" then
		if not index or index < 0 or index >= size - 1 then new_index = 0 else new_index = index + 1 end
	elseif where == "up" then
		if not index or index <= 0 or index > size - 1 then new_index = size - 1 else new_index = index - 1 end
	end
	self.list:SetFocusedItem( new_index )
	self.list:ScrollToPos( new_index ) 
	self:GetDescription( new_index )	
end

function spawn_items_dialog:ChangeButton( where )
	local buttons = {
		table_items,
		table_wpn, 		
		table_wpn_addons,
		table_outfits, 
		table_mutant_parts, 	
		table_ammo, 			
		table_medkits, 		
		table_quest_items, 
		table_devices, 		
		table_modificats, 
		table_unique_arts,
		table_arts_dynamic,
		table_kill_npc,
		table_community,
		table_spawn_monsters,
		table_spawn_npc
	}
	
	if tab_index == nil then tab_index = 1 end
	
	if where == "back" then 
		if buttons[ tab_index - 1 ] ~= nil then 
			tab_index = tab_index - 1 
		end
	end	 
	if where == "next" then 
		if buttons[ tab_index + 1 ] ~= nil then 
			tab_index = tab_index + 1 
		end
	end	
	
	local what = "actor"
	if 	   tab_index == 12 then what = "dynamic" 
	elseif tab_index == 13 then what = "kill"
	elseif tab_index == 14 then what = "community"
	elseif tab_index == 15 or tab_index == 16 then what = "stalker"
	end 
	
	local tbl = buttons[ tab_index ]

	self:OnTableNameFillList( tbl, what )
end

--\\-------------------------- Прочее

function spawn_items_dialog:MakeSpot()
    if self.text == "" then return end
    if self.lang == "RUS" then return end  -- Убрали сброс текста

    if not db.actor or not db.actor:alive() then return end

    local search_text = string_lower(string.sub(self.text, 1, -2))
    search_text = string.gsub(search_text, "-", " ")

    for a = 1, MAX_OBJ_ID do
        local obj = g_sim:object(a)
        if obj and obj.parent_id ~= 0 and strpos(obj:name(), search_text) then 
            local lname = "???"
            local gvid = obj.m_game_vertex_id
            if gvid ~= nil then 
                lname = game.translate_string(this.lname(gvid)) 
            end
            
            local ini = system_ini()
            -- Убедитесь, что sect определен
            local sect = obj:name()  -- или используйте подходящее значение для sect
            local rus = game.translate_string(read_if_exist_new("s", ini, sect, "inv_name", nil)) or obj:name()

            level.map_add_object_spot_ser(obj.id, "red_location", "".. rus .."")	
            timers.start_timer("del_diff_spots", 0, 0, 20, "spawner.remove_different_spots(".. obj.id ..")")	
            sak.send_tip(
                "Установлена метка на объект: ".. rus .." \\nУровень: ".. lname .." \\nавтоудаление через 20 минут", 
                nil, 1, 7, "g_g", "no", "green" 
            )					
        end	
    end	
end

function remove_different_spots( obj_id )
	local obj = g_sim:object( obj_id )
	if obj then 
		amk.remove_spot_from_map( obj.id, "red_location" )	
	end
end

function spawn_items_dialog:GetDescription( index )
	if not self.tbl or not self.tbl[index + 1] then return end
	local section = self.tbl[ index + 1 ]
	if string.find(section, "^>") then return end  -- заголовки пропускаем
	local sizes = give_icon_params( section )
	
	local px = 625 + ( 182 - ( sizes.width  * 0.26 * 1.2 ) )                       -- 0.26 для 1:1 на 1920
	local py = 58 + ( 128 - ( sizes.height * 0.32 * 1.2 ) )                        -- 0.32 для 1:1 на 1920
	local pw =  sizes.width * 0.52 * 1.2
	local ph = sizes.height * 0.64 * 1.2 
	
	if self.pict == nil then
		self.pict = CUIStatic()
		self.pict:SetWindowName("pict")
		self.pict:SetAutoDelete(true)
		self:AttachChild(self.pict)
	end
	
	local file
	if sizes.icon_group == 0 then
        file = "ui\\ui_icon_equipment"
	else
		file = "ui\\ui_icon_equipment_" .. sizes.icon_group
	end
			
	self.pict:InitTexture(file)
	self.pict:SetOriginalRect(sizes.x,sizes.y,sizes.width,sizes.height)
	self.pict:Init(px,py,pw,ph)
	self.pict:SetStretchTexture(true)
	
	local ini = system_ini()
    local description = "%c[255,255,0,0]"
    if ini:section_exist(section) then

        description = "Характеристики:"
        if ini:line_exist( section, "hit_power" ) then
            description = description .. "\\n %c[255,160,160,160]• убойность: "..math.round(ini:r_float(section, "hit_power")*100,1)
        end
        if ini:line_exist( section, "silencer_hit_power" ) then
            description = description .. "\\n %c[255,160,160,160]• убойность с глушителем: "..math.round(ini:r_float(section, "silencer_hit_power")*100,1)
        end
        if ini:line_exist( section, "fire_distance" ) then
            description = description .. "\\n %c[255,160,160,160]• дальность: "..ini:r_u32(section, "fire_distance")
        end
        if ini:line_exist( section, "silencer_fire_distance" ) then
            description = description .. "\\n %c[255,160,160,160]• дальность с глушителем: "..ini:r_u32( section, "silencer_fire_distance" )
        end
        if ini:line_exist( section, "rpm" ) then 
            description = description .. "\\n %c[255,160,160,160]• скорострельность: "..ini:r_u32( section, "rpm" )
        end
		if ini:line_exist( section, "cost" ) then
            description = description .. "\\n %c[255,160,160,160]• цена: "..ini:r_u32( section, "cost" )		
		end
		if ini:line_exist( section, "inv_weight" ) then
            description = description .. "\\n %c[255,160,160,160]• вес: "..ini:r_u32( section, "inv_weight" )		
		end		
    
		local infos = {
			{"burn", "           "},
			{"shock", "      "},
			{"strike", "           "},
			{"wound", "         "},
			{"radiation", "        "},
			{"telepatic", "       "},
			{"chemical_burn", "       "},
			{"explosion", "          "},
			{"fire_wound", "    "},
		}
		for _, item in ipairs( infos ) do
			if ini:line_exist( section, item[ 1 ] .. "_protection" ) then
				value = math.round( ini:r_float( section, item[ 1 ] .. "_protection" ) * 100 )
				if value > 0 then
					description = description.."\\n%c[255,255,255,255]"..game.translate_string("ui_inv_outfit_"..item[1].."_protection").."\t\t%c[255,1,255,1] "..value.."%"
				end
			end
		end
	
		if sizes.description ~= nil then 
			description = description .. "\\n" .. sizes.description
		else
			description = description.."\\n%c[255,255,255,255]Описание отсутствует"
		end		
	end
	
	if string.len( description ) >= 700 then description = string.sub( description, 1, 697 ) .. "..." end
	
	self.descr:SetText( description )
end

local sect_by_icon = {		-- иконки для сталкеров
	["esc_stalker_respawn_1"]="ui_npc_u_green_stalker_2",
	["bar_stalker_respawn_4"]="ui_npc_u_stalker_neytral_hood_uzor",
	["bar_stalker_respawn_1"]="ui_npc_u_stalker_neytral_nauchniy",
	["bar_stalker_respawn_2"]="ui_npc_u_stalker_neytral_exoskeleton",
	["bar_dolg_respawn_1"]="ui_npc_u_stalker_do_mask",
	["bar_dolg_respawn_2"]="ui_npc_u_stalker_do_nauchniy",
	["bar_dolg_respawn_3"]="ui_npc_u_stalker_do_exoskeleton",
	["mil_freedom_respawn_2"]="ui_npc_u_stalker_sv_rukzak_1_1",
	["mil_freedom_respawn_1"]="ui_npc_u_stalker_sv_hood_9",
	["pri_respawn_freedom"]="ui_npc_u_stalker_sv_exoskeleton",
	["gar_bandit_respawn_1"]="ui_npc_u_stalker_bandit_3",
	["gar_bandit_respawn_2"]="ui_npc_u_stalker_bandit_4",
	["ds_bandit_respawn_3"]="ui_npc_u_stalker_bandit_master",
	["cit_bandit_respawn_2"]="ui_npc_u_stalker_bandit_master",
	["ros_killer_respawn_3"]="ui_npc_u_stalker_ki_head_1",
	["ros_killer_respawn_2"]="ui_npc_u_stalker_ki_mask",
	["ros_killer_respawn_4"]="ui_npc_u_stalker_ki_exoskeleton",
	["pri_monolith_respawn_1"]="ui_npc_u_stalker_mo_head_1",
	["pri_monolith_respawn_2"]="ui_npc_u_stalker_mo_nauchniy",
	["mil_monolit_rush_respawn_1"]="ui_npc_u_stalker_mo_exo",
	["esc_soldier_respawn_1"]="ui_npc_u_soldier_bandana",
	["esc_soldier_respawn_specnaz"]="ui_npc_u_soldier_spetsnaz",
	["pri_respawn_military"]="ui_npc_u_stalker_militari_antigas_2",
	["rad_zombied_respawn_1"]="ui_npc_u_stalker_zombie1",
	["rad_zombied_respawn_2"]="ui_npc_u_stalker_zombie2",
	["rad_zombied_respawn_3"]="ui_npc_u_zombie_exoskeleton",
	["yan_ecolog_respawn_1"]="ui_npc_u_stalker_ecolog"
	}
	
	
function give_icon_params( sect )
	local ini = system_ini()
    local t = {}
	-------	
    if ini and ini:section_exist( sect ) then
		t.icon_group  = utils.cfg_get_number( ini, sect, "icon_group", nil, false, 0 )	
		t.description = game.translate_string( utils.cfg_get_string( ini, sect, "description", nil, false, "" ) )	
        t.width       = vergas_lib.set_pr_from_config( sect, "inv_grid_width"  ) * 50 or 176
        t.height      = vergas_lib.set_pr_from_config( sect, "inv_grid_height" ) * 50 or 78
        t.x           = vergas_lib.set_pr_from_config( sect, "inv_grid_x"      ) * 50 or 0
        t.y           = vergas_lib.set_pr_from_config( sect, "inv_grid_y"      ) * 50 or 0
    else
        t.description = ""
		t.icon_group  = 0
        t.width       = 176
        t.height      = 78
        t.x           = 0
        t.y           = 0
    end
    return t	
end

-------------------------------------------------
function string_lower( str )
	local low = [[qwertyuiopasdfghjklzxcvbnmйцукенгшщзхъфывапролджэячсмитьбюё]]
	local high = [[QWERTYUIOPASDFGHJKLZXCVBNMЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮЁ]]
	local low_str = ""
	for i = 1, #str do
		local letter = string.sub(str,i,i)
		for a = 1,#high do
			if letter == string.sub(high,a,a) then letter = string.sub(low,a,a) break end
		end
		low_str = low_str..letter
	end
	return low_str
end

function lname( num )
    local name = "???"
    for k, v in pairs( const.game_vertices ) do
        if num >= v[ 1 ] and num <= v[ 2 ] then
            name = k		
            break
        end
    end
	return name			
end

function read_if_exist_new( what, ini, section, name, def )
	if not ini then ini = system_ini() end
	if ini and ini:section_exist( section ) and ini:line_exist( section, name ) then
		if what == "f" then
			return ini:r_float( section, name )
		elseif what == "s" then
			return ini:r_string( section, name )
		elseif what == "b" then
			return ini:r_bool( section, name )
		end
	end
	return def
end

--\\--------------------------

function spawn_items_dialog:OnKeyboard(dik, keyboard_action)
	CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)
	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		if dik == DIK_keys.DIK_ESCAPE then self:OnButton_close_clicked()
		
		elseif dik == DIK_keys.DIK_1 or dik == DIK_keys.DIK_NUMPAD1 then current_dyn = 1 	self:Update_DynArtefact( current_dyn )
		elseif dik == DIK_keys.DIK_2 or dik == DIK_keys.DIK_NUMPAD2 then current_dyn = 2	self:Update_DynArtefact( current_dyn )
		elseif dik == DIK_keys.DIK_3 or dik == DIK_keys.DIK_NUMPAD3 then current_dyn = 3	self:Update_DynArtefact( current_dyn )
		elseif dik == DIK_keys.DIK_4 or dik == DIK_keys.DIK_NUMPAD4 then current_dyn = 4	self:Update_DynArtefact( current_dyn )
		elseif dik == DIK_keys.DIK_5 or dik == DIK_keys.DIK_NUMPAD5 then current_dyn = 5	self:Update_DynArtefact( current_dyn )
		elseif dik == DIK_keys.DIK_6 or dik == DIK_keys.DIK_NUMPAD6 then current_dyn = 6	self:Update_DynArtefact( current_dyn )
		-----------------
		elseif dik == DIK_keys.DIK_RETURN then self:OnButton_create_clicked()
		elseif dik == DIK_keys.DIK_TAB then self:SearchItem()
		elseif dik == DIK_keys.DIK_BACK then self:BackSpace()
		elseif dik == DIK_keys.DIK_DOWN then self:NavigateList("down")
		elseif dik == DIK_keys.DIK_UP then self:NavigateList("up")
		elseif dik == DIK_keys.DIK_LEFT then self:ChangeButton("back")
		elseif dik == DIK_keys.DIK_RIGHT then self:ChangeButton("next")		
		elseif dik == DIK_keys.DIK_LMENU then self.need_lang = true
		elseif dik == DIK_keys.DIK_LSHIFT and self.need_lang then self.need_lang = false self:ClickBtnLang()
		else
			self.need_lang = false
			local letter = string.sub( self.edit_box:GetText(), -1 )
			if letter and letter ~= "" then
				self:SearchText( letter )
				self.edit_box:SetText( "" )
			end
		end
	end
	return true
end

function main() end

--------------------------------------------------------
-- Телепорт по локациям

function spawn_items_dialog:Teleport()
	if level.present() and db.actor and db.actor:alive() then
		local obj =  alife():story_object( 987987 )				-- Удаляем прошлый чейнджер, если есть
		if obj then
			alife():release( obj, true )
		end
		self.teleportator_dialog = this.teleportator_menu()
		self.teleportator_dialog.owner = self
		self:GetHolder():start_stop_menu( self.teleportator_dialog, true )
		self:Show( true )
	end
end			

local points = {		
	{ level = "l03_agroprom",			name = "Тоннель",			    gv = 498,  	lv = 428829, 	x = 255.64,  	y = 0,      	z = 65.23	},
	{ level = "l03_agroprom",			name = "У Клыка",			    gv = 717,  	lv = 3327, 		x = -71.68,  	y = -6.87,      z = -70.97	},
	{ level = "l07_military",			name = "Лагерь нейтралов",		gv = 1710, 	lv = 213726, 	x = -96.58,  	y = -18.64, 	z = 212.17	},
	{ level = "l07_military",			name = "База Свободы",		    gv = 1593, 	lv = 286827, 	x = -20.56,  	y = -4.11,  	z = -23.96	},
	{ level = "l05_bar",		    	name = "Ангар у Бара",			gv = 1227, 	lv = 36082,  	x = 130.44,  	y = 0.1,    	z = 53.86	},
	{ level = "marsh",			    	name = "База ЧН",			    gv = 3374, 	lv = 65512,  	x = -157.31, 	y = 0.56,   	z = -315.09	},
	{ level = "l06_rostok",				name = "Переход в Бар",			gv = 1414, 	lv = 66990,  	x = 29.1,    	y = 1.24,   	z = 132.64	},
	{ level = "lost_village",			name = "Контрабандисты",		gv = 3329, 	lv = 15076,  	x = 5.41,    	y = 9.19,   	z = -73.77	},
	{ level = "generators",				name = "Переход в Лиманск",		gv = 3100, 	lv = 261568, 	x = -63.88,  	y = 33,     	z = -536.09	},		
	{ level = "deadcity",				name = "Переход в Тесла",		gv = 3844, 	lv = 241276, 	x = -68,     	y = 4.13,   	z = -191.69	},
	{ level = "l01_escape",				name = "Деревня новичков",		gv = 61,   	lv = 45931,  	x = -207.13, 	y = -20.59, 	z = -149.07	},
	{ level = "k01_darkscape",			name = "Ангар охотников",		gv = 4095, 	lv = 695029, 	x = 251.33,  	y = -0.36,  	z = -195.87	},
	{ level = "k01_darkscape",			name = "Северная стоянка",		gv = 3977, 	lv = 168532, 	x = -206.45,  	y = 3.46,  		z = 608.26	},
	{ level = "warlab",			    	name = "Радар - после х8",		gv = 3187, 	lv = 4317,   	x = -0.94,   	y = 1,      	z = 1.1		},	
	{ level = "labx8",			    	name = "Радар - Гармонизаторы",	gv = 3592, 	lv = 3041,   	x = -81.85,  	y = -16,    	z = 76.42	},
	{ level = "labx10",					name = "База Борова", 			gv = 3656, 	lv = 5925,   	x = -3.53,   	y = -7.45,  	z = -77.82	},
    { level = "l10u_bunker",			name = "Наёмники на Радаре",	gv = 2662, 	lv = 6862,   	x = 3.18,    	y = -7.45,  	z = -61.86	},		
	{ level = "l08u_brainlab",			name = "Начало",			    gv = 1542, 	lv = 7394, 		x = 140.29, 	y = 30.64, 		z = -15.56	},	
	{ level = "l08u_brainlab",			name = "У пролома",			    gv = 1529, 	lv = 489,    	x = -125.34, 	y = 18.76,  	z = -22.19	},	
	{ level = "l04u_labx18",			name = "Переход в ТД",			gv = 1109, 	lv = 2678,   	x = -0.51,   	y = 9.32,   	z = -10.27	},	
	{ level = "limansk", 				name = "У Михалыча",			gv = 2991, 	lv = 17444,  	x = -14.69,  	y = -5,     	z = -172.57	},	
	{ level = "av_peshera",				name = "Логово Стрелка",		gv = 2934, 	lv = 42980,  	x = -307.43, 	y = 42.47,  	z = 192.79	},
	{ level = "l03u_agr_underground",	name = "Переход на Агро",		gv = 725,  	lv = 4787,   	x = -38.47,  	y = -3.88,  	z = 19.52	},
	{ level = "l11_pripyat",			name = "Подземная автостоянка",	gv = 2226, 	lv = 211518, 	x = 107.06,  	y = -7.39,  	z = 9.62	},
	{ level = "l10_radar",				name = "Вагончик у леса",		gv = 2061, 	lv = 180293, 	x = 529.65,  	y = -49.1,  	z = -250.78	},	
	{ level = "red_forest",				name = "Переход на Янтарь",		gv = 3269, 	lv = 58306,  	x = -11.43,  	y = -0.4,   	z = -354.79	},	
	{ level = "red_forest",				name = "Шахта",					gv = 3240, 	lv = 8413,  	x = -125.46,  	y = -6.25,   	z = -42.87	},	
	{ level = "hospital",				name = "Лёха Старьёвщик",		gv = 3037, 	lv = 1745,   	x = -93.49,  	y = 33.96,  	z = 696.23	},	
	{ level = "l02_garbage",			name = "Руины около Долга",		gv = 258,  	lv = 165781, 	x = 104.36,  	y = 13.89,  	z = 174.03	},	
	{ level = "l04_darkvalley",			name = "Лагерь нейтралов",		gv = 836,  	lv = 37161,  	x = -120.34, 	y = 0.9,    	z = -535.94	},	
	{ level = "l04_darkvalley",			name = "Лагерь Борова",			gv = 1081,  lv = 224254,  	x = 40.03, 		y = 0.3,    	z = -71.07	},		
	{ level = "aver",			    	name = "Домик Доктора",			gv = 2889, 	lv = 263449, 	x = -352.11, 	y = -8.12,  	z = 8.89	},	
	{ level = "aver",			    	name = "Озеленение",			gv = 2902, 	lv = 1490256, 	x = 349.62, 	y = -6.20,  	z = -23.37	},		
	{ level = "l08_yantar",				name = "База учёных",			gv = 1479, 	lv = 51588,  	x = 25.85,   	y = -11.8,  	z = -301.72	},	
	{ level = "l12_stancia_new",    	name = "Тайник Стрелка",        gv = 4281, 	lv = 390872, 	x = 1017.82, 	y = -5.1,   	z = -74.99	},	
	{ level = "l12_stancia_2_new",  	name = "Переход с Генераторов", gv = 4401, 	lv = 223489, 	x = 382.65,  	y = -0.007, 	z = 81.82	},	
    { level = "l12u_sarcofag",			name = "У входа",			    gv = 2404, 	lv = 71,     	x = -29.02,  	y = 0.21,   	z = 34.35	},	
	{ level = "l12u_control_monolith", 	name = "Переход в ТЧ",       	gv = 2480, 	lv = 3907,   	x = 36.96,   	y = -34.48, 	z = 12.88	}
--	{ level = "",				    	name = "",			            gv = , 		lv = , 			x = , 			y = , 			z = 		},	
}



class "destination" (CUIListItemEx)

function destination:__init() super()
	self:SetWndRect(0,0,530,22)
	
	self.fn	= CUIStatic()
	self.fn:SetAutoDelete(true)
	self:AttachChild(self.fn)
	self.fn:SetWndRect(0,0,250,22)
	self.fn:SetFont(GetFontLetterica18Russian())
	self.fn:SetTextColor(255,216,186,140)

	self.pm	= CUIStatic()
	self.pm:SetAutoDelete(true)
	self:AttachChild(self.pm)
	self.pm:SetWndRect(250,0,130,22)
	self.pm:SetFont(GetFontLetterica18Russian())
	self.pm:SetTextColor(255,216,186,140)
end

class "teleportator_menu" (CUIScriptWnd)

function teleportator_menu:__init(owner,objid) super()
	self.targt = objid
	self.owner = owner

	self.point_id = {}

	self:InitControls()
	self:InitCallBacks()
	self:FillList()
end

function teleportator_menu:__finalize()
end

function teleportator_menu:FillList()
	local list_box = self:GetListWnd("list_window")
	local _itm, place
	for i = 1, #points do 			-- Сколько всего точек!
		place = points[ i ]
		_itm = destination()
		_itm.fn:SetText( game.translate_string( place.level ) )
		_itm.pm:SetText( tostring( place.name ) )
		list_box:AddItem(_itm )
		table.insert( self.point_id, i )
	end
end

function teleportator_menu:InitControls()
	self:Init(0,0,1024,768)
	
	-- файл-описатель наших элементов
	local ctrl
	local xml = CScriptXmlInit()
	xml:ParseFile("ui_mm_teleportator.xml")

	self.dialog	= xml:InitStatic("main_dialog:dialog", self)
	xml:InitStatic("main_dialog:capt", self.dialog)
	xml:InitStatic("main_dialog:msg1", self.dialog)
	xml:InitStatic("main_dialog:msg2", self.dialog)
	
	-- кнопки
	self:Register(xml:Init3tButton("main_dialog:btn_ok", self.dialog),"btn_ok")
	self:Register(xml:Init3tButton("main_dialog:btn_quit", self.dialog),"btn_quit")
	xml:InitFrame("main_dialog:list_frame", self.dialog)
	ctrl = xml:InitList("main_dialog:list", self.dialog)
	ctrl:ShowSelectedItem(true)
	self:Register(ctrl, "list_window")
end

function teleportator_menu:InitCallBacks()
	self:AddCallback("btn_ok", ui_events.BUTTON_CLICKED, self.on_ok, self)
	self:AddCallback("btn_quit", ui_events.BUTTON_CLICKED, self.on_quit, self)
	self:AddCallback("list_window", ui_events.WINDOW_LBUTTON_DB_CLICK, self.OnListItemDbClicked, self)
end

function teleportator_menu:OnKeyboard( dik, keyboard_action )
	CUIScriptWnd.OnKeyboard( self, dik, keyboard_action )
	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		if dik == DIK_keys.DIK_ESCAPE then
			self:on_quit()
		end
		if dik == DIK_keys.DIK_RETURN then
			self:on_ok()
		end
	end
	return true
end

function teleportator_menu:OnListItemDbClicked()
	self:on_ok()
end

function teleportator_menu:on_ok()
	local list = self:GetListWnd("list_window")	
	if list:GetSize()==0 then return end
	local index = list:GetSelectedItem()
	if index == -1 then return end
	local n = self.point_id[index+1]

	self:on_quit()
	this.create_level_changers(points[n].lv, points[n].gv, vector():set(points[n].x, points[n].y, points[n].z))
end

function teleportator_menu:on_quit()
	self:GetHolder():start_stop_menu(self, false)
	self.owner:Show (true)
	get_console():execute("main_menu off")
end

function remove_created_changer()
	local ch = get_value( "spawned_lc" )
	if not ch then return end
	local changer = g_sim:object( ch )
	if changer then 
		misc.release_obj( changer )
		remove_value( "spawned_lc" )
		sak.send_tip( 
			"Level Changer уже существует, поэтому был удален. Пересоздайте телепорт!", 
			nil, 0, 25, "stalker", "sak", "red"
		)
	end	
end

--// Спавн временного левел-чейнджера
function create_level_changers(
	p_dest_lv,										-- level_vertex_id   - идентифицируют уровень, на который level_changer будет перебрасывать игрока 
	p_dest_gv,										-- game_vertex_id
	p_dest_pos										-- координаты точки, в которой на новом уровне окажется игрок
	)
	-- следующие параметры убраны из аргументов, т.к. не меняются
	local p_story_id = 987987						-- STORY_ID нового level_changer (понадобится нам позже)
	local p_position = db.actor:position()			-- вектор, координаты точки, в которой будет располагаться центр нового level_changer
	local p_lvertex_id = db.actor:level_vertex_id()	-- level_vertext_id - идентифицируют уровень, на котором будет создан level_changer
	local p_gvertex_id = db.actor:game_vertex_id()	-- game_vertext_id   	
	local p_dest_dir = vector():set(0,0,0)			-- направрение взгляда игрока
	local p_dest_level = level.name()				-- название уровня, например "L11_Pripyat" (уровень НА КОТОРОМ создаётся ЛЧ, не назначения!)
	local p_silent = 1								-- следует задать 1, чтобы подавить вопрос о смене уровня (автоматический переход)

	this.remove_created_changer()

	local sim = alife()
	local obj = sim:create("level_changer", p_position, p_lvertex_id, p_gvertex_id)
	set_value( "spawned_lc", obj.id )
 
--	level.map_add_object_spot(obj.id, "level_changer", "")
 
	local packet = net_packet()
	obj:STATE_Write(packet)
 
	-- свойства cse_alife_object
	local game_vertex_id 				= packet:r_u16()
	local cse_alife_object__unk1_f32 	= packet:r_float()
	local cse_alife_object__unk2_u32 	= packet:r_u32()
	local level_vertex_id 				= packet:r_u32()
	local object_flags 					= packet:r_u32()
	local custom_data 					= packet:r_stringZ()
	local story_id 						= packet:r_u32()
	local spawn_story_id				= packet:r_u32()
 
	-- свойства cse_shape
	local shape_count 			= packet:r_u8()
	for i=1,shape_count do
		local shape_type 		= packet:r_u8()
		if shape_type == 0 then
			-- sphere
			local center 		= packet:r_vec3()
			local radius 		= packet:r_float()
		else
			-- box
			local axis_x_x = packet:r_float()
			local axis_x_y = packet:r_float()
			local axis_x_z = packet:r_float()
			local axis_y_x = packet:r_float()
			local axis_y_y = packet:r_float()
			local axis_y_z = packet:r_float()
			local axis_z_x = packet:r_float()
			local axis_z_y = packet:r_float()
			local axis_z_z = packet:r_float()
			local offset_x = packet:r_float()
			local offset_y = packet:r_float()
			local offset_z = packet:r_float()
		end
	end
 
	-- свойства cse_alife_space_restrictor
	local restrictor_type 			= packet:r_u8()
 
	-- свойства cse_level_changer
	local dest_game_vertex_id		= packet:r_u16()  
	local dest_level_vertex_id 		= packet:r_u32()  
	local dest_position 			= packet:r_vec3()
	local dest_direction 			= packet:r_vec3()
	local dest_level_name 			= packet:r_stringZ()
	local dest_graph_point 			= packet:r_stringZ()
	local silent_mode 				= packet:r_u8()
 
 
	packet:w_begin(game_vertex_id)			-- game_vertex_id
	packet:w_float(cse_alife_object__unk1_f32)
	packet:w_u32(cse_alife_object__unk2_u32) 
	packet:w_u32(level_vertex_id)			-- level_vertex_id
	packet:w_u32( bit_not(193) )			-- object_flags = -193 = 0xFFFFFF3E
	packet:w_stringZ(custom_data)
	packet:w_u32(p_story_id)				-- story_id
	packet:w_u32(spawn_story_id)
 
	packet:w_u8(1)			-- количество фигур
	packet:w_u8(1)			-- тип фигуры: box
	packet:w_float(50)	   	-- axis_x_x
	packet:w_float(0)	   	-- axis_x_y
	packet:w_float(0)	  	-- axis_x_z
	packet:w_float(0)	  	-- axis_y_x
	packet:w_float(50)	   	-- axis_y_y
	packet:w_float(0)	   	-- axis_y_z
	packet:w_float(0)	  	-- axis_z_x
	packet:w_float(0)	   	-- axis_z_y
	packet:w_float(50)	   	-- axis_z_z
	packet:w_float(0)	   	-- offset_x
	packet:w_float(0)	   	-- offset_y
	packet:w_float(0)      	-- offset_z
 
	packet:w_u8(3)	 	   	-- restrictor_type
 
	packet:w_u16(p_dest_gv)				-- destination game_vertex_id
	packet:w_s32(p_dest_lv)				-- destination level_vertex_id
	packet:w_vec3(p_dest_pos)			-- destination position
	packet:w_vec3(p_dest_dir)			-- destination direction (направление взгляда)
	packet:w_stringZ(p_dest_level)		-- destination level name
	packet:w_stringZ("start_actor_02")	-- some string, always const
	packet:w_u8(p_silent)				-- 1 for silent level changing
 
	packet:r_seek(0)
	obj:STATE_Read(packet, packet:w_tell())
	-- level.add_pp_effector ("teleport.ppe", 2006, false)			-- эффектор, если нужен
	timers.start_timer( "del_spawned_lc", 0, 0, 1, "spawner.del_lc()" )	
end

function del_lc()
	local ch = get_value( "spawned_lc" )
	if not ch then return end
	local changer = g_sim:object( ch )
	if changer then 
		sak.send_tip( changer:name(), "Удалён LC:", 0, 10, "g_g", "sak", "red" )		
		misc.release_obj( changer )		
		remove_value( "spawned_lc" )
	end	
end

--\\----------------- Сортировка секций

local index2type = {
	[1] = "weapons",
	[2] = "ammo",
	[3] = "addons",
	[4] = "outfits",
	[5] = "artefacts",
	[6] = "food_and_drugs",
	[7] = "items",
	[8] = "quest_items",
	[9] = "npc",
	[10] = "mobs",
	[11] = "anomalies",
	[12] = "junk"
}

function init_cheat_table()
	local cheat_list = {}
	local tmp = collect_sections.main()
	local name
	for i, v in ipairs(index2type) do
		local tbl = tmp[v]
		if tbl then
			local t = {}
			cheat_list[v] = t
			for j, sec in ipairs( tbl ) do
				if v == "npc" or v == "mobs" then
					name = sec
					if v == "npc" then
						local rank = sys_ini:line_exist( sec, "spec_rank" ) and sys_ini:r_string( sec, "spec_rank" )
						local community = sys_ini:line_exist( sec, "community" ) and sys_ini:r_string( sec, "community" )
						if community and rank then
							if community == "stalker" or community == "stranger" then
								community = "neutral"
							end
							name = community.."_"..rank
						end
					end
					name = game.translate_string( name )
					if sys_ini:line_exist( sec, "custom_data" )
						and sys_ini:r_string( sec, "custom_data" ) ~= "stalker_custom_data.ltx"
					then
						name = "! "..name
					end
					table.insert( t, { sec, name } )
				elseif v ==  "anomalies" then
					name = sec
					table.insert( t, { sec, name } )
				else
					table.insert( t, { sec, get_inv_name(sec,sec) } )
				end
			end
		end
	end
	this.sort_sections( cheat_list, 0 )
	return cheat_list
end

function sort_sections( list, mode )
	if mode then
		for k, t in pairs( list ) do
			table.sort( t, function( t1, t2 )
				if t1[2] == t2[2] or mode == 1 then
					return t1[1] < t2[1]
				else
					return t1[2] < t2[2]
				end
			end)
		end
	end
end

			
				--[[
				local tbl = {
					[ "poltergeist" ] = CLID_POLTERGEIST,
					[ "zombi"		] = CLID_ZOMBIE,
					[ "gigant"		] = CLID_GIGANT
				}
				for a = 1, MAX_OBJ_ID do
					local obj = g_sim:object( a )
					if obj and IsMonster( obj ) then
						local posobj 	= obj.position
						local actorpos 	= db.actor:position()	
						if posobj:distance_to( actorpos ) < 100 then
							if obj:clsid() == tbl[ item ] then  
								if obj and obj:alive() then
									obj = client_obj( obj.id )
									obj:kill( obj )
								end			
							end	
						end	
					end
				end	
				]]--