function generate_diary_table()
	local nums = { 17 }  -- ѕервым должно быть 17
	for i = 1, 16 do
		table.insert( nums, i )
	end

	-- "ѕеремешивание" массива, чтобы получить уникальные значени€, начина€ со второго элемента
	for i = 2, #nums do
		local j = lua_random( 2, #nums )
		nums[ i ], nums[ j ] = nums[ j ], nums[ i ]
	end
	set_value( "generated_diarys", nums )
end

function get_next_diary()
	local generated_diarys = get_value( "generated_diarys", {} )
    if #generated_diarys > 0 then
        local num = table.remove( generated_diarys, 1 )
		set_value( "generated_diarys", generated_diarys )
        return num
    end
end

function monster_killed( obj, who )
	local food = sak_dialog.table_food[ dsh.get_next_random( "arc_diary.monster_killed", #sak_dialog.table_food ) ]
	if food ~= "suhpay" then
		misc.spawn_to( food, obj )
	end

	local num = get_next_diary()
	if num then
		misc.spawn_to( "arc_diary_" .. num, obj )
	end

	obj:set_tip_text( monster_parts.get_tip_text( obj, monster_parts.has_knife() ) )
end

function on_get_diary( obj )
	local sect = obj:section()
	if not sect then return end
	local num = sect:match( "(%d+)$" )
	give_info( "kontroler_diary_info_" .. num )
	
	if dsh.get_next_random( "on_get_diary" ) <= 0.21 then
		if sak.level_difficulty[ level.name() ] > 1.2 then
			kotovod.modificat_recipes()
		else
			kotovod.thirdlvl_recipes()
		end
	end	
	if dsh.get_next_random( "on_get_diary" ) <= 0.33 then	
		-- TODO: потом поправить, пока вылетать будет
		-- kotovod.add_rnd_treasure()
	end	
	
	misc.release_obj( obj, true )	
	sak.send_tip( 
		" лочки бумаги, исписанные листочки, может интересное что?", 
		"«аписки", 0, 5, "g_g", "no", "sky_blue" 
	)		
end