--[[
Динамический худ v 4
Фляжки для мытья стекол противогаза 
Режим мытья стекол противогаза
Vergas
© NLC-6.0
]]--

class "cheat" (CUIScriptWnd)

local wnd_pocket        --ячейка чехла
local wnd_pic_pocket    --пиктограмма ячейки чехла
local info_chhl = {}    --информация для чехла (что лежит)

function cheat:__init(owner) 
    super()
    self.owner = owner
    self:InitControls()
    self:InitCallBacks()
end

function cheat:InitControls()
    -- Положение и размеры окна
    self:Init(248,0,528,414)
    -- файл-описатель элементов
    local xml = CScriptXmlInit()
    xml:ParseFile("ui_cheat_flask.xml")
    
    xml:InitStatic("background_0", self)         --Стекло
    xml:InitStatic("background_quickly", self)   --Собственно рамка
    
    self:Register(xml:Init3tButton("btn_stop_quickly", self),"btn_stop_quickly")  -- Кнопка Выкл
    self:Register(xml:Init3tButton("btn_wash_quickly", self),"btn_wash_quickly")  -- Кнопка Помыть
	self:Register(xml:Init3tButton("btn_drink_quickly", self),"btn_drink_quickly")	-- Кнопка пить воду	
end

function cheat:InitCallBacks()
    self:AddCallback("btn_stop_quickly", ui_events.BUTTON_CLICKED, self.btn_stop_quickly, self)  -- Кнопка Выкл
    self:AddCallback("btn_wash_quickly", ui_events.BUTTON_CLICKED, self.btn_wash_quickly, self)  -- Кнопка Помыть
	self:AddCallback("btn_drink_quickly", ui_events.BUTTON_CLICKED, self.btn_drink_quickly, self)   -- Кнопка пить воду	
    
    info_chhl = self:data_collection()
    self:init_win_pocket()
    if info_chhl[1] == "?" then
        self:set_wnd_pocket(1)
    else
        self:set_wnd_pocket(2)
    end
end

function cheat:OnKeyboard(dik, keyboard_action)
	CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)
	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		if dik == DIK_keys.DIK_ESCAPE then
			self:btn_stop_quickly()
		end
	end
	return true
end

function cheat:on_quit()
    info_chhl = {}  
    if wnd_pocket ~= nil then
        self:DetachChild(wnd_pocket)
        wnd_pocket = nil
    end
    if wnd_pic_pocket ~= nil then
        self:DetachChild(wnd_pic_pocket)
        wnd_pic_pocket = nil
    end
    used_items.set_get_flag_use_gadget(1,true)
    self:GetHolder():start_stop_menu (self,true)
    vergas_lib.s_play(vergas_lib.set_pr_from_config_str("bag_on_belt","snd_deselect"),1)
    bind_stalker.restore_weapon()
end

function cheat:on_work_quit()
    self:write_data()
    info_chhl = {}  
    if wnd_pocket ~= nil then
        self:DetachChild(wnd_pocket)
        wnd_pocket = nil
    end
    if wnd_pic_pocket ~= nil then
        self:DetachChild(wnd_pic_pocket)
        wnd_pic_pocket = nil
    end
    used_items.set_get_flag_use_gadget(1,true)
    self:GetHolder():start_stop_menu (self,true)
    vergas_lib.s_play(vergas_lib.set_pr_from_config_str("bag_on_belt","snd_deselect"),1)
end

function cheat:btn_stop_quickly()                    --Кнопка закрытия чехла
    self:on_quit()
end

function cheat:btn_wash_quickly()
	local flask = get_value( "equipped_flask", nil )	
	if flask == nil then
		sak.send_tip(
			"Етижи-пассатижи, так фляга-то отсутствует...", 
			"Мысли вслух", 0, 5, "g_g", "no", "red" 
		)		
		return 
	end 
    if info_chhl[1] ~= "?" then
        local new_water = vergas_flask.wash_glass( info_chhl[ 1 ] )
        if new_water then
            info_chhl[ 2 ] = new_water
            self:set_wnd_pocket( 2 )  -- Обновляем отображение фляжки
        end
        used_items.set_get_flag_use_gadget( 1, false )
    else
        vergas_lib.s_play("device\\masks\\water_no", 5)
    end
    self:write_data()
    self:on_work_quit()
end

function cheat:btn_drink_quickly()
	local flask = get_value( "equipped_flask", nil )	
	if flask == nil then
		sak.send_tip(
			"Етижи-пассатижи, так фляга-то отсутствует...", 
			"Мысли вслух", 0, 5, "g_g", "no", "red" 
		)		
		return 
	end 
    if info_chhl[1] ~= "?" then
        local new_water = vergas_flask.drink_water( info_chhl[ 1 ] )
        if new_water then
            info_chhl[ 2 ] = new_water
            self:set_wnd_pocket( 2 )  -- Обновляем отображение фляжки
        end
        used_items.set_get_flag_use_gadget( 1, false )
    else
        vergas_lib.s_play( "device\\masks\\water_no", 5 )
    end
    self:write_data()
    self:on_work_quit()
end

function cheat:init_win_pocket()
    if wnd_pocket ~= nil then
        self:DetachChild(wnd_pocket)
        wnd_pocket = nil
    end
    wnd_pocket = CUIStatic()
    wnd_pocket:SetAutoDelete(true)
    self:AttachChild(wnd_pocket)
    wnd_pocket:SetStretchTexture(true)
    if wnd_pic_pocket ~= nil then
        self:DetachChild(wnd_pic_pocket)
        wnd_pic_pocket = nil
    end
    wnd_pic_pocket = CUIStatic()
    wnd_pic_pocket:SetAutoDelete(true)
    self:AttachChild(wnd_pic_pocket)
    wnd_pic_pocket:SetStretchTexture(true)
    wnd_pic_pocket:SetWndRect(289,288,20,20)
end

function cheat:set_wnd_pocket(mode)
--mode = 2 - чехол с фляжкой
--mode = 1 - чехол без фляжки
    if mode == 1 then
        wnd_pocket:SetWndRect(214+16,281+13,68,63)
        wnd_pocket:InitTexture("ui_cover_without_flask")
        wnd_pic_pocket:Show(false)
    else
        wnd_pocket:SetWndRect(214+30,278+12,40,60)
        wnd_pocket:InitTexture("ui_flask_army")
        wnd_pic_pocket:InitTexture("ui_water_pictogram_"..(info_chhl[2] - 1))
        wnd_pic_pocket:Show(true)
    end
end

function cheat:data_collection()
    local tbl_ch = {}    -- фляжка в чехле
    
	local flask = get_value( "equipped_flask", nil )	
	if flask then	
        -- Пытаемся найти объект по ID
        local flask_obj = level.object_by_id( tonumber( flask ) )
        
        if flask_obj and flask_obj:section() == "flask_army" then
            -- Если объект существует и это фляга, заполняем данные
            tbl_ch[1] = tonumber( flask )
            tbl_ch[2] = get_flask_water(flask_obj)
        else
            -- Если объект не найден или не является флягой, сбрасываем equipped_flask
           remove_value( "equipped_flask" )
        end
    end
    
    if #tbl_ch == 0 then
        table.insert(tbl_ch, "?")
        table.insert(tbl_ch, 0)
    end
    
    return tbl_ch
end


function cheat:write_data()
    if info_chhl[1] ~= "?" then
        local obj = level.object_by_id(info_chhl[1])
        if obj and obj:section() == "flask_army" then
            set_flask_water(obj, info_chhl[2])
			set_value( "equipped_flask", info_chhl[1] )				
        else
            remove_value( "equipped_flask" )
        end
    else
        remove_value( "equipped_flask" )
    end
end

function get_flask_water(obj)
    local eat = obj:get_eatable_item()
    return eat.eat_portions_num
end

function set_flask_water( obj, amount )
	if not obj then return end
	if not amount then amount = 1 end
    local eat = obj:get_eatable_item()
	if eat then 	
		eat.eat_portions_num = amount
	end	
	vergas_flask.replace_flask_weight( obj.id, amount )
end
