--Меню настроек клавиатуры. Используется скриптом ui_mm_opt_main.script

local function register_hint(handler, control, id, caption, description)
	handler:Register(control, id)
	handler:AddCallback(id, ui_events.STATIC_FOCUS_RECEIVED, function()
		handler.hint_name:SetText(game.translate_string(caption))
		handler.hint_caption:SetText(game.translate_string(description))
	end)
end

class "opt_controls" (CUIWindow)
function opt_controls:__init() super()
end

function opt_controls:__finalize()
end

function opt_controls:InitControls(x, y, xml, handler)
	self:Init(x, y, 738, 416)
	self:SetAutoDelete(true)

	xml:InitFrame("frame", self)
	local section_mouse = xml:InitLabel("tab_controls:section_mouse", self)
	register_hint(handler, section_mouse, "controls_section_mouse", "ui_mm_section_controls_mouse", "ui_mm_section_controls_mouse_desc")

	local cap_mousesens = xml:InitStatic("tab_controls:cap_mousesens", self)
	local mouse_invert = xml:InitCheck("tab_controls:check_mouseinvert", self)
	xml:InitLabel("tab_controls:cap_keyboardsetup", self)
	xml:InitTrackBar("tab_controls:track_mousesens", self)
	xml:InitKeyBinding("tab_controls:key_binding", self)

	register_hint(handler, cap_mousesens, "controls_cap_mousesens", "ui_mm_mouse_sense", "ui_mm_mouse_sense_desc")
	register_hint(handler, mouse_invert, "controls_mouse_invert", "ui_mm_invert_mouse", "ui_mm_invert_mouse_desc")

	local btn = xml:Init3tButton("tab_controls:btn_default", self)
	handler:Register(btn, "btn_keyb_default")
end