-- Меню расширенных настроек графики для OGSR Engine
-- Глобальная переделка xrSimpodin (c) 2023

local hint_colors = {
	["green"]  = { 255, 0, 128, 0 },
	["yellow"] = { 255, 186, 149, 0 },
	["red"]    = { 255, 255, 0, 0 },
}

local adv_vid_opt_params = {
	{ section = "ui_mm_section_camera_view" },
	{ "fov",                    "track", 0, hint_colors.green , "ui_mm_fov", "video_settings_desc_61" },
	{ "hud_fov",                "track", 0, hint_colors.green , "ui_mm_hud_fov", "video_settings_desc_62" },
	{ "3dss_scale_factor",      "track", 0, hint_colors.yellow, "ui_mm_3dss_scale_factor", "video_settings_desc_69" },
	{ "cam_inert",              "track", 0, hint_colors.green , "ui_mm_cam_inert", "ui_mm_cam_inert_desc" },
	{ "dof_reload",             "check", 0, hint_colors.green , "ui_mm_r2_reload_dof", "video_settings_desc_41" },
	{ "dof_zoom",               "check", 0, hint_colors.green , "ui_mm_r2_zoom_dof", "video_settings_desc_42" },
	{ "dof_zoom_param",         "track", 0, hint_colors.green , "ui_mm_dof_zoom_param", "ui_mm_dof_zoom_param_desc" },
	{ "mblur",                  "check", 0, hint_colors.green , "ui_mm_mblur", "video_settings_desc_1" },
	{ "mblur_param",            "track", 0, hint_colors.green , "ui_mm_mblur_param", "ui_mm_mblur_param_desc" },

	{ section = "ui_mm_section_aa_sharpening" },
	{ "aa",                     "list",  0, hint_colors.green , "ui_mm_r_aa_mode", "video_settings_desc_19" },
	{ "cas",                    "track", 0, hint_colors.green , "ui_mm_cas", "ui_mm_cas_desc" },

	{ section = "ui_mm_section_world_detail" },
	{ "vis_dist",               "track", 0, hint_colors.yellow, "ui_mm_vis_distance", "video_settings_desc_2" },
	{ "geometry_lod",           "track", 0, hint_colors.yellow, "ui_mm_geometry_lod", "video_settings_desc_3" },
	{ "detail_density",         "track", 0, hint_colors.red   , "ui_mm_detail_density", "video_settings_desc_4" },
	{ "detail_distance",        "track", 0, hint_colors.red   , "ui_mm_detail_distance", "video_settings_desc_5" },
	{ "detail_scale",           "track", 0, hint_colors.yellow, "ui_mm_detail_scale", "ui_mm_detail_scale_desc" },
	{ "r2_steep_parallax",      "check", 0, hint_colors.yellow, "ui_mm_r2_steep_parallax", "video_settings_desc_39" },

	{ section = "ui_mm_section_lighting_shadows" },
	{ "r__smap_size",           "list",  1, hint_colors.red   , "ui_mm_r__smap_size", "video_settings_desc_59" },
	{ "r2_sun_quality",         "list",  0, hint_colors.red   , "ui_mm_r2_sun_quality", "ui_mm_r2_sun_quality_desc" },
	{ "sun_shafts",             "list",  0, hint_colors.yellow, "ui_mm_r2_sunshafts_mode", "video_settings_desc_29" },
	{ "r2_sun_details",         "check", 0, hint_colors.red   , "ui_mm_r2_sun_details", "video_settings_desc_12" },
	{ "r2_actor_shadow",        "check", 0, hint_colors.green , "ui_mm_r2_actor_shadow", "ui_mm_r2_actor_shadow_desc" },
	{ "ao_mode",                "list",  0, hint_colors.red   , "ui_mm_ao_mode", "video_settings_desc_38" },
	{ "ssao",                   "list",  0, hint_colors.red   , "ui_mm_ssao", "video_settings_desc_37" },

	{ section = "ui_mm_section_weather_effects" },
	{ "r3_dynamic_wet_surfaces", "check", 0, hint_colors.yellow, "ui_mm_r3_dynamic_wet_surfaces", "video_settings_desc_49" },
	{ "r_sslr_enable",          "check", 1, hint_colors.red   , "ui_mm_r_sslr_enable", "video_settings_desc_51" },
	{ "lens_flare",             "check", 0, hint_colors.green , "ui_mm_lens_flare", "ui_mm_lens_flare_desc" },
	{ "r2_mask",                "check", 0, hint_colors.green , "ui_mm_r2_mask", "video_settings_desc_66" },
	{ "r2_visor_refl",          "check", 0, hint_colors.green , "ui_mm_r2_visor_refl", "ui_mm_r2_visor_refl_desc" },
	{ "r2_rain_drops",          "check", 0, hint_colors.green , "ui_mm_r2_rain_drops", "video_settings_desc_47" },
	{ "r3_volumetric_smoke",    "check", 0, hint_colors.green , "ui_mm_r3_volumetric_smoke", "video_settings_desc_55" },

	{ section = "ui_mm_section_performance_system" },
	{ "tessellation",           "check", 1, hint_colors.red   , "ui_mm_r4_enable_tessellation", "video_settings_desc_52" },
	{ "vsync",                  "check", 0, hint_colors.green , "ui_mm_vsync", "video_settings_desc_16" },
	{ "mt_texload",             "check", 0, hint_colors.green , "ui_mm_mt_texload", "ui_mm_mt_texload_desc" },
}
local control_init_funs = {
	["track"] = "InitTrackBar",
	["list"]  = "InitComboBox",
	["check"] = "InitCheck",
}


class "opt_video_adv" (CUIWindow)
function opt_video_adv:__init() super()
end

function opt_video_adv:__finalize()
	--log1("--opt_video_adv:__finalize() called!")
end

function opt_video_adv:InitControls(x, y, xml, handler)
	self:Init(x, y, 738, 416)
	self:SetAutoDelete(true)

	xml:InitFrame("frame", self)
	self.scroll_v = xml:InitScrollView("video_adv:scroll_v", self)

	-- перебираем с конца, поскольку в настройках scroll view в xml стоит параметр flip_vert="1",
	-- который инвертирует порядок элементов, что в свою очередь сделано для того, чтобы визуально первые элементы
	-- добавлялись последними, что в свою очередь позволяет раскрывающимся спискам перекрывать элементы, расположенные ниже по списку
	for i = #adv_vid_opt_params, 1, -1 do
		local row = adv_vid_opt_params[i]
		if row.section then
			local section_id = row.section
			local _st = xml:InitLabel("video_adv:templ_section", self.scroll_v)
			_st:SetText(game.translate_string(section_id))
			handler:Register(_st, "video_adv_section_"..section_id)
			handler:AddCallback("video_adv_section_"..section_id, ui_events.STATIC_FOCUS_RECEIVED, function()
				handler.hint_name:SetText(game.translate_string(section_id))
				handler.hint_caption:SetText(game.translate_string(section_id.."_desc"))
			end)
		else
			local opt, ctr_type, need_restart, color, hint_caption, hint_string, cond = unpack(row)
			local enabled = not cond or cond()

			local _st = xml:InitStatic("video_adv:templ_item", self.scroll_v)
			local _st2 = xml:InitStatic("video_adv:cap_"..opt, _st)
			local ctl = xml[control_init_funs[ctr_type]](xml, "video_adv:"..ctr_type.."_"..opt, _st)

			if color and enabled then
				_st2:SetTextColor(unpack(color))
			end

			handler:Register(_st, "video_adv_cap_"..opt)
			handler:AddCallback(
				"video_adv_cap_"..opt,
				ui_events.STATIC_FOCUS_RECEIVED,
				function()
					handler.hint_name:SetText(hint_caption and game.translate_string(hint_caption) or "")
					handler.hint_caption:SetText(hint_string and game.translate_string(hint_string) or "")
				end
			)

			if opt == "dof_zoom" then
				handler.dof_zoom = ctl
				handler:Register(ctl, "video_adv_dof_zoom")
				handler:AddCallback("video_adv_dof_zoom", ui_events.BUTTON_CLICKED, handler.OnAdvancedDofZoomChanged, handler)
			elseif need_restart == 1 then
				handler:Register(ctl, "video_adv:"..ctr_type.."_"..opt)
				handler:AddCallback(
					"video_adv:"..ctr_type.."_"..opt,
					ctr_type == "list" and ui_events.LIST_ITEM_SELECT or ui_events.BUTTON_CLICKED,
					handler.show_need_restart_wnd, handler
				)
			end

			_st:Enable(enabled)
			_st2:Enable(enabled)
		end
	end
	local btn = xml:Init3tButton("video_adv:btn_to_simply",	self)
	handler:Register(btn, "btn_simply_graphic")
end
