init_priority = 800

local initialized = false

function attach(sm)
	init_module()
end

function init_module()
	if initialized then return end
	initialized = true

	if _G.AddRegularTask and olr_timers and olr_timers.upd then
		AddRegularTask("olr_timers_upd", olr_timers.upd, nil, 0, 50)
	end

	if _G.AddRegularTask and olr_offline_walk and olr_offline_walk.update then
		AddRegularTask("olr_offline_walk", olr_offline_walk.update, nil, 0, 50)
	end

	if _G.AddRegularTask and olr_monsters_sim and olr_monsters_sim.sim_kill_stalkers then
		AddRegularTask("olr_sim_kill_stalkers", olr_sim_setup, nil, 1, 600)
	end

	if _G.AddRegularTask and olr_monsters_sim and olr_monsters_sim.sim_location_traveling then
		AddRegularTask("olr_sim_location_traveling", olr_monsters_sim.sim_location_traveling, nil, 0, 500)
	end

	if _G.AddRegularTask and olr_squads and olr_squads.update then
		AddRegularTask("olr_squads", olr_squads.update, nil, 0, 500)
	end

	if _G.AddRegularTask and olr_raids and olr_raids.update then
		AddRegularTask("olr_raids", olr_raids.update, nil, 0, 1000)
	end
end

function olr_sim_setup()
	if db.actor and olr_monsters_sim then
		olr_monsters_sim.sim_kill_stalkers()
	end
end
