local initialized = false

function attach(sm)
	if initialized then return end
	initialized = true

	if olr_timers and olr_timers.upd then
		sm:subscribe({ signal = "on_update", fun = this.upd_timers })
	end

	if olr_offline_walk and olr_offline_walk.update then
		sm:subscribe({ signal = "on_update", fun = this.upd_offline_walk })
	end

	if olr_monsters_sim and olr_monsters_sim.sim_location_traveling then
		sm:subscribe({ signal = "on_update", fun = this.upd_location_traveling })
	end

	if olr_squads and olr_squads.update then
		sm:subscribe({ signal = "on_update", fun = this.upd_squads })
	end

	if olr_raids and olr_raids.update then
		sm:subscribe({ signal = "on_update", fun = this.upd_raids })
	end

	if olr_monsters_sim and olr_monsters_sim.sim_kill_stalkers then
		sm:subscribe({ signal = "on_first_update", fun = this.sim_kill_stalkers_once })
	end
end

function upd_timers(delta)
	ogse_signals.get_mgr():reschedule(50)
	olr_timers.upd()
end

function upd_offline_walk(delta)
	ogse_signals.get_mgr():reschedule(50)
	olr_offline_walk.update(delta)
end

function upd_location_traveling(delta)
	ogse_signals.get_mgr():reschedule(500)
	olr_monsters_sim.sim_location_traveling()
end

function upd_squads(delta)
	ogse_signals.get_mgr():reschedule(500)
	olr_squads.update()
end

function upd_raids(delta)
	ogse_signals.get_mgr():reschedule(1000)
	olr_raids.update()
end

function sim_kill_stalkers_once()
	if db.actor then
		olr_monsters_sim.sim_kill_stalkers()
	end
end
