local func = nil
local tUpd = 0
local tUpdTime = 1000
local tUpdz = 0
local tUpdTimez = 3500
cnt_st = 0
local tmt = nil
local tmp = nil

local function olr_save(name, value)
	set_value("nlc." .. name, value)
end

local function olr_load(name, default)
	local res = get_value("nlc." .. name)
	if res ~= nil then
		return res
	else
		return default
	end
end

local function olr_del(name)
	remove_value("nlc." .. name)
end

function st_timer(name, delay, action)
	if not delay then
		return false
	end
	if not action then
		action = ""
	end
	local tc = olr_load("olr_timers_count", 0)
	if tc <= 0 then
		tc = 1
	end
	tc = tc + 1
	olr_save("olr_timers_count", tc)
	local time = game.time()
	olr_save("olr_xt" .. tc, name)
	olr_save("olr_xd" .. tc, time + delay * 1000 * system_ini():r_float("alife", "time_factor"))
	olr_save("olr_xp" .. tc, action)
	local ts = olr_load("olr_timers_started", 0)
	olr_save("olr_timers_started", ts + 1)
end

function upd()
	if time_global() > tUpdz then
		tUpdz = time_global() + tUpdTimez
		cnt_st = cnt_st + 1
	end
	if cnt_st > 4 then
		if device().precache_frame < 1 then
			if time_global() > tUpd then
				tUpd = time_global() + tUpdTime
				if level.present() then
					local tc = olr_load("olr_timers_count", 0)
					if tc and tc > 0 then
						for a = 1, tc do
							tmt = olr_load("olr_xt" .. a, nil)
							if tmt then
								olr_timers.timer_found(a)
							end
						end
					end
				end
			end
		end
	end
end

function timer_found(idx)
	local time = game.time()
	local timvar = olr_load("olr_xd" .. idx, nil)
	local name, params
	if timvar and time then
		if timvar <= time then
			name = olr_load("olr_xt" .. idx, nil)
			params = olr_load("olr_xp" .. idx, nil)
			olr_timers.do_timer_action(name, params, idx)
		end
	end
end

function do_timer_action(select_string, params_string, idx)
	func = loadstring(params_string)
	if func then
		local ok, err = pcall(func)
		if not ok then
		end
		olr_del("olr_xt" .. idx)
		olr_del("olr_xd" .. idx)
		olr_del("olr_xp" .. idx)
		local td = olr_load("olr_timers_done", 0)
		td = td + 1
		olr_save("olr_timers_done", td)
		local tc = olr_load("olr_timers_count", 0)
		if tostring(td) == tostring(tc) then
			olr_save("olr_timers_count", 1)
			olr_save("olr_timers_done", 1)
		end
	end
end

function has_timer(name)
	local tc = olr_load("olr_timers_count", 0)
	if tc and tc > 0 then
		for a = 1, tc do
			tmp = olr_load("olr_xt" .. a, nil)
			if tmp and tmp == name then
				return true
			end
		end
		return false
	end
end

function del_timer(name)
	local tc = olr_load("olr_timers_count", 0)
	if tc then
		for a = 1, tc do
			tmp = olr_load("olr_xt" .. a, nil)
			if tmp and tmp == name then
				local td = olr_load("olr_timers_done", 0)
				olr_save("olr_timers_done", td + 1)
				olr_del("olr_xt" .. a)
				olr_del("olr_xd" .. a)
				olr_del("olr_xp" .. a)
			end
		end
	end
end
