
-- [HE-PORT] perenos kvestovyh funkcij iz NLC HE (kotovod\nlc_fixes.script)
function create_limansk_corpse()
	sak.create_corpse( "limansk_mielofon_corpse",
        sak.v3f( -50.284, -10.629, -183.869 ), 2993, 2894, 10108
    )
end
function rewrite_val_box_data()
	local box = g_sim:object( "dv_sak_box_ammo" )
	if box then 
		local pk         = get_netpk( box )
		local data       = pk:get()
		data.custom_data = "bes"
		pk:set( data )
	end
end
