local t = {}

function load_job(sj, gname, type, squad, groups)
	-- Посетители Долга
	if type=="bar_visitors" then
		t = {section = "logic@bar_visitors_kamp1",
			idle = 0,
			prior = 9, state = {0}, squad = squad, group = groups[2],
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.rank>400
						end
		}
		table.insert(sj, t)				
		t = {section = "logic@bar_visitors_kamp1",
			idle = 0,
			prior = 8, state = {0}, squad = squad, group = groups[2],
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.rank>400
						end
		}
		table.insert(sj, t)				
		t = {section = "logic@bar_visitors_kamp1",
			idle = 0,
			prior = 7, state = {0}, squad = squad, group = groups[2],
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.rank>400
						end
		}
		table.insert(sj, t)				
		t = {section = "logic@bar_visitors_kamp1",
			idle = 0,
			prior = 6, state = {0}, squad = squad, group = groups[2],
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.rank>400
						end
		}
		table.insert(sj, t)			

		t = {section = "logic@bar_visitors_kamp2",
			idle = 0,
			prior = 9, state = {0}, squad = squad, group = groups[3],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)				
		t = {section = "logic@bar_visitors_kamp2",
			idle = 0,
			prior = 8, state = {0}, squad = squad, group = groups[3],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)				
		t = {section = "logic@bar_visitors_kamp2",
			idle = 0,
			prior = 7, state = {0}, squad = squad, group = groups[3],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)				
		t = {section = "logic@bar_visitors_kamp2",
			idle = 0, 
			prior = 6, state = {0}, squad = squad, group = groups[3],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)						

		t = {section = "logic@bar_visitors_kamp3",
			idle = 0,
			prior = 9, state = {0}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)				
		t = {section = "logic@bar_visitors_kamp3",
			idle = 0,
			prior = 8, state = {0}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)				
		t = {section = "logic@bar_visitors_kamp3",
			idle = 0,
			prior = 7, state = {0}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)				
		t = {section = "logic@bar_visitors_kamp3",
			idle = 0,
			prior = 6, state = {0}, squad = squad, group = groups[4],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)										

		t = {section = "logic@bar_visitors_walker",
			idle = 0, 
			prior = 7, state = {0}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)				
		t = {section = "logic@bar_visitors_walker",
			idle = 0, timeout = lua_random(10,20)*60*1000,
			prior = 7, state = {0}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)				
		t = {section = "logic@bar_visitors_walker",
			idle = 0, timeout = lua_random(10,20)*60*1000,
			prior = 7, state = {0}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)				
		t = {section = "logic@bar_visitors_walker",
			idle = 0, timeout = lua_random(10,20)*60*1000,
			prior = 7, state = {0}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)		
		
	end
	
	-- Гулаг ламеров Долга внутри базы Долга
	if type=="bar_dolg_general" then
		t = {section = "logic1@bar_dolg_general_guard_left",
			idle = 0,
			prior = 8, state = {0,1,2}, squad = squad, group = groups[0],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)				
		t = {section = "logic2@bar_dolg_general_guard_right",
			idle = 0,
			prior = 8, state = {0,1,2}, squad = squad, group = groups[0],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)				
		t = {section = "logic3@bar_dolg_general_guard_center",
			idle = 0,
			prior = 9, state = {0,1,2}, squad = squad, group = groups[0],
			in_rest = "", position_threshold = 400, out_rest = "",
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}",
			predicate = function(obj_info)
							return obj_info.profile_name=="bar_dolg_guard_commander"
						end
			}
		table.insert(sj, t)		
			t = {section = "logic4@bar_dolg_general_kamp",
			idle = 0,
			prior = 5, state = {0,1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = {section = "logic4@bar_dolg_general_kamp",
			idle = 0,
			prior = 5, state = {0,1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = {section = "logic4@bar_dolg_general_kamp",
			idle = 0,
			prior = 5, state = {0,1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = {section = "logic4@bar_dolg_general_kamp",
			idle = 0,
			prior = 5, state = {0,1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = {section = "logic4@bar_dolg_general_kamp",
			idle = 0,
			prior = 5, state = {0,1}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)


		t = {section = "logic5@bar_dolg_general_patrol1", 
			idle = 5*60*60*1000,
			prior = 6, state = {0}, squad = squad, group = groups[2],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = {section = "logic6@bar_dolg_general_patrol2", 
			idle = 5*60*60*1000,
			prior = 6, state = {0}, squad = squad, group = groups[2],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)


		t = {section = "logic6@bar_dolg_general_camper",
			idle = 0,
			prior = 5, state = {2}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = {section = "logic7@bar_dolg_general_camper",
			idle = 0,
			prior = 5, state = {2}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = {section = "logic8@bar_dolg_general_camper",
			idle = 0,
			prior = 5, state = {2}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = {section = "logic9@bar_dolg_general_camper",
			idle = 0,
			prior = 5, state = {2}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = {section = "logic10@bar_dolg_general_camper",
			idle = 0,
			prior = 5, state = {2}, squad = squad, group = groups[1],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)

	end

	-- Гулаг ветеранов Долга внутри базы Долга
	if type=="bar_dolg_veterans" then
		t = {section = "logic3@bar_dolg_veterans_gates1", 
			idle = 0,
			prior = 7, state = {0,1}, squad = squad, group = groups[0],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = {section = "logic4@bar_dolg_veterans_gates2", 
			idle = 0,
			prior = 7, state = {0,1}, squad = squad, group = groups[0],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = {section = "logic1@bar_dolg_veterans_guard_bunker1", 
			idle = 0,
			prior = 9, state = {0,1,2}, squad = squad, group = groups[0],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = {section = "logic2@bar_dolg_veterans_guard_bunker2", 
			idle = 0,
			prior = 9, state = {0,1,2}, squad = squad, group = groups[0],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
		t = {section = "logic5@bar_dolg_veterans_gates_alarm1", 
			idle = 0,
			prior = 5, state = {2}, squad = squad, group = groups[0],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)	
		t = {section = "logic6@bar_dolg_veterans_gates_alarm2", 
			idle = 0,
			prior = 5, state = {2}, squad = squad, group = groups[0],
			in_rest = "", out_rest = ""
					--online = "{=actor_in_zone(bar_dolg_online_restrictor)}"
		}
		table.insert(sj, t)
	end

	-- Гулаг в бункере Долга
	if type=="bar_dolg_bunker" then
		t = {section = "logic2@bar_dolg_bunker", 
			idle = 0,
			prior = 10, state = {0}, squad = squad, group = groups[0],
			in_rest = "", out_rest = "bar_dolg_bunker_restrictor"
					--online = "{=actor_in_zone(bar_bunker_online_restrictor)}"
		}
		table.insert(sj, t)				
		t = {section = "logic3@bar_dolg_bunker", 
			idle = 0,
			prior = 5, state = {0}, squad = squad, group = groups[0],
			in_rest = "", out_rest = "bar_dolg_bunker_restrictor"
					--online = "{=actor_in_zone(bar_bunker_online_restrictor)}"
		}
		table.insert(sj, t)				
		t = {section = "logic4@bar_dolg_bunker", 
			idle = 0,
			prior = 5, state = {0}, squad = squad, group = groups[0],
			in_rest = "", out_rest = "bar_dolg_bunker_restrictor"
					--online = "{=actor_in_zone(bar_bunker_online_restrictor)}"
		}
		table.insert(sj, t)				
		t = {section = "logic5@bar_dolg_bunker", 
			idle = 0,
			prior = 4, state = {0}, squad = squad, group = groups[0],
			in_rest = "", out_rest = "bar_dolg_bunker_restrictor"
					--online = "{=actor_in_zone(bar_bunker_online_restrictor)}"
		}
		table.insert(sj, t)				
		
	end

		-- Гулаг сталкеров на заставе 1

		if type=="bar_zastava" then 
				t = {section = "logic@bar_dolg_zastava1_cammander_1",
				idle = 0,
				prior = 9, state = {0},
				in_rest = "", out_rest = "bar_zastava_restrictor",
					--online = "{=actor_in_zone(bar_zastava_online_restrictor)}",
		predicate = function(obj_info)
									return obj_info.profile_name=="bar_zastava_commander_1"
							end
				}
		table.insert(sj, t)	
				for i = 1,3 do
					t = {section = "logic@bar_dolg_zastava1_walker"..i,
					idle = 0,
					prior = 8, state = {0},
					in_rest = "", out_rest = "bar_zastava_restrictor"
					--online = "{=actor_in_zone(bar_zastava_online_restrictor)}"
								}
				table.insert(sj, t)
				end
		end

		-- Гулаг сталкеров на заставе 2

		if type=="bar_zastava_2" then 
				for i = 1,3 do
					t = {section = "logic@bar_dolg_zastava2_walker"..i,
					idle = 0,
					prior = 9, state = {0},
					in_rest = "", out_rest = "bar_zastava_restrictor_2"
					--online = "{=actor_in_zone(bar_zastava2_online_restrictor)}"	
								}
				table.insert(sj, t)
				end
		end

	-- Учёные
	
	if type=="bar_ecolog_crush" then
		t = {section = "logic@bar_ecolog_crush_sniper_1", 
			idle = 0,
			prior = 5, state = {0}, squad = squad, group = groups[0],
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.name~="bar_ecolog_professor"
						end
		}
		table.insert(sj, t)
		t = {section = "logic@bar_ecolog_crush_sniper_2", 
			idle = 0,
			prior = 5, state = {0}, squad = squad, group = groups[0],
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.name~="bar_ecolog_professor"
						end
		}
		table.insert(sj, t)
		t = {section = "logic@bar_ecolog_crush_sniper_3", 
			idle = 0,
			prior = 5, state = {0}, squad = squad, group = groups[0],
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.name~="bar_ecolog_professor"
						end
		}
		table.insert(sj, t)
		t = {section = "logic@bar_ecolog_professor", 
			idle = 0,
			prior = 5, state = {0}, squad = squad, group = groups[0],
			--online = true,
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.name=="bar_ecolog_professor"
						end
		}
		table.insert(sj, t)

		end

	-- бандиты на стройке								  

	if type=="bar_freedom_chasers_attack" then
		
		table.insert(sj, t)
		t = {section = "logic@bar_freedom_chaser_attack_hide_1", 
			idle = 0,
			prior = 5, state = {1}, squad = squad, group = groups[0],
			in_rest = "",position_threshold = 100, out_rest = ""
		}
		table.insert(sj, t)
		t = {section = "logic@bar_freedom_chaser_attack_hide_2", 
			idle = 0,
			prior = 5, state = {1}, squad = squad, group = groups[0],
			in_rest = "",position_threshold = 100, out_rest = ""
		}
		table.insert(sj, t)
		t = {section = "logic@bar_freedom_chaser_attack_hide_3", 
			idle = 0,
			prior = 5, state = {1}, squad = squad, group = groups[0],
			in_rest = "",position_threshold = 100, out_rest = ""
		}
		table.insert(sj, t)
		t = {section = "logic@bar_freedom_chaser_attack_hide_4", 
			idle = 0,
			prior = 5, state = {1}, squad = squad, group = groups[0],
			in_rest = "",position_threshold = 100, out_rest = ""
		}
		table.insert(sj, t)

	end
	
	-- Фраер и Кочерга
	
	if type=="dt_fraer_smart" then
		t = {section = "logic@dt_fraer_smart_fraer",
			idle = 0,
			prior = 4, state = {0},
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.profile_name=="sim_bandit_master_fraer_sak"
						end
		}
		table.insert(sj, t)
		t = {section = "logic@dt_fraer_smart_kocherga",
			idle = 0,
			prior = 4, state = {0},
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.profile_name=="sim_bandit_master_kocherga_sak"
						end
		}
		table.insert(sj, t)
	end
	-- Волкодав и ко

	if type=="dt_merc_baze" then
		t = {section = "logic@dt_merc_baze_post1",
			idle = 0,
			prior = 50, state = {0},
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.story_id==509
						end
		}
		table.insert(sj, t)
		t = {section = "logic@dt_merc_baze_post2",
			idle = 0,
			prior = 40, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = {section = "logic@dt_merc_baze_post3",
			idle = 0,
			prior = 30, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = {section = "logic@dt_merc_baze_post4",
			idle = 0,
			prior = 40, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = {section = "logic@dt_merc_baze_post5",
			idle = 0,
			prior = 30, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	end
		
	if type=="bar_dolg_petrenko" then
		t = {section = "logic@bar_dolg_petrenko",
			idle = 0,
			prior = 15, state = {0},
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
										return obj_info.profile_name=="bar_dolg_petrenko"
									end
		}
		table.insert(sj, t)
		t = {section = "logic@bar_dolg_petrenko_off",
			idle = 0,
			prior = 15, state = {1},
			online = false,
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.profile_name=="bar_dolg_petrenko"
						end
		}
		table.insert(sj, t)
	end
	
	if type=="yan_dolg_petrenko" then
		t = {section = "logic@yan_dolg_petrenko",
			idle = 0,
			prior = 15, state = {1},
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.name=="yan_dolg_petrenko"
						end
		}
		table.insert(sj, t)
		t = {section = "logic@yan_dolg_petrenko",
			idle = 0,
			prior = 15, state = {0},
			in_rest = "", position_threshold = 400, out_rest = "",
			online = false,
			predicate = function(obj_info)
							return obj_info.name=="yan_dolg_petrenko"
						end
		}
		table.insert(sj, t)
	end
	
	if type=="art_exchanger_bar" then
		t = {section = "logic@art_exchanger_bar",
			idle = 0,
			prior = 15, state = {0},
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.name=="art_exchanger"
						end
		}
		table.insert(sj, t)
		t = {section = "logic@art_exchanger_bar",
			idle = 0,
			prior = 15, state = {1},
			in_rest = "", position_threshold = 400, out_rest = "",
			online = false,
			predicate = function(obj_info)
							return obj_info.name=="art_exchanger"
						end
		}
		table.insert(sj, t)
	end
	if type=="art_exchanger_mil" then
		t = {section = "logic@art_exchanger_mil",
			idle = 0,
			prior = 15, state = {1},
			in_rest = "mil_freedom_wall_restrictor", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.name=="art_exchanger2"
						end
		}
		table.insert(sj, t)
		t = {section = "logic@art_exchanger_mil",
			idle = 0,
			prior = 15, state = {0},
			in_rest = "mil_freedom_wall_restrictor", position_threshold = 400, out_rest = "",
			online = false,
			predicate = function(obj_info)
							return obj_info.name=="art_exchanger2"
						end
		}
		table.insert(sj, t)
	end
	if type=="red_serafim" then
		t = {section = "logic@red_serafim",
			idle = 0,
			prior = 50, state = {0},
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.profile_name=="serafim"
						end
		}
		table.insert(sj, t)
	end
	if type=="vorobey_bar" then
		t = {section = "logic@vorobey_bar",
			idle = 0,
			prior = 50, state = {0},
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.profile_name=="sim_stalker_veteran_vorobey"
						end
		}
		table.insert(sj, t)
	end
	if type=="diador_bar" then
		t = {section = "logic@diador_bar",
			idle = 0,
			prior = 15, state = {0},
			in_rest = "sak_physic_object02_restr", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.profile_name=="sim_stalker_master_diador"
						end
		}
		table.insert(sj, t)
	end
	if type=="diador_mar" then
		t = {section = "logic@diador_mar",
			idle = 0,
			prior = 15, state = {0},
			in_rest = "", position_threshold = 400, out_rest = "",
			predicate = function(obj_info)
							return obj_info.profile_name=="sim_stalker_master_diador"
						end
		}
		table.insert(sj, t)
	end
end

local simpl_type={
["dt_merc_baze"]=true,
["red_serafim"]=true,
["vorobey_bar"]=true,
["diador_bar"]=true,
["diador_mar"]=true,
["bar_zastava"]=true,
["dt_fraer_smart"]=true,
["bar_zastava_2"]=true,
["bar_dolg_bunker"]=true,
["bar_ecolog_crush"]=true,
["bar_visitors"]=true
}
function load_states(gname, type)
	
	if simpl_type[type] then
		return function(gulag)
			return 0
		end
	end

	if type=="art_exchanger_bar" then
		return function(gulag)
			if db.actor~=nil then
				if has_alife_info("yan_semenov_resiept_done") and not has_alife_info("sak_ros_merk_out") and not has_alife_info("volkodav_dt_art_done") then
					return 0
				end
				local shift=2
				local holidays=level.get_time_days()
				for i=1,7 do
					if (holidays >= shift*(i*2-1) and holidays < shift*(i*2)) then
					return 0
					end
				end
				return 1
			else
				return gulag.state
			end
		end
	end
	
	if type=="art_exchanger_mil" then
		return function(gulag)
			if db.actor~=nil then
				local shift=2
				local holidays=level.get_time_days()
				for i=1,7 do
					if (holidays >= shift*(i*2-1) and holidays < shift*(i*2)) then
					return 0
					end
				end
				return 1
			else
				return gulag.state
			end
		end
	end
	
	if type=="bar_dolg_petrenko" then
		return function(gulag)
			if db.actor~=nil then
				local shift=2
				local holidays=level.get_time_days()
				for i=1,10 do
					if (holidays >= shift*(i*2-1) and holidays < shift*(i*2)) then
					return 1
					end
				end
				return 0
			else
				return gulag.state
			end
		end
	end
	
	if type=="yan_dolg_petrenko" then
		return function(gulag)
			if db.actor~=nil then
				local shift=2
				local holidays=level.get_time_days()
				for i=1,10 do
					if (holidays >= shift*(i*2-1) and holidays < shift*(i*2)) then
					return 1
					end
				end
				return 0
			else
				return gulag.state
			end
		end
	end

	if type=="bar_dolg_general" then
		return function(gulag)
				for k,v in pairs(gulag.Object) do
					if v~=true and v:best_enemy()~=nil and v:best_enemy():id()==0 then
							gulag.alarm_start = game.get_game_time()
							return 2 -- тревога
					end
				end		
		
				if gulag.alarm_start==nil or
					game.get_game_time():diffSec(gulag.alarm_start) > 300 then
					if level.get_time_hours() >= 6 and level.get_time_hours() <= 22 then
						return 0	-- день
					else
						return 1	-- ночь
					end
				else
					return 2
				end
		end
	end
	
	if type=="bar_dolg_veterans" then				
		return function(gulag)
				for k,v in pairs(gulag.Object) do
					if v~=true and v:best_enemy()~=nil and v:best_enemy():id()==0 then
							gulag.alarm_start = game.get_game_time()
							return 2 -- тревога
					end
				end		
		
				if gulag.alarm_start==nil or game.get_game_time():diffSec(gulag.alarm_start) > 300 then
					if level.get_time_hours() >= 6 and level.get_time_hours() <= 22 then
						return 0	-- день
					else
						return 1	-- ночь
					end
				else
					return 2
				end
		end
	end
	
	if type=="bar_freedom_chasers_attack" then				
		return function(gulag)
			return 1
		end
	end
end

--------------------------------------------------------------------------
-- Dynamic ltx
--------------------------------------------------------------------------
function load_ltx(gname, type)
	return nil
end
local no_comm={
["art_exchanger_bar"]=true,
["art_exchanger_mil"]=true,
["red_serafim"]=true,
["vorobey_bar"]=true,
["diador_bar"]=true,
["diador_mar"]=true,
["bar_visitors"]=true
}
function checkStalker(npc_community, gulag_type)
	if gulag_type=="bar_dolg_general" or gulag_type=="bar_dolg_petrenko" or gulag_type=="yan_dolg_petrenko" or gulag_type=="bar_dolg_veterans" or  gulag_type=="bar_dolg_bunker" or gulag_type=="bar_zastava" or gulag_type=="bar_zastava_2" then
		return npc_community=="dolg"
	end
	if no_comm[gulag_type] then
		return true
	end
	if gulag_type=="dt_fraer_smart" or gulag_type=="bar_freedom_chasers_attack" then
		return npc_community=="bandit"
	end
	if gulag_type=="dt_merc_baze" then
		return npc_community=="killer"
	end
	if gulag_type=="bar_ecolog_crush" then
		return npc_community=="ecolog"
	end

	return false
end

function checkMonster(npc_community, gulag_type, npc_rank, se_obj)													  
	return false
end