addons = {
	"move_mgr",
	"xr_kamp",
	"dsh_monster_attack",
	"dsh_battle_radius",
	"xr_combat_ignore",
	"dsh_enemies",
	"undergrounds_hits",
	"oxy_wnp",
	"actor_take_item", -- [HE-PORT]
	"weight_upgrade", -- [HE-PORT]
	"parts_decay", -- [HE-PORT]
	"he_stor", -- [HE-PORT]
	"he_kruglov",
	"he_semenov",
	"he_guest_kill",
	"he_no_monsters",
	"he_red_water",
	"anagramm_flash", -- [HE-PORT]
	"pda_battery", -- [HE-PORT]
	"he_pda_market", -- [HE-PORT]
	"ballon_refill", -- [HE-PORT]
	"set_far_dist_vision",
	"projectors",

	"nlc_container",
	"arc_arts",
	"art_collections", -- [HE-PORT]
	"he_gluzov_art",
	"smart_terrain",
	"actor_params",
	"black_tip",
	"sak_dialog",
	"sak",
	"ui_find_by_name",
	"windows",
	"razgruzka",
	"vergas_krujka",
	"vergas_watch",
	"xr_statistic",

	"dsh_hud_icons",
	"vergas_lib",
	"amk_mod",
	"timers",
	"amk",
	"vergas_masks",
	"ogse_campfire",
	"xr_meet",

	"wpn_params",

	"nlc_torch",
	"sak_inventory",
	"nvd_params",

	"ui_body_add",
	"ui_inv_add",
	"ui_trade_add",
	"trade_manager",
	"ogsr_exo_step_sound",
	"he_watch_ui", -- [HE-PORT]
	"allcore_hide",
	"anomaly_detector",
	"flamethrower",
	"ui_pda_addons",
	"ogsr_shaders_control",
	"ui_arc_container_menu",
	"dsh_drag_drop",
	"dsh_remkit",
	"dsh_reload",
	"dsh_wpn",
	"he_hipfire", -- [HE-PORT]
	"sivol_fuzz_recoil_profiles", -- [HE-PORT]
	"sivol_fuzz_recoil", -- [HE-PORT]
	"monster_parts",
	-- [HE-PORT]
	"thirst",
	"nlc_corpse_decay",
	"sivol_weapon",
	"sivol_weapon_aim_speed",
	"sivol_weapon_inertia",
	"sivol_weapon_inertia_configs",
	"sivol_blood_pools",
	"trade_arts_news",
	"new_compass_tp",
	"ogse_critical_hit",
	"garbage_arts",
	"detectors_art",
	"he_sleeves", -- [HE-PORT]
	"on_body_item_drop",
	"watch_gate",
	"sivol",
	"sivol_outfit_animations", -- [HE-PORT]
	-- [HE-PORT]
	"olr_init",
	-- [HE-PORT]
	"he_bai_compat",
	"sivol_sprint_fov",
	"sivol_weapon_zoom",
	"pda_noise",
	"sivol_pda",
	"xrs_battle_ai",
	"sivol_anom_effects",
	"sivol_rain",
	"sivol_emp_sources",
	"sivol_hit_shock",
	"sivol_outfit_stats",
	"sivol_shell_sounds",
	"sivol_visible_body"
}
