param(
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot
$cp1251 = [System.Text.Encoding]::GetEncoding(1251)
$errors = New-Object 'System.Collections.Generic.List[string]'

function Add-AuditError {
    param([string]$Message)

    [void]$script:errors.Add($Message)
}

function Read-LegacyText {
    param([string]$RelativePath)

    $path = Join-Path $repoRoot $RelativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        Add-AuditError "Missing file: $RelativePath"
        return ""
    }

    return [System.IO.File]::ReadAllText($path, $cp1251)
}

function Read-StringTable {
    param([string]$RelativePath)

    $path = Join-Path $repoRoot $RelativePath
    $table = @{}
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        Add-AuditError "Missing string table: $RelativePath"
        return $table
    }

    $xml = New-Object System.Xml.XmlDocument
    $xml.PreserveWhitespace = $true
    try {
        [void]$xml.Load($path)
    }
    catch {
        Add-AuditError "Could not parse XML: $RelativePath ($($_.Exception.Message))"
        return $table
    }

    foreach ($node in $xml.SelectNodes('/string_table/string')) {
        $id = [string]$node.GetAttribute('id')
        if ([string]::IsNullOrEmpty($id)) {
            Add-AuditError "String without an id: $RelativePath"
            continue
        }
        $table[$id] = [string]$node.InnerText
    }

    return $table
}

function Require-LocalizedString {
    param(
        [hashtable]$Table,
        [string]$Id,
        [string]$Language
    )

    if (-not $Table.ContainsKey($Id)) {
        Add-AuditError "Missing $Language localization: $Id"
        return ""
    }

    return [string]$Table[$Id]
}

$eng = Read-StringTable 'gamedata/config/text/eng/ui_st_mm.xml'
$rus = Read-StringTable 'gamedata/config/text/rus/ui_st_mm.xml'

$rusDefaultMarker = @(
    [char]0x041F, [char]0x043E, ' ',
    [char]0x0443, [char]0x043C, [char]0x043E, [char]0x043B,
    [char]0x0447, [char]0x0430, [char]0x043D, [char]0x0438,
    [char]0x044E, ':'
) -join ''

# Every description referenced by an options-menu script must exist in both
# languages and keep the established yellow default-marker convention. The
# section descriptions are intentional exceptions: they describe a category,
# rather than an individual option.
$descriptionIds = @{}
$scriptDir = Join-Path $repoRoot 'gamedata/scripts/ui'
foreach ($scriptPath in Get-ChildItem -LiteralPath $scriptDir -Filter 'ui_mm_opt_*.script' -File) {
    $source = Read-LegacyText (Join-Path 'gamedata/scripts/ui' $scriptPath.Name)
    foreach ($match in [regex]::Matches($source, '(?<![A-Za-z0-9_])(?:ui_[A-Za-z0-9_]+_desc|video_settings_desc_[0-9]+)(?![A-Za-z0-9_])')) {
        $descriptionIds[$match.Value] = $true
    }
}

foreach ($id in ($descriptionIds.Keys | Sort-Object)) {
    $engText = Require-LocalizedString $eng $id 'English'
    $rusText = Require-LocalizedString $rus $id 'Russian'
    if ($id -notmatch '^ui_mm_section_') {
        if ($engText -notmatch '%c\[yellow\]Default:') {
            Add-AuditError "English description lacks the yellow default marker: $id"
        }
        if ($rusText -notmatch [regex]::Escape('%c[yellow]' + $rusDefaultMarker + '')) {
            Add-AuditError "Russian description lacks the yellow default marker: $id"
        }
    }
}

# Section rows are generated by their tab scripts. Verify that each generated
# section has a title and a hint caption in both language tables.
$sectionIds = @{}
foreach ($relativeScript in @(
    'gamedata/scripts/ui/ui_mm_opt_gameplay.script',
    'gamedata/scripts/ui/ui_mm_opt_video_adv.script'
)) {
    $source = Read-LegacyText $relativeScript
    foreach ($match in [regex]::Matches($source, '\{\s*section\s*=\s*"([^"]+)"\s*\}')) {
        $sectionIds[$match.Groups[1].Value] = $true
    }
    if ($source -notmatch 'InitLabel\("[^:]+:templ_section"') {
        Add-AuditError "Section-generating script has no templ_section label: $relativeScript"
    }
}

foreach ($id in ($sectionIds.Keys | Sort-Object)) {
    [void](Require-LocalizedString $eng $id 'English')
    [void](Require-LocalizedString $rus $id 'Russian')
    [void](Require-LocalizedString $eng ($id + '_desc') 'English')
    [void](Require-LocalizedString $rus ($id + '_desc') 'Russian')
}

$uiXmlPath = Join-Path $repoRoot 'gamedata/config/ui/ui_mm_opt.xml'
if (Test-Path -LiteralPath $uiXmlPath -PathType Leaf) {
    $uiXml = New-Object System.Xml.XmlDocument
    try {
        [void]$uiXml.Load($uiXmlPath)
        $sectionTemplates = @($uiXml.SelectNodes('//templ_section'))
        if ($sectionTemplates.Count -ne 2) {
            Add-AuditError "Expected two section templates in ui_mm_opt.xml, found $($sectionTemplates.Count)"
        }
        foreach ($template in $sectionTemplates) {
            $texture = $template.SelectSingleNode('./texture')
            if ($null -eq $texture -or $texture.InnerText -ne 'ui_brokenline') {
                Add-AuditError "Section template is missing the established ui_brokenline treatment"
            }
        }
    }
    catch {
        Add-AuditError "Could not parse XML: gamedata/config/ui/ui_mm_opt.xml ($($_.Exception.Message))"
    }
}
else {
    Add-AuditError 'Missing file: gamedata/config/ui/ui_mm_opt.xml'
}

# These are the reset invariants that previously regressed. Keep the check
# deliberately explicit: the reset table is Lua data, not a general-purpose
# config parser, and these values are the user-approved canonical defaults.
$mainSource = Read-LegacyText 'gamedata/scripts/ui/ui_mm_opt_main.script'
$expectedResetValues = [ordered]@{
    'g_font_scale_x' = '1.0'
    'g_font_scale_y' = '1.0'
    'hud_crosshair_hard' = 'on'
    'hud_show_status_icons' = 'on'
}
foreach ($entry in $expectedResetValues.Keys) {
    $match = [regex]::Match($mainSource, '(?m)^\s*' + [regex]::Escape($entry) + '\s*=\s*"([^"]+)"')
    if (-not $match.Success) {
        Add-AuditError "Reset table entry is missing: $entry"
    }
    elseif ($match.Groups[1].Value -ne $expectedResetValues[$entry]) {
        Add-AuditError "Reset table value for $entry is '$($match.Groups[1].Value)', expected '$($expectedResetValues[$entry])'"
    }
}

foreach ($callbackId in @('btn_default_sound', 'btn_gameplay_default')) {
    if ($mainSource -notmatch ('AddCallback\("' + $callbackId + '"\s*,\s*ui_events\.BUTTON_CLICKED')) {
        Add-AuditError "Reset button is not wired to a click callback: $callbackId"
    }
}

if ($errors.Count -gt 0) {
    foreach ($errorMessage in $errors) {
        Write-Host "ERROR: $errorMessage" -ForegroundColor Red
    }
    exit 1
}

if (-not $Quiet) {
    Write-Host ("Options-menu audit passed: {0} descriptions, {1} generated sections, 4 reset invariants." -f $descriptionIds.Count, $sectionIds.Count)
}
exit 0
