function attach(sm)
	sm:subscribe({signal = "on_item_to_slot", fun = this.on_slot})
	sm:subscribe({signal = "on_item_to_ruck", fun = this.on_drop})
	sm:subscribe({signal = "on_drop_before_all", fun = this.on_drop})
	-- sm:subscribe({signal = "on_key", fun = this.on_key})
	sm:subscribe({signal = "on_before_switch_nv", fun = this.on_before_switch_nv})
	sm:subscribe({signal = "on_spawn", fun = this.on_spawn})
	sm:subscribe({signal = "on_first_update", fun = this.on_first_update})
	sm:subscribe({signal = "on_save", fun = this.on_save})
	sm:subscribe({signal = "on_update", fun = this.on_save})
end

local snd_on = sound_object("weapons\\nv_start")
local snd_off = sound_object("weapons\\nv_off")

-- https://github.com/OGSR/OGSR_GA_Resources/blob/main/gamedata/scripts/ogse_night_vision.script
local r_pnv_gain_current_base = 0
local r_pnv_gain_current_mod  = 0

local beef_nv = {
    r_pnv_mode = 0,             -- 1, 2, 3
    r_pnv_num_tubes = 2,        -- число трубок 1, 1.1, 1.2, 2, 4
    r_pnv_gain_offset = 2.0,    -- усиление (сила) ПНВ (основа(
    r_pnv_gain_current = 1,     -- усиление (сила) ПНВ
    r_pnv_radius = 0.5,         -- размер (радиус) ПНВ
    r_pnv_glitch = 0.006,       -- тряска
    r_pnv_noise = 0.3,          -- шум
    r_pnv_scanlines = 1,        -- эффект crt
    r_pnv_scintillation = 0.99, -- МЕРЦАНИЯ
    r_pnv_alfa_vignete = 0,     -- режим рамки 0 - blur, 1 - black, 2 - image overlay
    r_pnv_size_vignet = 0.04,   -- размер виньетки
    r_pnv_washout_thresh  = 0.7, -- засвет источников света
}

local beef_nv_v4 = {
    heat_fade_distance = vector4():set(13.000000, 20.000000, 0.000000, 0.000000), -- FADE_DISTANCE_START 13.00, FADE_DISTANCE_END 20.00
    heat_vision_blurring = vector4():set(1.000000, 1.500000, 1.100000, 0.000000), -- int samples = lerp(heat_vision_blurring.x, heat_vision_blurring.y, smoothstep(0.0, heat_vision_blurring.z, depth));
    heat_vision_steps = vector4():set(0.300000, 0.200000, 0.500000, 0.000000),    -- хз что это такое
}

local function apply_pnv_mode()
    -- 0.10000, 3.00000
    local gain = math.clamp(r_pnv_gain_current_base + r_pnv_gain_current_mod, 0.1, 3.0)
    cmd("r_pnv_gain_current", gain)
end

local function apply_pnv(nv_sect)
    local color = get_vector(nv_sect, "pnv_color")
    cmd("pnv_color " .. string.format("%f,%f,%f", color.x, color.y, color.z))

    for k, v in pairs(beef_nv) do
        local v1 = get_float(nv_sect, k, v)
        cmd(k, v1)
    end

    for k, v in pairs(beef_nv_v4) do
        local v = get_vector4(nv_sect, k, v)
        local v1 = string.format("%f,%f,%f,%f", v.x, v.y, v.z, v.w)
        cmd(k, v1)
    end

    r_pnv_gain_current_base = get_float(nv_sect, "r_pnv_gain_current", beef_nv.r_pnv_gain_current)
    apply_pnv_mode()
end

local eff, obj_id, flag
function on_slot(obj)
	local sect = obj and obj:section()
	local eff_sect = sect and get_string(sect, "night_vision_device")
	if not eff_sect then return end
	apply_pnv(eff_sect)
	local aobj = get_actor_obj()
	if aobj then aobj.can_switch_nv = true end
	eff, obj_id = eff_sect, obj:id()
end

function on_drop(obj)
	if obj:id() == obj_id then
		local aobj = get_actor_obj()
		if aobj then aobj.can_switch_nv = false end
		eff, obj_id = nil, nil
		off_pnv(flag)
	end
end

function on_before_switch_nv()
	if not eff or not (check_accum() and vergas_masks.get_flag_mask() == true) then return end
	if not used_items.can_use_gadget() or db.actor:is_talking() or level.main_input_receiver() then return end
	if level.name() == 'aver' then return end

	if db.actor:active_item() then
		if flag then
			off_pnv(true)
		else
			on_pnv(true)
		end
		return
	end

	local detector = db.actor:item_in_slot(8)
	local torch_anm_sec = "switch_torch"
	local anim = "anm_show"
	if detector and get_actor_obj():IsDetectorActive() then
		torch_anm_sec = get_string(detector:section(), "hud")
		anim = "anm_headlamp_on"
	end
	local torch_anm_time_1 = game.get_motion_length(torch_anm_sec, anim, 1)
	level.only_allow_movekeys(true)
	level.set_actor_allow_ladder(false)
	game.play_hud_motion(db.actor:active_item() and 1 or 2, torch_anm_sec, anim, false, 1)
	-- level.add_cam_effector("camera_effects\\weapon\\headflash.anm", 7538, false, "", 0, false)
	dsh.timeout(torch_anm_time_1 * 0.5, function()
		if flag then
			off_pnv(true)
		else
			on_pnv(true)
		end
		dsh.timeout(torch_anm_time_1, function()
			level.only_allow_movekeys(false)
			level.set_actor_allow_ladder(true)
		end)
	end)
end

function on_pnv(snd)
	if not eff then return end
	flag = true
	cmd("r_pnv_mode 1")
	level.set_min_lumscale_amb(0.02)
	if snd then
		snd_on:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
end

function off_pnv(snd)
	flag = false
	cmd("r_pnv_mode 0")
	level.set_min_lumscale_amb(0.001)
	if snd then
		snd_off:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1.0)
	end
end

function on_spawn()
	local aobj = get_actor_obj()
	if aobj then aobj.can_switch_nv = false end
	flag = get_value("nightvision_en", false)
	-- if flag and level.name() ~= 'aver' then on_pnv() end
end

function on_first_update()
	if flag and level.name() ~= 'aver' then on_pnv() end
end

function on_save()
	set_value("nightvision_en", flag)
end

function check_accum()
	local obj = sak.get_accum()
	return obj and obj:condition() > 0.071 and obj
end

function disable_NVD()
	if flag then
		off_pnv()
	end
end

function get_NVD_powered()
	return flag
end
