
local body_states = { -- флажки состо€ни€ тела актора
[1] = "fwd",
[2] = "back",
[4] = "l_strafe",
[8] = "r_strafe",
[16] = "crouch",
[17] = "crouch", -- crouch в движении
[32] = "accel",
[48] = "creep",
[49] = "creep", -- creep в движении
[64] = "turn",
[128] = "jump",
[256] = "fall",
[512] = "landing",
[1024] = "landing2",
[2048] = "climb",
[4096] = "sprint",
[8192] = "l_lookout",
[16384] = "r_lookout"
}

-- получени€ флагов состо€ни€ тела актора
function actor_body_state()
  local aobj = get_actor_obj()
  local body_state = aobj and body_states[ aobj:get_body_state() ]
  if body_state then
    return body_state
  else
    return ""
  end
end

local cond_old=0.1
-- cond_wpn_old = { 0, 0, 0, 0, 0, 0 }

local add_outfit_weight=0

local cl_condition = {}

matches_flame=-1
pwr_restore=0
add_coll=0


params.con_commands = {}

local game_difficulty=tonumber(level.get_game_difficulty())
local game_difficulty_by_num = {
  [0] = "novice",
  [1] = "stalker",
  [2] = "veteran",
  [3] = "master"
  }
local immunity="actor_immunities_gd_"..game_difficulty_by_num[game_difficulty]
local hit_probability = system_ini():r_float("actor", "hit_probability_gd_"..game_difficulty_by_num[game_difficulty])

local offsets_xrGame_3312R =
 {
   console_add             = 1160,
   const_0_75f             = "$4D246C",    -- __real@3f400000 = 0.75 ?
   actor_fov               = "$53C598",    -- g_fov = 67.5f
   unbind                  = "$5616E8",
   cldcs                   = "$561E48",
   hud_info                = "$561E98"   
 } 

local offsets_xrGame_all = { xr3312release = offsets_xrGame_3312R } 

--[=[
wprintf("~C0B[~T/~B]. #PERF: params.script 0~C07")
local xrgame = GetModuleInfo('xrGame.dll').release
offsets_xrGame = offsets_xrGame_all ['xr'..xrgame] or {} -- offsets for functions
wprintf("~C0B[~T/~B]. #PERF: params.script 1~C07")
RunCommand('REINIT_DMA') -- reload offsets
wprintf("~C0B[~T/~B]. #PERF: params.script 2~C07")

if xr_build_id > 5500 then   
   offsets_xrGame.console_add = CalcPtr('#CConsole.commands', 0, '+', '@int')
  -- wprintf("[~T]. #PARAM: build_%d console_add =~C0D %s ~C07", xr_build_id, FormatPtr(offsets_xrGame.console_add) or 'nil')  
   --offsets_xrGame.actor_fov =   GetVarPtr('xrGame.dll', 'g_fov', 'RVA')
end
--]=]
function value2str(v)
 if type(v) == "number" then
    if math.abs(v) > 0.1 then 
       return sprintf("%.2f", v)
    else
       return sprintf("%.7f", v)
    end   
 else
    return DumpVar(v)
 end
end

_G.value2str = value2str

function update_prop(intf, key, newval)
 if intf == nil then
   wprintf("[~T].~C0C #ERROR:~C07 trying get/update nil table for property %s ", key)
   wprintf(" %s", debug.traceback(' ', 2))
   return 0
 end 
 
 
 if intf[key] == nil then
    if key ~= 'selected_item' then
       wprintf("[~T].~C0C #ERROR(params):~C0F table %s[%s] = nil ~C07", intf.class_name or '?', key)
    end   
    return nil
 end

 local v = intf[key] 
 if newval ~= nil then
    intf[key] = newval
    local sold = value2str(v)
    local snew = value2str(newval)
    if sold ~= snew then
       -- wprintf("~C0E %-30s ~C0B[~C0A%s~C0B] =~C0F %s~C07 =>>~C0F %s~C07", intf.class_name or '?', key, v, newval)
    end   
 end
 return v
end  

_G.update_prop = update_prop

function hit_probability_add(key)
  local new_hit_prob = hit_probability*key
  if new_hit_prob>1 then new_hit_prob=1 end
  actor_params.actor_prop ("hit_probability", new_hit_prob)
end
local mass=system_ini():r_float("actor","ph_mass")
function add_actor_mass(key)
  local new_mass = mass+key
  actor_params.mov_prop("ph_mass", new_mass)
end

function spawn_matches_flame(msec) 
end

function del_matches_flame(id)
end

function set_direction(coor_x,coor_y,coor_z)
  local dir_d = vector()
  dir_d:set(coor_x, coor_y, coor_z)
  local h_rad = -dir_d:getH()
  local p_rad = -dir_d:getP()
  coord_params.camera_angles(h_rad, p_rad)
end

function outfit_weight_cond(item_in_slot_6,cond,fast)
	-- local nname = 'nil'
	-- if item_in_slot_6 then
		-- nname = item_in_slot_6:name()
	-- end
	-- log2("outfit_weight_cond called for [%s] cond [%.4f] - cond_old [%.4f] = [%.4f]", nname, cond, cond_old, math.abs(cond-cond_old))
	if item_in_slot_6~=nil then
		if math.abs(cond-cond_old)>0.05 or fast then
			local section=item_in_slot_6:section()
			actor_immunities_add(section,cond)
			-- texman.swap_sleeve(sleeve[section][1],sleeve[section][2],sleeve[section][3],sleeve[section][4])
			cond_old=cond
			-- log2("outfit_weight_cond called for armor [%s] with cond [%s] fast_mode [%s]", section, tostring(cond), tostring(fast))
		end
	else
		if math.abs(cond-cond_old)>0.05 then
			actor_immunities_add()
			cond_old=0.03
			-- texman.swap_sleeve("000","css","001","001")
			-- log2("outfit_weight_cond called for armor [nil] with cond [%s]", tostring(cond))
		end
	end  
end

local cache_out = {} -- Manool: кэширование параметров дл€ оптимизации
local function get_out_prot(sect, par)
  if not cache_out[sect] then cache_out[sect] = {} end
  if not cache_out[sect][par] then
    local out_prot = string.gsub(par, "_immunity", "_protection")
    cache_out[sect][par] = sys_ini:r_float(sect, out_prot)
  end
  -- log3("cache_out = %s", cache_out)
  return cache_out[sect][par]
end

function actor_immunities_add(out_sect,key)
	local old_param = 0.6+tonumber(level.get_game_difficulty())*0.4
	for i,k in pairs(actor_params.immun_params) do
		if i~="unk_max_offset" then
			local new_param
			if out_sect then
				local param_out_prot = get_out_prot(out_sect, i)
				if i=="telepatic_immunity" then
					old_param=(old_param+0.2)
				end
				new_param = old_param*(1-(param_out_prot*key))
			else
				new_param = old_param*5
			end
			if i=="telepatic_immunity" then
				new_param=(new_param*sak.black_bonus)
			end
			actor_params.immun_prop (i, new_param)
		end
	end
end

function set_inv_weight(id, add)
 item_params.item_prop(id, "inv_weight", add)
end
  
local sys_repbox_weight = system_ini():r_float("repair_boxoutfit", "inv_weight")
function repbox_weight_add()
  if sak_inventory.eatable["repair_boxoutfit"] then
    for a=1,#sak_inventory.eatable["repair_boxoutfit"] do
        local repbox_id=sak_inventory.eatable["repair_boxoutfit"][a]
        local rem={}
        local sobj = alife():object(repbox_id)
      if sobj then
          local pk = get_netpk(sobj)
          local data = pk:get()
          local str=data.custom_data
          rem = vergas_lib.str_explode(",",str,true)
          local repiout=tonumber(rem[1]) or 0
          local repiweap=tonumber(rem[2]) or 0
          local new_weight = sys_repbox_weight+(0.25*repiout)+(0.25*repiweap)
          set_inv_weight(repbox_id, new_weight) -- for CInventoryItem descedants
      end
    end
  end
end

local sys_razgruzka_weight = system_ini():r_float("razgruzka", "inv_weight")
function razgruzka_weight_add(add)
  if sak_inventory.eatable["razgruzka"] then
      local razgruzka_id=sak_inventory.eatable["razgruzka"][1]
      local new_weight = sys_razgruzka_weight+add
        set_inv_weight(razgruzka_id, new_weight)
  end
end  

local sys_podsumok_weight = system_ini():r_float("podsumok", "inv_weight")
function podsumok_weight_add(add)
  if sak_inventory.eatable["podsumok"] then
     local podsumok_id=sak_inventory.eatable["podsumok"][1]
     local new_weight = sys_podsumok_weight+add
       set_inv_weight(podsumok_id, add)     
  end
end
local run_coef = system_ini():r_float("actor", "run_coef")
local sprint_koef = system_ini():r_float("actor", "sprint_koef")
local walk_accel = system_ini():r_float("actor", "walk_accel")
local climb_coef = system_ini():r_float("actor", "climb_coef")
local w_w_power = system_ini():r_float("actor_condition", "walk_weight_power")
local ww_power = w_w_power
local tiredness_timer = misc.game_timer()
local sleep_time = 0
-- set_value("ph_tiredness", -100)
local prev_inert
function tiredness_add()
	if vergas_art.params_flag == true then return end
	local act = db.actor
	local gg_heal  = 15*(math.ceil((db.actor.health - 0.01) * 10))

	local ph_t = get_value("ph_tiredness", 0) -- накопленна€ физическа€ усталость, восстанавливаетс€ со временем

	local delay = tiredness_timer:elapsed(true) / 60.0 -- сколько игровых минут между замером    

	local sleepiness = sleep_manager.get_sleepiness()

	local state = actor_body_state()
	local sleep = sleep_manager.is_sleep_active()

	local delta = -0.1

	if state.crouch then delta = delta + 0.1 end
	if state.sprint then delta = delta + 0.1 end
	if state.jump   then delta = delta + 0.5 end  

	if act.power == act.max_power and ph_t > 5 then
		ph_t = ph_t * 0.98 -- 2% процентное восстановление при высокой усталости
	end  
								 
	local have_power = ( act.power + 0.1 ) / act.max_power  -- краткосрочна€ перегрузка
	local action = "ADD"
	if sleep then 
		action = "RESTOR"
		have_power = 1
		delta = delta * sleep_manager.restore_coef() -- в защите, с оружием и рюкзаком спать неудобно!
	else   
		delta = delta + (act.max_power - act.power)
		sleepiness = sleepiness + delay / 6.0       -- раз в 360 игровых секунд добавл€етс€ 1 пункт сонливости
	end  

	if delta < 0 and ph_t < 0 then
		if (not sleep) or (ph_t < -100) then
			delta = 0
		end     
	end 

	ph_t = ph_t + delta * delay         
	if (delta > 0) and (not sleep) then
		sleepiness = sleepiness + delta * delay * 0.1 -- физическа€ нагрузка приближает желание поспать
	end

	if sleepiness > 270 then
		sleepiness = 270
	end

	local diff = sleep_manager.change_sleepiness(sleepiness)

	set_value("ph_tiredness", ph_t)

	local new_coef = ( 960 + sleepiness + ph_t ) / ( 700 + 100 * have_power + gg_heal )
	if new_coef < 1 then new_coef = 1 end

	local wpn_wobble = math.min (1.5, new_coef / 1.5)
	wpn_wobble = math.max(wpn_wobble, 0.9) 
	wpn_params.gg_tired = wpn_wobble * wpn_wobble 

	local new_run_coef    = run_coef    / new_coef
	local new_sprint_koef = sprint_koef / new_coef
	local new_walk_accel  = walk_accel  / new_coef
	local new_climb_coef  = climb_coef  / new_coef
	local inert= math.floor( 8 - (db.actor.health * 5)) * 0.1
	inert = math.min(inert, 0.5)
	inert = sprintf ('%.2f', inert)  
	-- cam_inert=~C0D %s~C07 inert,
	-- wprintf("~C1F[~T]. #TIREDNESS_%s:~C17 new_coef =~C1D %.5f~C17, sleepiness =~C1D %.3f~C17, stamina =~C1D %.3f~C17 (max_power =~C1D %.1f~C17), pht =~C1D %.3f~C17, diff =~C1D %.4f~C17, delay =~C1D %.1f~C17 min ~C07",
									 -- action, new_coef, sleepiness, have_power, act.max_power, ph_t, diff, delay)
	-- wprintf("~C0A %s~C07", lua_traceback(' '))
	ww_power = w_w_power * new_coef
	act.max_power = 1 - ph_t * 0.02

	if get_console():get_bool("g_god") then
		new_walk_accel = 17
		new_run_coef = 2.1
		new_sprint_koef = 2.6
		new_climb_coef = 0.7
		actor_params.actor_prop("jump_speed",  7.6)
		inert = 0
	end
	
	local penalty = 1
	if db.actor.satiety <= 0.2 then
		penalty = penalty - 0.1
	end
	local slp = sleep_manager.get_sleepiness(108)
	if slp >= 175 then
		penalty = penalty - 0.1
	end

	actor_params.actor_prop("run_coef",    new_run_coef * penalty)
	actor_params.actor_prop("sprint_koef", new_sprint_koef * penalty)
	actor_params.actor_prop("walk_accel",  new_walk_accel * penalty)
	actor_params.actor_prop("climb_coef",  new_climb_coef * penalty)
	tired_owermass()

	if prev_inert ~= inert then
		cmd("cam_inert", inert)
		cmd("cam_inert_sprint", inert)
		prev_inert = inert
	end
end
function container_weight_add(container_id, add)
  if container_id then     
       set_inv_weight(container_id, add)
  end
end
local max_weight = system_ini():r_float("inventory", "max_weight")
local max_walk_weight = system_ini():r_float("actor_condition", "max_walk_weight")
function max_item_mass_add(add)
  local new_max_weight = max_weight+add+(sak.mass_add)
  local new_weight = max_walk_weight+add+(sak.mass_add)
  actor_params.inv_prop("max_weight", new_max_weight)
  actor_params.cond_prop("max_walk_weight", new_weight)
end

local psy_health_v = system_ini():r_float("actor_condition", "psy_health_v")
function psy_restore_speed_add(add)
  local new_psy = psy_health_v+add
  actor_params.cond_prop("psy_health_v", new_psy)
end

function tired_owermass()
  --[[local carr_norm = actor_params.inv_prop("max_weight")+add_outfit_weight+pwr_restore+add_coll
  local carr_weight = actor_params.inv_prop("total_weight")
  local new_weight_power=ww_power    
  if carr_weight>carr_norm then
      local coef=(carr_weight-carr_norm)
    new_weight_power=ww_power+0.0000005*(coef^2)
  end
    actor_params.cond_prop("walk_weight_power", ww_power) -- остальное добавит движок через коэффициенты перевеса ]]
  -- actor_params.cond_prop("walk_weight_power", new_weight_power)
end

function radiation_add(add)
  local radiat = actor_params.cond_prop("radiation")
  local r_health=radiat+add
  if r_health>1 then r_health=1 end
  actor_params.cond_prop("radiation", r_health)
end
function health_add(add)
  local healt = actor_params.cond_prop("health")
  local health=healt+add
  if health>1 then health=1 end
 
    if health <= 0 then
       --wprintf(" heath_add: %.3f += %.3f   actor killing from: \n %s ", healt, add, debug.traceback(" ", 2))
       -- health = 1
    end
 
  if health < 0 then health=0 end
 
  actor_params.cond_prop("health", health)
end
local psy_health_v = system_ini():r_float("actor_condition", "psy_health_v")
function psy_health_v_add(key)
  local new_psy_health_v = psy_health_v*key 
  actor_params.cond_prop("psy_health_v", new_psy_health_v) 
end

function satiety_v_add (multv, divider)
  -- local satiety_v = balance.satiety.lost_velocity
  local satiety_v = 0.000004
  --  
  local new_satiety_v = satiety_v * multv / divider
  local prev_v = actor_params.cond_prop("satiety_v")
  actor_params.cond_prop("satiety_v", new_satiety_v)  
  if math.abs (prev_v - new_satiety_v) > 0.00001  then 
     wprintf("[~T]. #DBG: satiety velocity updated from~C0D %8f~C07 to~C0D %.8f~C07, satiety health =~C0D %.8f~C07", prev_v, new_satiety_v, params.actor_satiety_health())
     -- wprintf("\t\t from:~C0A %s~C07", lua_traceback(' '))
  end       
end
function health_v_add (multv, divider)
  -- local health_v = balance.health.restore_speed       
  local health_v = 0.000001
  local new_health_v = health_v * multv / divider
  local new_bleed_v = (health_v * 20) * multv / divider
  actor_params.cond_prop("health_restore_v",    new_health_v)
  actor_params.cond_prop("satiety_health_v",    new_health_v)
  actor_params.cond_prop("wound_incarnation_v", new_bleed_v)
end

function satiety_add(add)
  if sleep_manager.sleeping then return end
  local satiety = actor_params.cond_prop("satiety")
  local s_health=satiety+add
  if s_health<0 then s_health=0 end
  actor_params.cond_prop("satiety", s_health)
end
function actor_health_v()
  for k, v in pairs(actor_params.condition_params) do
      local b = actor_params.cond_prop(k)
  end
end
function actor_satiety_health()
  return actor_params.cond_prop("satiety")
end
function actor_bleeding()
    -- local blood = 0                                      
    -- local bcnt = 5
    -- local kobj = xray_visual.GetKinematics (get_actor_obj())
    -- if kobj then
    --    bcnt = kobj:LL_BoneCount()
    -- end 
    
    -- for b = 0, bcnt - 1 do 
    --     blood = blood + actor_params.get_wound_total_size(b)
    -- end    
  return blood or 0
end                                
function psy_health_add(add)
  local p_heal = actor_params.cond_prop("psy_health")
  local p_health=p_heal+add
  if p_health<0 then p_health=0 end
  actor_params.cond_prop("psy_health", p_health)
end

function power_health_add(add)
  actor_params.cond_prop("power", add)
end
function power_max_out(par)
  actor_params.cond_prop("power_max", par)
end
function bleeding_add(add)
  --local b_heal = actor_params.getp("wound_3")
  --local b_health=b_heal+add
  --if b_health<0 then b_health=0 end
    -- TODO: refactor
  -- actor_params.cond_prop("wound_3", add)
end
function actor_alcohol_health()
  return actor_params.cond_prop("alcohol_health")
end
function actor_psy_health()
  return actor_params.cond_prop("psy_health")
end
local jump_speed = system_ini():r_float("actor", "jump_speed")
function jump_speed_add(add)
  local new_jump_speed = jump_speed+add
  actor_params.actor_prop("jump_speed", new_jump_speed)
end
function move_speed_set(val)
	if not sak.game_began then return end
	if val == 0 then -- Sn: для принудительной проверки действия энергетика
		db.actor.speed_multiplier = 1
		arc_arts.check_artefact()
		return
	else
		db.actor.speed_multiplier = val
	end
	-- log2("move_speed_set: db.actor.speed_multiplier [%.2f]",db.actor.speed_multiplier)
end
local air_control_param = system_ini():r_float("actor", "air_control_param")
function air_param_add(add)
  local new_air_control_param = air_control_param*add
  actor_params.cond_prop("air_control_param", new_air_control_param)
end

function belt_param_add(count)
  -- log2("belt_param_add: %s", count)
  count = count or 0
  local new_belt_param = count        
  if count ~= 0 then count = count - 1 end -- потому что одна €чейка уходит на аккумул€тор по старой логике
    -- wprintf("[~T]. #DBG: belt_param_add value =~C0D %d~C07", add)
  wprintf(" max_belt updated to~C0D %d~C07", count)     
  db.actor.inventory.max_belt_custom = count                   
  -- actor_params.inv_prop("max_belt", count, true)
  if new_belt_param == 1 then  
     new_belt_param = 0
  end
  texman.swap_belt(new_belt_param)      
end

--trade_flag_byte: true = 246 ($F6), false = 242 ($F2)
--2 (4) = trade flag
--3 (8) = belt flag
--6 (64) = default_to_ruck
--7 (128) = sprint_allowed

function params.start_dialog(dlg, hide_indicators)
--  if ui.start_dialog then
--     return ui.start_dialog(dlg, hide_indicators) -- build 5600+
--  end

 local IR = level.main_input_receiver() 
 if dlg and (IR == nil) then
   -- если статус окна не соответствует требуемому
  if not dlg:IsShown() then
    level.start_stop_menu(dlg, hide_indicators)              
  end       
 end
end

function params.stop_dialog(dlg)
--  if ui.stop_dialog then
--     return ui.stop_dialog(dlg) -- build 5600+
--  end

 -- если статус окна не соответствует требуемому
 if dlg and dlg:IsShown() then
    level.start_stop_menu(dlg, false)              
 end       
 
end

function obj_condition(id, newval)
  local obj = client_obj(id)
  if obj then 
    cl_condition[id] = nil
    local cond = obj:condition()
    if newval then
       obj:set_condition(newval)
    end             
    return cond
  else
    cl_condition[id] = newval    
  end
  
  if server_obj(id) then 
     return 1 -- хрен ведь угадаешь, ага?
  else
     return -1
  end     
end

function params.get_condition(obj, limit)
 limit = limit or 100
 local id = misc.get_object_id(obj)
 
 obj = client_obj (id) 
 if obj then
    local cv = obj:condition() 
    if cv > limit then cv = limit end
    if cv > 0 and cv < 10 then return cv end 
 end
  
 local sobj = g_sim:object(id)
 if sobj then 
    local pk = get_netpk(obj, 1)
    local data = pk:get()
    if data.condition > limit then 
      return limit
    else    
      return data.condition
    end   
 end     
 
 return -1
end 
 
function params.upd_condition(obj, newval)
 local id = misc.get_object_id(obj)
 local sobj = obj 
 if (type(sobj) ~= 'userdata') or (nil == sobj.m_game_vertex_id) then
    sobj = g_sim:object(id)
 end
    
 if sobj then 
	local new_cond = newval
    local pk = get_netpk(sobj, 1)
    local data = pk:get()
    data.condition = new_cond
    pk:set(data)
 end 
 obj_condition(id, newval)
end

function add_condition(obj, add)
 local cv = params.get_condition(obj, 0.9999) or 0
 if cv >= 0 then
    cv = cv + add
    params.upd_condition (obj, cv)    
 end      
 return cv
end

function set_obj_usable(id, newval)
 local obj = client_obj(id) 
 if obj then 
    obj:set_nonscript_usable(newval)
 end                                       
end

function late_init()
 if get_value("ph_tiredness") > 30 then 
    set_value("ph_tiredness", 5)
 end 
 --db.g_statics = {}
 --get_hud():RemoveCustomStatic("dynamic_hud")  
 --wprintf(" test params:~C0F %s ~C07", params.show())
end

function on_cl_spawned(list) -- postponed update condition
 for i, id in ipairs(list) do
  if cl_condition[id] then
     obj_condition(id, cl_condition[id])
  end
 end
end

-- Manool: проще через серверный объект помен€ть да и всЄ
function post_cond_check(id, newval)
  local sobj = id and server_obj(id)
  if sobj then
    local iitem = sobj:get_inventory_item()
    if iitem then iitem.item_condition = newval end
  end
end

-- [HE-PORT] zapret prodazhi predmeta (NLC HE)
function cant_trade_add( id )
	local value = item_params.item_prop( id, "item_flags" )
	value = bit_and( value, 65535 - global_flags.FCanTrade )
	item_params.item_prop( id, "item_flags", value )
end

function can_trade_add( id )
	local value = item_params.item_prop( id, "item_flags" )
	value = bit_or( value, global_flags.FCanTrade )
	item_params.item_prop( id, "item_flags", value )
end
